//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class BrandProfileFuwuSectionData, NSMutableArray;

@interface BrandProfileFuwuCell : UITableViewCell
{
    NSMutableArray *_buttonList;
    id <BrandProfileFuwuCellDelegate> _delegate;
    BrandProfileFuwuSectionData *_sectionData;
}

@property(retain, nonatomic) BrandProfileFuwuSectionData *sectionData; // @synthesize sectionData=_sectionData;
@property(nonatomic) __weak id <BrandProfileFuwuCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onFuwuButtonClicked:(id)arg1;
- (void)addCornerToContentView:(unsigned long long)arg1;
- (void)layoutContentView;
- (void)layoutSubviews;
- (void)setupSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

