//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IFTSIndexOperation.h"
#import "IFavoritesExt.h"

@class FTSDB, FTSFavDB, FTSFavIndexState, NSObject<OS_dispatch_queue>, NSString;

@interface FTSFavIndexMgr : NSObject <IFavoritesExt, IFTSIndexOperation>
{
    _Bool _isInIndexingLoop;
    _Bool _pause;
    _Bool _canceled;
    int _currentPriority;
    FTSFavIndexState *_favIndexState;
    _Bool _hasInitSource;
    _Bool _hasIndexTask;
    _Bool _hasVerifyTask;
    int _iFTSIndexingType;
    FTSFavDB *_ftsFavDB;
    NSObject<OS_dispatch_queue> *_taskQueue;
    FTSDB *_ftsDB;
}

@property(retain, nonatomic) FTSDB *ftsDB; // @synthesize ftsDB=_ftsDB;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *taskQueue; // @synthesize taskQueue=_taskQueue;
@property(retain, nonatomic) FTSFavDB *ftsFavDB; // @synthesize ftsFavDB=_ftsFavDB;
@property(nonatomic) int iFTSIndexingType; // @synthesize iFTSIndexingType=_iFTSIndexingType;
- (void).cxx_destruct;
- (_Bool)internalIndexingInsertTask;
- (_Bool)internalIndexingUpdateTask;
- (_Bool)internalIndexingDeleteTask;
- (_Bool)internalIndexingDropTask;
- (void)fireMsgIndexingTaskLoop;
- (void)delayRunIndexTask;
- (void)OnDelAllFavItem;
- (void)OnDelFavoritesItems:(id)arg1;
- (void)OnModFavoritesItem:(id)arg1;
- (_Bool)trySaveIndexState;
- (void)tryLoadIndexState;
- (id)pathForIndexState;
- (void)iFTSIndexingReloadDB;
- (void)iFTSIndexingMemoryWarning;
- (void)iFTSIndexingStop;
- (void)iFTSIndexingPause;
- (void)iFTSIndexingFireTask:(int)arg1;
- (void)iFTSIndexingPrepareSearch;
- (void)iFTSIndexingInit;
- (void)traceIndexState;
- (void)doInitIndexing;
- (void)makeSureInitIndexing;
- (void)asyncInitIndex;
- (void)dealloc;
- (id)initWithFTSDB:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

