//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MatrixAppRebootAnalyzer : NSObject
{
}

+ (_Bool)isOSReboot;
+ (unsigned long long)getSystemLaunchTimeStamp;
+ (_Bool)isOSChange;
+ (_Bool)isAppChange;
+ (id)lastDumpFileName;
+ (void)setDumpFileName:(id)arg1;
+ (void)isForegroundMainThreadBlock:(_Bool)arg1;
+ (id)userSceneOfLastRun;
+ (void)setUserScene:(id)arg1;
+ (void)notifyAppWillSuspend;
+ (void)notifyAppBackgroundFetch;
+ (void)notifyAppEnterBackground;
+ (void)notifyAppEnterForeground;
+ (void)notifyAppCrashed;
+ (void)notifyAppQuitByUser;
+ (void)notifyAppQuitByExit;
+ (unsigned long long)lastAppLaunchTime;
+ (unsigned long long)appLaunchTime;
+ (unsigned long long)lastRebootType;
+ (_Bool)isAfterLastLaunchUserRebootDevice;
+ (void)checkRebootType;
+ (void)installAppRebootAnalyzer;

@end

