//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMKView.h"

@class MMKSwitchViewOnChangeSwitchCallback;

@protocol MMKSwitchView <MMKView>
- (void)setOnChangeSwitchCallback:(MMKSwitchViewOnChangeSwitchCallback *)arg1;
- (_Bool)getEnabled;
- (void)setEnabled:(_Bool)arg1;
- (_Bool)getOn;
- (void)setOn:(_Bool)arg1;
- (id <MMKImage>)getOffImage;
- (void)setOffImage:(id <MMKImage>)arg1;
- (id <MMKImage>)getOnImage;
- (void)setOnImage:(id <MMKImage>)arg1;
- (long long)getThumbTintColor;
- (void)setThumbTintColor:(long long)arg1;
- (long long)getTintColor;
- (void)setTintColor:(long long)arg1;
- (long long)getOnTintColor;
- (void)setOnTintColor:(long long)arg1;
@end

