//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TTFaceAlignmenter : NSObject
{
    _Bool _faceTrackRefineEnable;
    _Bool _shouldDeleteRunner;
    struct YTFaceAlignment *_faRunner;
}

+ (int)GlobalRelease;
+ (int)GlobalInitWithPath:(id)arg1;
@property(nonatomic) _Bool shouldDeleteRunner; // @synthesize shouldDeleteRunner=_shouldDeleteRunner;
@property(nonatomic) struct YTFaceAlignment *faRunner; // @synthesize faRunner=_faRunner;
@property(nonatomic) _Bool faceTrackRefineEnable; // @synthesize faceTrackRefineEnable=_faceTrackRefineEnable;
- (int)trackImage:(id)arg1 faceFeature:(id)arg2;
- (id)initWithRunner:(struct YTFaceAlignment *)arg1 freeWhenDone:(_Bool)arg2;
- (void)dealloc;
- (id)init;
- (id)initWithRunner:(struct YTFaceAlignment *)arg1;

@end

