//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCBaseCgi.h"

@class NSArray, NSString;

@interface WASubscriptionMessageRequestListByIDCgi : WCBaseCgi
{
    NSArray *_templateArray;
    NSString *_subscriptionUrl;
    NSString *_username;
    unsigned long long _scene;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failBlock;
}

@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *subscriptionUrl; // @synthesize subscriptionUrl=_subscriptionUrl;
@property(retain, nonatomic) NSArray *templateArray; // @synthesize templateArray=_templateArray;
- (void).cxx_destruct;
- (void)didFailWithError:(id)arg1 reponse:(id)arg2;
- (void)didGetResponse:(id)arg1;
- (id)generateItemListWith:(id)arg1;
- (void)createRequest;
- (id)initWithSubscriptionUrl:(id)arg1 username:(id)arg2 scene:(unsigned long long)arg3 successBlock:(CDUnknownBlockType)arg4 failBlock:(CDUnknownBlockType)arg5;
- (id)initWithTemplateArray:(id)arg1 username:(id)arg2 scene:(unsigned long long)arg3 successBlock:(CDUnknownBlockType)arg4 failBlock:(CDUnknownBlockType)arg5;

@end

