//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCStackFeatPool;

@interface WCFilterStackHandler : NSObject
{
    WCStackFeatPool *_stackFeatPool;
}

@property(retain, nonatomic) WCStackFeatPool *stackFeatPool; // @synthesize stackFeatPool=_stackFeatPool;
- (void).cxx_destruct;
- (unsigned long long)addStackFeat:(unsigned long long)arg1;
- (void)saveStackFeat;
- (void)loadStackFeat;
- (id)init;

@end

