//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSString, WCHardLinkMergeOperation;

@interface WCHardLinkService : MMService <MMService>
{
    WCHardLinkMergeOperation *_mergeOperation;
}

+ (void)setStateOfOpenHardLink:(_Bool)arg1;
+ (_Bool)getStateOfOpenHardLink;
+ (id)getLinkToInfo;
+ (id)getBeLinkedInfo;
+ (void)removeLinkInfo;
+ (void)setCurrentLink:(id)arg1 with:(id)arg2;
+ (void)setStateOfHardLinkDone:(_Bool)arg1;
+ (_Bool)getStateOfHardLinkDone;
+ (id)getRelatedMemoryKV;
@property(retain, nonatomic) WCHardLinkMergeOperation *mergeOperation; // @synthesize mergeOperation=_mergeOperation;
- (void).cxx_destruct;
- (void)tryToHardLinkSameFile;
- (void)onServiceReloadData;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

