//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface WCSessionFlowConfigModel : MMObject <PBCoding>
{
    NSMutableArray *sessionsArray;
    NSMutableArray *blackListPages;
    NSMutableArray *mainTabPages;
    NSMutableArray *filterPages;
    NSString *originalJson;
    NSMutableDictionary *_sessionsDicForPageName;
    NSMutableDictionary *_sessionsDicForSid;
}

+ (void)initialize;
@property(retain, nonatomic) NSMutableDictionary *sessionsDicForSid; // @synthesize sessionsDicForSid=_sessionsDicForSid;
@property(retain, nonatomic) NSMutableDictionary *sessionsDicForPageName; // @synthesize sessionsDicForPageName=_sessionsDicForPageName;
@property(retain, nonatomic) NSString *originalJson; // @synthesize originalJson;
@property(retain, nonatomic) NSMutableArray *filterPages; // @synthesize filterPages;
@property(retain, nonatomic) NSMutableArray *mainTabPages; // @synthesize mainTabPages;
@property(retain, nonatomic) NSMutableArray *blackListPages; // @synthesize blackListPages;
@property(retain, nonatomic) NSMutableArray *sessionsArray; // @synthesize sessionsArray;
- (void).cxx_destruct;
- (id)toString;
- (void)initCacheDictionary;
- (id)init;
- (const map_f8690629 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

