//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ContactSelectViewDelegate.h"

@class NSString;

@interface WCTimeLineContactSelectViewController : MMUIViewController <ContactSelectViewDelegate>
{
    id <WCTimeLineContactSelectViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (id)getSafeSearchViewController;
- (_Bool)onFilterContactCandidate:(id)arg1;
- (void)onSelectContact:(id)arg1;
- (void)onCancelBack:(id)arg1;
- (void)initTitleArea;
- (void)initView;
- (void)viewDidLoad;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

