# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyMobIMTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Hyphenate'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'SDWebImage/GIF'
  pod 'FLAnimatedImage'

end
