//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNNetworkTransport.h"

#import "_QNNetworkTransportSessionProtocol.h"

@class NSString, NSURL;

@interface _QNNetworkTransportNSURLSession : QNNetworkTransport <_QNNetworkTransportSessionProtocol>
{
    NSString *_hashString;
    BOOL _requestMethod;
    NSURL *_baseURL;
    NSString *_urlString;
    NSString *_cancelToken;
    long long _toleranceHostIndex;
}

@property long long toleranceHostIndex; // @synthesize toleranceHostIndex=_toleranceHostIndex;
@property(copy, nonatomic) NSString *cancelToken; // @synthesize cancelToken=_cancelToken;
@property(copy, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(copy, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
@property(nonatomic) BOOL requestMethod; // @synthesize requestMethod=_requestMethod;
- (void).cxx_destruct;
- (unsigned long long)_responseStringEncodingFrom:(id)arg1;
- (void)handleTaskMetrics:(id)arg1;
- (void)handleTaskFailed:(id)arg1 error:(id)arg2;
- (void)handleTaskSuccess:(id)arg1 responseObject:(id)arg2;
- (id)_filterPostValues:(id)arg1;
- (id)_updateBaseURL:(id)arg1;
- (void)_startRequest;
- (void)cancel;
- (void)startWithDelegate:(id)arg1;
@property(readonly, copy) NSString *description;
- (_Bool)isEqualToSessionTransport:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)hashString;
@property(readonly) unsigned long long hash;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

