//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WKNavigationDelegate.h"
#import "WKUIDelegate.h"

@class NSString, QNWeakArray;

@interface _QNWebViewDelegateDispatcher : NSObject <WKNavigationDelegate, WKUIDelegate>
{
    id <WKNavigationDelegate> _mainNavigationDelegate;
    QNWeakArray *_navigationDelegates;
    QNWeakArray *_UIDelegates;
}

@property(readonly, nonatomic) QNWeakArray *UIDelegates; // @synthesize UIDelegates=_UIDelegates;
@property(readonly, nonatomic) QNWeakArray *navigationDelegates; // @synthesize navigationDelegates=_navigationDelegates;
@property(nonatomic) __weak id <WKNavigationDelegate> mainNavigationDelegate; // @synthesize mainNavigationDelegate=_mainNavigationDelegate;
- (void).cxx_destruct;
- (void)webView:(id)arg1 runJavaScriptTextInputPanelWithPrompt:(id)arg2 defaultText:(id)arg3 initiatedByFrame:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)webView:(id)arg1 runJavaScriptConfirmPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (_Bool)p_canShowPanelWithWebView:(id)arg1;
- (id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalNavigation:(id)arg2;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (_Bool)containsUIDelegate:(id)arg1;
- (void)removeAllUIDelegates;
- (void)removeUIDelegate:(id)arg1;
- (void)addUIDelegate:(id)arg1;
- (_Bool)containsNavigationDelegate:(id)arg1;
- (void)removeAllNavigationDelegates;
- (void)removeNavigationDelegate:(id)arg1;
- (void)addNavigationDelegate:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

