//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAlertView;

@interface CAppStore : UIView
{
    CAlertView *_alertView;
}

+ (id)sharedCAppStore;
@property(retain, nonatomic) CAlertView *alertView; // @synthesize alertView=_alertView;
- (void).cxx_destruct;
- (void)alertview:(id)arg1 buttonClickedWithTitle:(id)arg2;
- (void)update:(id)arg1 msg:(id)arg2;
- (_Bool)isNeedUpdate:(id)arg1;
- (void)gotoHomepageInAppStore;
- (id)getHomepageURLInAppStore;

@end

