//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCarBaseManager.h"

@class NSMutableDictionary, NSString;

@interface CCarConditionTypeManager : CCarBaseManager
{
    NSMutableDictionary *_carConditionDict;
    NSString *_typeVersion;
}

+ (id)getConditionTypeList;
@property(copy, nonatomic) NSString *typeVersion; // @synthesize typeVersion=_typeVersion;
@property(retain, nonatomic) NSMutableDictionary *carConditionDict; // @synthesize carConditionDict=_carConditionDict;
- (void).cxx_destruct;
- (id)calculateConfig:(id)arg1 andItemList:(id)arg2;
- (void)writeToDisk;
- (void)dataLoaderDownLoadDataFailed:(id)arg1;
- (void)dataLoaderDownLoadDataComplete:(id)arg1;
- (id)parseJSONResponse:(id)arg1;
- (id)getRequestURL;
- (void)startRequestWithOptionConfig;
- (void)dealloc;
- (id)init;

@end

