//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface CCarCityItem : NSObject <NSCoding>
{
    _Bool _isDiscnt;
    NSString *_cityId;
    NSString *_cityName;
    NSString *_location;
    NSString *_provinceId;
}

@property(nonatomic) _Bool isDiscnt; // @synthesize isDiscnt=_isDiscnt;
@property(copy, nonatomic) NSString *provinceId; // @synthesize provinceId=_provinceId;
@property(copy, nonatomic) NSString *location; // @synthesize location=_location;
@property(copy, nonatomic) NSString *cityName; // @synthesize cityName=_cityName;
@property(copy, nonatomic) NSString *cityId; // @synthesize cityId=_cityId;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithInfoDic:(id)arg1;
- (void)dealloc;

@end

