//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNRootViewController.h"

#import "CCarNoResultViewDelegarte.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CCarNoResultView, NSMutableArray, NSString, QNCarLoaderApi, UITableView;

@interface CCarResultListController : QNRootViewController <UITableViewDelegate, UITableViewDataSource, CCarNoResultViewDelegarte>
{
    _Bool _isFinishLoading;
    _Bool _isDownLoading;
    _Bool _isGetMore;
    long long _totalCnt;
    UITableView *_tableView;
    NSMutableArray *_resultArray;
    CCarNoResultView *_noRetView;
    NSMutableArray *_defaultBtnArray;
    long long _currPage;
    QNCarLoaderApi *_carLoaderRequest;
}

@property(retain, nonatomic) QNCarLoaderApi *carLoaderRequest; // @synthesize carLoaderRequest=_carLoaderRequest;
@property(nonatomic) long long currPage; // @synthesize currPage=_currPage;
@property(retain, nonatomic) NSMutableArray *defaultBtnArray; // @synthesize defaultBtnArray=_defaultBtnArray;
@property(retain, nonatomic) CCarNoResultView *noRetView; // @synthesize noRetView=_noRetView;
@property(retain, nonatomic) NSMutableArray *resultArray; // @synthesize resultArray=_resultArray;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool isGetMore; // @synthesize isGetMore=_isGetMore;
@property(nonatomic) long long totalCnt; // @synthesize totalCnt=_totalCnt;
- (void).cxx_destruct;
- (void)scroll2Top;
- (void)clickDefaultBtnToSearch:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)getMoreItemList;
- (_Bool)isReachEnd;
- (void)dataLoaderDownLoadDataFailed:(id)arg1;
- (void)getMoreDone:(_Bool)arg1;
- (void)dataLoaderDownLoadDataComplete:(id)arg1;
- (id)parseJSONResponse:(id)arg1;
- (id)getRequestURL;
- (id)p_createUrl;
- (void)p_startRequestWithDataType:(long long)arg1 inputDic:(id)arg2;
- (void)requestWithSearchOptionForResultList;
- (void)dismissWaitingView;
- (void)showWaitingView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)dealloc;
- (void)carResultListThemeChanged;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

