//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class CCarRecommendItem;

@interface CCarRecommentBtn : UIButton
{
    CCarRecommendItem *_rOptionItem;
}

@property(retain, nonatomic) CCarRecommendItem *rOptionItem; // @synthesize rOptionItem=_rOptionItem;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

