//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface CCustomButton : UIButton
{
    int _buttonStyle;
}

+ (id)stretchImg:(id)arg1 vertical:(float)arg2;
+ (id)buttonWithTitle:(id)arg1 style:(int)arg2;
- (void)setHidden:(_Bool)arg1;
- (void)changeTheme;
- (void)dealloc;
- (void)setTitle:(id)arg1 style:(int)arg2;
- (id)imageWithStyle:(int)arg1 forState:(unsigned long long)arg2;

@end

