//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QNFinanceMarketSummaryApi;

@interface CMarketSummaryDataRequest : NSObject
{
    id <CMarketSummaryDataRequestDelegate> _marketSummaryDataRequestDelegate;
    QNFinanceMarketSummaryApi *_api;
}

@property(retain, nonatomic) QNFinanceMarketSummaryApi *api; // @synthesize api=_api;
@property(nonatomic) __weak id <CMarketSummaryDataRequestDelegate> marketSummaryDataRequestDelegate; // @synthesize marketSummaryDataRequestDelegate=_marketSummaryDataRequestDelegate;
- (void).cxx_destruct;
- (void)getMarketSummaryData;
- (void)dealloc;
- (id)init;

@end

