//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CPictureCache : NSObject
{
    NSMutableDictionary *_cache;
    NSMutableDictionary *_order;
}

+ (id)alloc;
+ (id)sharedPictureCache;
@property(retain) NSMutableDictionary *order; // @synthesize order=_order;
@property(retain) NSMutableDictionary *cache; // @synthesize cache=_cache;
- (void).cxx_destruct;
- (void)dealloc;
- (void)clearAll;
- (void)appendPicture:(id)arg1 forUrl:(id)arg2 category:(id)arg3;
- (id)getPicture:(id)arg1 category:(id)arg2;
- (_Bool)containPicture:(id)arg1 category:(id)arg2;
- (id)init;

@end

