//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableArray, NSString;

@interface CPortfolioGroupData : NSObject <NSCoding>
{
    _Bool _hasSorted;
    _Bool _hasStockSorted;
    NSString *_groupId;
    NSString *_groupTempId;
    NSString *_groupName;
    long long _groupOrder;
    NSMutableArray *_stocks;
}

+ (id)parserPortfolioGroupData:(id)arg1;
@property(nonatomic) _Bool hasStockSorted; // @synthesize hasStockSorted=_hasStockSorted;
@property(nonatomic) _Bool hasSorted; // @synthesize hasSorted=_hasSorted;
@property(retain, nonatomic) NSMutableArray *stocks; // @synthesize stocks=_stocks;
@property(nonatomic) long long groupOrder; // @synthesize groupOrder=_groupOrder;
@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(copy, nonatomic) NSString *groupTempId; // @synthesize groupTempId=_groupTempId;
@property(copy, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithGroupId:(id)arg1 GroupName:(id)arg2;
- (id)awakeAfterUsingCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

