//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CRSA : NSObject
{
    struct rsa_st *_rsa;
}

+ (id)shareInstance;
- (id)decryptByRsa:(id)arg1 keyType:(int)arg2 withKey:(id)arg3;
- (id)encryptByRsa:(id)arg1 keyType:(int)arg2 withKey:(id)arg3;
- (_Bool)_readRSAKey:(int)arg1 withKey:(id)arg2;
- (int)getBlockSizeWithRSA_PADDING_TYPE:(int)arg1;

@end

