//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSMutableArray, NSString;

@interface CSectionItemType : NSObject <NSCoding, NSCopying>
{
    _Bool _skipLoadMore;
    NSString *_sectionName;
    NSMutableArray *_sectionList;
    NSMutableArray *_indexList;
    long long _adCount;
    NSString *_secType;
}

@property(nonatomic) _Bool skipLoadMore; // @synthesize skipLoadMore=_skipLoadMore;
@property(retain, nonatomic) NSString *secType; // @synthesize secType=_secType;
@property(nonatomic) long long adCount; // @synthesize adCount=_adCount;
@property(retain, nonatomic) NSMutableArray *indexList; // @synthesize indexList=_indexList;
@property(retain, nonatomic) NSMutableArray *sectionList; // @synthesize sectionList=_sectionList;
@property(copy, nonatomic) NSString *sectionName; // @synthesize sectionName=_sectionName;
- (void).cxx_destruct;
- (void)dealloc;
- (id)loadMoreIDsWithCount:(long long)arg1;
- (_Bool)insertAdListItem:(id)arg1 atIndex:(long long)arg2;
- (_Bool)appendListItems:(id)arg1;
- (_Bool)canLoadMore;
- (void)validateSectionListWithListItemDict:(id)arg1;
- (id)listItemDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

