//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DownloadCache : NSObject
{
}

+ (id)sharedInstance;
- (void)clearAllCache;
- (void)clearCacheForURL:(id)arg1;
- (_Bool)cacheURL:(id)arg1 forURL:(id)arg2;
- (_Bool)cacheFile:(id)arg1 forURL:(id)arg2;
- (_Bool)cacheData:(id)arg1 forURL:(id)arg2;
- (id)fileForURL:(id)arg1;
- (id)dataForURL:(id)arg1;
- (_Bool)hasCachedForURL:(id)arg1;
- (id)tempFile:(id)arg1;
- (id)cacheFile:(id)arg1;
- (id)cacheKey:(id)arg1;
- (id)tempPath;
- (id)cachePath;
- (unsigned long long)totalSize;

@end

