//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GRMustacheInheritablePartialNode, GRMustacheInheritableSectionNode, GRMustachePartialNode, GRMustacheSectionTag, GRMustacheTemplateAST, GRMustacheTextNode, GRMustacheVariableTag;

@protocol GRMustacheTemplateASTVisitor <NSObject>
- (_Bool)visitTextNode:(GRMustacheTextNode *)arg1 error:(id *)arg2;
- (_Bool)visitSectionTag:(GRMustacheSectionTag *)arg1 error:(id *)arg2;
- (_Bool)visitVariableTag:(GRMustacheVariableTag *)arg1 error:(id *)arg2;
- (_Bool)visitPartialNode:(GRMustachePartialNode *)arg1 error:(id *)arg2;
- (_Bool)visitInheritableSectionNode:(GRMustacheInheritableSectionNode *)arg1 error:(id *)arg2;
- (_Bool)visitInheritablePartialNode:(GRMustacheInheritablePartialNode *)arg1 error:(id *)arg2;
- (_Bool)visitTemplateAST:(GRMustacheTemplateAST *)arg1 error:(id *)arg2;
@end

