//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<NSCoding>, NSObject<UITableViewDataSource>, NSObject<UITableViewDelegate>, QNBasicListDataAdapter<QNListDataAdapterSubclassProtocol>, QNBasicListViewModel<QNBasicListViewModelSubclassProtocol>, QNControllerMemeryInfo, QNListLoaderFailedResponse, QNListLoaderSuccessResponse, QNListTopToolBar, UIView;

@protocol KBListControllerSubclassProtocol <NSObject>
- (QNBasicListViewModel<QNBasicListViewModelSubclassProtocol> *)customViewModel;
- (QNBasicListDataAdapter<QNListDataAdapterSubclassProtocol> *)customListDataAdapter;

@optional
- (NSObject<NSCoding> *)subclassControllerStateForReusable;
- (void)recoverSubclassControllerState:(QNControllerMemeryInfo *)arg1;
- (_Bool)shouldRecoverSubclassControllerState:(QNControllerMemeryInfo *)arg1;
- (UIView *)customEmptyView;
- (long long)customTableViewStyle;
- (QNListTopToolBar *)customLIstTopToolBar;
- (NSObject<UITableViewDelegate> *)customTableViewDelegate;
- (NSObject<UITableViewDataSource> *)customTableViewDataSource;
- (void)showRecommendTipView:(QNListLoaderSuccessResponse *)arg1;
- (void)showBottomTipsView:(QNListLoaderSuccessResponse *)arg1;
- (void)showTopTipsView:(QNListLoaderSuccessResponse *)arg1;
- (void)setInfiniteScrollingViewReachEnd:(_Bool)arg1;
- (void)triggerInfiniteScrolling;
- (_Bool)canShowJumpToRecommendListTip;
- (void)modelDidPullData;
- (void)additionalOperationsAfterLoadModelFailed:(QNListLoaderFailedResponse *)arg1;
- (void)additionalOperationsAfterLoadModelSuccess:(QNListLoaderSuccessResponse *)arg1;
- (void)willInfiniteScrolling;
- (void)willPullToRefresh;
@end

