//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class QNBaseLabel, UIImageView, UIView;

@interface KBListSeparatorRefresh2 : QNThemableView
{
    QNBaseLabel *_customLabel;
    UIImageView *_refreshImageView;
    UIView *_textBackgroundView;
}

@property(retain, nonatomic) UIView *textBackgroundView; // @synthesize textBackgroundView=_textBackgroundView;
@property(retain, nonatomic) UIImageView *refreshImageView; // @synthesize refreshImageView=_refreshImageView;
@property(retain, nonatomic) QNBaseLabel *customLabel; // @synthesize customLabel=_customLabel;
- (void).cxx_destruct;
- (void)themeChanged:(long long)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)_preLayoutSubView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

