//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KBTemplateNormalRendering.h"

@interface KBTemplateCustomRenderingCSS : KBTemplateNormalRendering
{
}

- (id)renderForMustacheTag:(id)arg1 context:(id)arg2 HTMLSafe:(_Bool *)arg3 error:(id *)arg4;

@end

