//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface LKImageLogManager : NSObject
{
    NSMutableArray *_listenerList;
}

+ (id)logLevelStr:(unsigned long long)arg1;
+ (id)instance;
@property(retain, nonatomic) NSMutableArray *listenerList; // @synthesize listenerList=_listenerList;
- (void).cxx_destruct;
- (void)log:(unsigned long long)arg1 str:(id)arg2;
- (void)registerListener:(CDUnknownBlockType)arg1;

@end

