//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue;

@interface LKImageProcessorManager : NSObject
{
    NSOperationQueue *_queue;
}

+ (id)keyForProcessorList:(id)arg1;
+ (id)defaultManager;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)process:(id)arg1 request:(id)arg2 index:(long long)arg3 complete:(CDUnknownBlockType)arg4;
- (void)process:(id)arg1 request:(id)arg2 complete:(CDUnknownBlockType)arg3;
- (id)init;

@end

