//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LKImageLoader.h"

@interface LKImageMemoryImageLoader : LKImageLoader
{
}

- (void)imageWithRequest:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (_Bool)isValidRequest:(id)arg1;

@end

