//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MQQHttpRequest;

@interface MQQKCardNumberChecker : NSObject
{
    id <MQQKCardNumberCheckerDelegate> _delegate;
    MQQHttpRequest *_request;
}

@property(retain, nonatomic) MQQHttpRequest *request; // @synthesize request=_request;
@property(nonatomic) id <MQQKCardNumberCheckerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)httpRequestDidFail:(id)arg1;
- (void)httpRequestDidFinish:(id)arg1;
- (void)_reportWithInfo:(id)arg1;
- (void)_didFinishWithPhoneNumber:(id)arg1 error:(id)arg2;
- (id)_cellularIP;
- (_Bool)_isCurrentNetworkValid;
- (_Bool)_isCurrentCarrierValid;
- (void)cancelChecking;
- (_Bool)checkPhoneNumberWithProductID:(id)arg1;
@property(readonly, nonatomic) _Bool isChecking;
- (void)dealloc;

@end

