//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol MQQSharkDataDelegate <NSObject>
- (void)didSharkDataFailInAccessLayer;
- (void)didSharkDataFail:(const vector_aa1d262e *)arg1 errCode:(long long)arg2;
- (void)didSharkDataFinish:(const vector_aa1d262e *)arg1;
@end

