//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MQQWiFiInfo : NSObject
{
    NSString *_SSID;
    NSString *_BSSID;
}

@property(copy, nonatomic) NSString *BSSID; // @synthesize BSSID=_BSSID;
@property(copy, nonatomic) NSString *SSID; // @synthesize SSID=_SSID;
- (void)dealloc;

@end

