//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MVAudioSessionHelper : NSObject
{
}

+ (id)instance;
- (void)audioRouteChange:(id)arg1;
- (void)resumeAudioSessionForPlay;
- (void)setupAudioSessionForRecord;
- (void)stopObserveAudioSessionForRecord;
- (void)startObserveAudioSessionForRecord;
- (_Bool)isHeadsetPluggedIn;

@end

