//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class MVAVItem;

@interface MVAVAssetSegment : NSObject <NSCopying>
{
    MVAVItem *_avItem;
    CDStruct_e83c9415 _sourceTimeRange;
    CDStruct_e83c9415 _targetTimeRange;
}

+ (id)segmentWithAVItem:(id)arg1 sourceTimeRange:(CDStruct_e83c9415)arg2 targetTimeRange:(CDStruct_e83c9415)arg3;
+ (id)segmentWithAVItem:(id)arg1 sourceTimeRange:(CDStruct_e83c9415)arg2;
+ (id)emptySegmentWithTargetTimeRange:(CDStruct_e83c9415)arg1;
@property(nonatomic) CDStruct_e83c9415 targetTimeRange; // @synthesize targetTimeRange=_targetTimeRange;
@property(nonatomic) CDStruct_e83c9415 sourceTimeRange; // @synthesize sourceTimeRange=_sourceTimeRange;
@property(retain, nonatomic) MVAVItem *avItem; // @synthesize avItem=_avItem;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

