//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSTimer;

@interface MVCameraFocusView : UIImageView
{
    NSTimer *_hideTimer;
}

+ (id)instantiate;
@property(retain, nonatomic) NSTimer *hideTimer; // @synthesize hideTimer=_hideTimer;
- (void).cxx_destruct;
- (void)hide;
- (void)showAtCenter:(struct CGPoint)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

