//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureAudioDataOutputSampleBufferDelegate.h"
#import "AVCaptureMetadataOutputObjectsDelegate.h"
#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureDevice, AVCaptureDeviceInput, AVCaptureMetadataOutput, AVCaptureSession, AVCaptureVideoDataOutput, NSArray, NSObject<OS_dispatch_queue>, NSString, NSTimer;

@interface MVCameraVideoDevice : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate, AVCaptureAudioDataOutputSampleBufferDelegate, AVCaptureMetadataOutputObjectsDelegate>
{
    NSObject<OS_dispatch_queue> *deviceOperationQueue;
    NSObject<OS_dispatch_queue> *videoProcessingQueue;
    NSArray *observers;
    NSTimer *videoCheckTimer;
    _Bool runningListening;
    _Bool focusListening;
    int _cameraProcessingCount;
    long long _sampleBufferSkipCount;
    _Bool _autoStartSession;
    _Bool _autoStopSession;
    _Bool _isRunning;
    _Bool _MVCameraDeviceEventpause;
    _Bool _lowLightBoost;
    _Bool _pause;
    _Bool _running;
    _Bool _VideoStreamFlagRunning;
    _Bool _VideoStreamFlagCheck;
    _Bool _VideoStreamFlagReceiveVideoFrameNotify;
    _Bool _cameraConfiguring;
    float _brightness;
    id <MVCameraVideoDeviceDelegate> _delegate;
    AVCaptureDevice *_device;
    AVCaptureSession *_session;
    long long _torchMode;
    double _zoomFactor;
    long long _exposureDuration;
    long long _fps;
    NSString *_captureSessionPreset;
    AVCaptureDeviceInput *_videoInput;
    AVCaptureVideoDataOutput *_videoOutput;
    AVCaptureMetadataOutput *_metadataOutput;
    long long _VideoStreamFlagRestartCount;
    struct CGPoint _focusPoint;
    struct CGPoint _exposurePoint;
    struct CGSize _videoSize;
    struct UIEdgeInsets _exposureInset;
}

+ (struct UIEdgeInsets)exposureInsetFromVideoScaleFactor:(struct CGRect)arg1;
@property(nonatomic) float brightness; // @synthesize brightness=_brightness;
@property int cameraProcessingCount; // @synthesize cameraProcessingCount=_cameraProcessingCount;
@property _Bool cameraConfiguring; // @synthesize cameraConfiguring=_cameraConfiguring;
@property long long VideoStreamFlagRestartCount; // @synthesize VideoStreamFlagRestartCount=_VideoStreamFlagRestartCount;
@property _Bool VideoStreamFlagReceiveVideoFrameNotify; // @synthesize VideoStreamFlagReceiveVideoFrameNotify=_VideoStreamFlagReceiveVideoFrameNotify;
@property _Bool VideoStreamFlagCheck; // @synthesize VideoStreamFlagCheck=_VideoStreamFlagCheck;
@property _Bool VideoStreamFlagRunning; // @synthesize VideoStreamFlagRunning=_VideoStreamFlagRunning;
@property(nonatomic) _Bool running; // @synthesize running=_running;
@property(nonatomic) _Bool pause; // @synthesize pause=_pause;
@property(retain, nonatomic) AVCaptureMetadataOutput *metadataOutput; // @synthesize metadataOutput=_metadataOutput;
@property(retain, nonatomic) AVCaptureVideoDataOutput *videoOutput; // @synthesize videoOutput=_videoOutput;
@property(retain, nonatomic) AVCaptureDeviceInput *videoInput; // @synthesize videoInput=_videoInput;
@property(nonatomic) struct UIEdgeInsets exposureInset; // @synthesize exposureInset=_exposureInset;
@property(copy, nonatomic) NSString *captureSessionPreset; // @synthesize captureSessionPreset=_captureSessionPreset;
@property(readonly, nonatomic) struct CGSize videoSize; // @synthesize videoSize=_videoSize;
@property(readonly, nonatomic) long long fps; // @synthesize fps=_fps;
@property(nonatomic) _Bool lowLightBoost; // @synthesize lowLightBoost=_lowLightBoost;
@property(nonatomic) long long exposureDuration; // @synthesize exposureDuration=_exposureDuration;
@property(nonatomic) double zoomFactor; // @synthesize zoomFactor=_zoomFactor;
@property(nonatomic) struct CGPoint exposurePoint; // @synthesize exposurePoint=_exposurePoint;
@property(nonatomic) struct CGPoint focusPoint; // @synthesize focusPoint=_focusPoint;
@property(nonatomic) _Bool MVCameraDeviceEventpause; // @synthesize MVCameraDeviceEventpause=_MVCameraDeviceEventpause;
@property(nonatomic) _Bool isRunning; // @synthesize isRunning=_isRunning;
@property(nonatomic) long long torchMode; // @synthesize torchMode=_torchMode;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AVCaptureDevice *device; // @synthesize device=_device;
@property(nonatomic) __weak id <MVCameraVideoDeviceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)originVideoSizeFromCamera;
- (void)captureOutput:(id)arg1 didDropSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeFocusChangeListener;
- (void)addFocusChangeListener;
- (void)removeRunningChangeListener;
- (void)addRunningChangeListener;
- (void)videoCheckTimerHandler;
- (void)stopVideoCheckTimer;
- (void)setupVideoCheckTimer;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)startFaceDetection:(id)arg1;
- (void)stopFaceDetection;
- (id)getFromateVideoMinFrameDuration:(CDStruct_1b6d18a9)arg1 maxFrameDuration:(CDStruct_1b6d18a9)arg2 inDevice:(id)arg3;
- (_Bool)setVideoMinFrameDuration:(CDStruct_1b6d18a9)arg1 maxFrameDuration:(CDStruct_1b6d18a9)arg2;
- (void)updateDeviceStatus;
- (void)changeDevicePosition;
- (id)deviceWithType:(id)arg1 position:(long long)arg2;
- (id)devicesOfPhoto;
- (void)restartDevcie;
- (void)commitConfiguration;
- (void)beginConfiguration;
- (void)stopDevice;
- (void)startDevice;
- (struct CGPoint)untranslateFromDevicePoint:(struct CGPoint)arg1;
- (struct CGPoint)translateToDevicePoint:(struct CGPoint)arg1;
- (_Bool)doesVideoHaveFrames;
@property(readonly, nonatomic) _Bool hasBack;
@property(readonly, nonatomic) _Bool hasFront;
@property(readonly, nonatomic) _Bool hasTorch;
- (void)closeTroch;
- (long long)canDeviceSetFlashMode:(long long)arg1;
- (_Bool)supportFlashModeOn;
- (_Bool)supportFrontCameraFlashModeOn;
- (void)setFPS:(long long)arg1 videoSize:(struct CGSize)arg2;
- (void)setPosition:(long long)arg1 complete:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) long long position;
- (id)getDeviceOperationQueue;
- (void)dealloc;
- (id)initWithPosition:(long long)arg1 queue:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

