//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MVBaseViewController.h"

#import "MVCameraBottomBarDelegate.h"
#import "MVCameraControllerGestureDelegate.h"
#import "MVCameraTopBarDelegate.h"
#import "MVRecordEngineDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class GPUImageView, MPVolumeView, MVCameraBottomBar, MVCameraFocusControl, MVCameraTopBar, MVFilterPicker, MVGradientView, MVMaterialItem, MVMediaMakerController, MVMediaMakerOptions, MVModel, MVMusicItem, MVRecordEngine, MVRecordProgressView, NSArray, NSString, NSTimer, QZEVContext, UIPanGestureRecognizer, UIPinchGestureRecognizer, UISlider, UITableView, UITapGestureRecognizer, UIView;

@interface MVCameraViewController : MVBaseViewController <MVCameraControllerGestureDelegate, UIGestureRecognizerDelegate, MVRecordEngineDelegate, UIViewControllerTransitioningDelegate, MVCameraTopBarDelegate, MVCameraBottomBarDelegate, UINavigationControllerDelegate>
{
    _Bool _volumePhotoEnable;
    _Bool _firstAppeared;
    _Bool _viewAppeared;
    _Bool _isShowingTipFilter;
    _Bool _needShowDraftPrompt;
    _Bool _needResetDraftEditMode;
    _Bool _hasTouchedSpeedButton;
    _Bool _isMusicDownloaded;
    _Bool _isMotionDownloaded;
    _Bool _autoFinishRecord;
    _Bool _needShowMotionTips;
    _Bool _needShowARGameTips;
    _Bool _downloadMaterialCanceled;
    _Bool _downloadMaterialError;
    _Bool _enableCountDown;
    _Bool _isCountingDown;
    _Bool _selectTmplViewDidApperred;
    _Bool _isInEnteringGawuViewController;
    _Bool _videoCameraStopped;
    _Bool _audioCameraStopped;
    _Bool _isGawuResourceDownloaded;
    _Bool _isContextLoaded;
    float _globleProgress;
    float _motionProgress;
    float _musicProgress;
    float _factor;
    float _perFactor;
    QZEVContext *_context;
    long long _mediaType;
    MVMediaMakerOptions *_options;
    MVModel *_draft;
    MVRecordEngine *_recordEngine;
    GPUImageView *_previewView;
    MVCameraTopBar *_cameraTopBar;
    MVCameraBottomBar *_cameraBottomBar;
    MVCameraFocusControl *_focusControl;
    MVFilterPicker *_filterPicker;
    NSString *_schemaSelectTmplCategory;
    NSString *_schemaSelectTmplName;
    MVGradientView *_topGradientView;
    MVGradientView *_bottomGradientView;
    MVMaterialItem *_materialItem;
    MVMusicItem *_musicItem;
    MVRecordProgressView *_recordProgressView;
    UIView *_topicUpperView;
    NSArray *_gestureDelegates;
    id <MVCameraControllerGestureDelegate> _defaultGestureDelegate;
    UIView *_gestureView;
    UITapGestureRecognizer *_singleTapGesture;
    UITapGestureRecognizer *_doubleTapGesture;
    UIPinchGestureRecognizer *_pinchGesture;
    UIPanGestureRecognizer *_singlePanGesture;
    UIPanGestureRecognizer *_doublePanGesture;
    double _zoomLocationY;
    double _zoomOrignY;
    double _zoomStartValue;
    NSTimer *_timerMusicObserver;
    UITableView *_debugView;
    MPVolumeView *_volumeView;
    double _lastVolume;
    UISlider *_volumeSlider;
    double _lastVolumeChangeTime;
    CDStruct_e83c9415 _selectedRange;
}

+ (void)initialize;
@property(nonatomic) _Bool isContextLoaded; // @synthesize isContextLoaded=_isContextLoaded;
@property(nonatomic) _Bool isGawuResourceDownloaded; // @synthesize isGawuResourceDownloaded=_isGawuResourceDownloaded;
@property(nonatomic) _Bool audioCameraStopped; // @synthesize audioCameraStopped=_audioCameraStopped;
@property(nonatomic) _Bool videoCameraStopped; // @synthesize videoCameraStopped=_videoCameraStopped;
@property(nonatomic) _Bool isInEnteringGawuViewController; // @synthesize isInEnteringGawuViewController=_isInEnteringGawuViewController;
@property(nonatomic) _Bool selectTmplViewDidApperred; // @synthesize selectTmplViewDidApperred=_selectTmplViewDidApperred;
@property(nonatomic) double lastVolumeChangeTime; // @synthesize lastVolumeChangeTime=_lastVolumeChangeTime;
@property(nonatomic) __weak UISlider *volumeSlider; // @synthesize volumeSlider=_volumeSlider;
@property(nonatomic) double lastVolume; // @synthesize lastVolume=_lastVolume;
@property(retain, nonatomic) MPVolumeView *volumeView; // @synthesize volumeView=_volumeView;
@property(nonatomic) _Bool isCountingDown; // @synthesize isCountingDown=_isCountingDown;
@property(nonatomic) _Bool enableCountDown; // @synthesize enableCountDown=_enableCountDown;
@property(retain, nonatomic) UITableView *debugView; // @synthesize debugView=_debugView;
@property(nonatomic) _Bool downloadMaterialError; // @synthesize downloadMaterialError=_downloadMaterialError;
@property(nonatomic) _Bool downloadMaterialCanceled; // @synthesize downloadMaterialCanceled=_downloadMaterialCanceled;
@property(nonatomic) float perFactor; // @synthesize perFactor=_perFactor;
@property(nonatomic) float factor; // @synthesize factor=_factor;
@property(nonatomic) float musicProgress; // @synthesize musicProgress=_musicProgress;
@property(nonatomic) float motionProgress; // @synthesize motionProgress=_motionProgress;
@property(nonatomic) float globleProgress; // @synthesize globleProgress=_globleProgress;
@property(retain, nonatomic) NSTimer *timerMusicObserver; // @synthesize timerMusicObserver=_timerMusicObserver;
@property(nonatomic) double zoomStartValue; // @synthesize zoomStartValue=_zoomStartValue;
@property(nonatomic) double zoomOrignY; // @synthesize zoomOrignY=_zoomOrignY;
@property(nonatomic) double zoomLocationY; // @synthesize zoomLocationY=_zoomLocationY;
@property(retain, nonatomic) UIPanGestureRecognizer *doublePanGesture; // @synthesize doublePanGesture=_doublePanGesture;
@property(retain, nonatomic) UIPanGestureRecognizer *singlePanGesture; // @synthesize singlePanGesture=_singlePanGesture;
@property(retain, nonatomic) UIPinchGestureRecognizer *pinchGesture; // @synthesize pinchGesture=_pinchGesture;
@property(retain, nonatomic) UITapGestureRecognizer *doubleTapGesture; // @synthesize doubleTapGesture=_doubleTapGesture;
@property(retain, nonatomic) UITapGestureRecognizer *singleTapGesture; // @synthesize singleTapGesture=_singleTapGesture;
@property(retain, nonatomic) UIView *gestureView; // @synthesize gestureView=_gestureView;
@property(nonatomic) __weak id <MVCameraControllerGestureDelegate> defaultGestureDelegate; // @synthesize defaultGestureDelegate=_defaultGestureDelegate;
@property(retain, nonatomic) NSArray *gestureDelegates; // @synthesize gestureDelegates=_gestureDelegates;
@property(nonatomic) _Bool needShowARGameTips; // @synthesize needShowARGameTips=_needShowARGameTips;
@property(nonatomic) _Bool needShowMotionTips; // @synthesize needShowMotionTips=_needShowMotionTips;
@property(nonatomic) _Bool autoFinishRecord; // @synthesize autoFinishRecord=_autoFinishRecord;
@property(nonatomic) _Bool isMotionDownloaded; // @synthesize isMotionDownloaded=_isMotionDownloaded;
@property(nonatomic) _Bool isMusicDownloaded; // @synthesize isMusicDownloaded=_isMusicDownloaded;
@property(retain, nonatomic) UIView *topicUpperView; // @synthesize topicUpperView=_topicUpperView;
@property(retain, nonatomic) MVRecordProgressView *recordProgressView; // @synthesize recordProgressView=_recordProgressView;
@property(retain, nonatomic) MVMusicItem *musicItem; // @synthesize musicItem=_musicItem;
@property(nonatomic) _Bool hasTouchedSpeedButton; // @synthesize hasTouchedSpeedButton=_hasTouchedSpeedButton;
@property(nonatomic) _Bool needResetDraftEditMode; // @synthesize needResetDraftEditMode=_needResetDraftEditMode;
@property(nonatomic) _Bool needShowDraftPrompt; // @synthesize needShowDraftPrompt=_needShowDraftPrompt;
@property(retain, nonatomic) MVMaterialItem *materialItem; // @synthesize materialItem=_materialItem;
@property(retain, nonatomic) MVGradientView *bottomGradientView; // @synthesize bottomGradientView=_bottomGradientView;
@property(retain, nonatomic) MVGradientView *topGradientView; // @synthesize topGradientView=_topGradientView;
@property(nonatomic) CDStruct_e83c9415 selectedRange; // @synthesize selectedRange=_selectedRange;
@property(nonatomic) _Bool isShowingTipFilter; // @synthesize isShowingTipFilter=_isShowingTipFilter;
@property(retain, nonatomic) NSString *schemaSelectTmplName; // @synthesize schemaSelectTmplName=_schemaSelectTmplName;
@property(retain, nonatomic) NSString *schemaSelectTmplCategory; // @synthesize schemaSelectTmplCategory=_schemaSelectTmplCategory;
@property(retain, nonatomic) MVFilterPicker *filterPicker; // @synthesize filterPicker=_filterPicker;
@property(retain, nonatomic) MVCameraFocusControl *focusControl; // @synthesize focusControl=_focusControl;
@property(retain, nonatomic) MVCameraBottomBar *cameraBottomBar; // @synthesize cameraBottomBar=_cameraBottomBar;
@property(retain, nonatomic) MVCameraTopBar *cameraTopBar; // @synthesize cameraTopBar=_cameraTopBar;
@property(retain, nonatomic) GPUImageView *previewView; // @synthesize previewView=_previewView;
@property(retain, nonatomic) MVRecordEngine *recordEngine; // @synthesize recordEngine=_recordEngine;
@property(nonatomic) _Bool viewAppeared; // @synthesize viewAppeared=_viewAppeared;
@property(nonatomic) _Bool firstAppeared; // @synthesize firstAppeared=_firstAppeared;
@property(nonatomic) _Bool volumePhotoEnable; // @synthesize volumePhotoEnable=_volumePhotoEnable;
@property(retain, nonatomic) MVModel *draft; // @synthesize draft=_draft;
@property(readonly, nonatomic) MVMediaMakerOptions *options; // @synthesize options=_options;
@property(readonly, nonatomic) long long mediaType; // @synthesize mediaType=_mediaType;
@property(retain, nonatomic) QZEVContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (_Bool)checkFreeDiskSpaceEnough;
@property(readonly, nonatomic) MVMediaMakerController *currentMediaMakerController;
- (void)refreshModelCover;
- (void)editMedia:(id)arg1;
- (void)finishWithMVRecordEngine:(id)arg1;
- (void)initPreview;
- (void)initCameraBottomBar;
- (void)initCameraTopBar;
- (void)updateTorchMode;
- (void)shutdownTorch;
- (void)recordEngine:(id)arg1 updateGestureForItemType:(unsigned long long)arg2;
- (void)recordEngine:(id)arg1 didRenderSizeUpdate:(struct CGSize)arg2;
- (void)recordEngine:(id)arg1 needUpdateFaceSwapTipsForTmpl:(id)arg2 faceCount:(long long)arg3;
- (void)recordEngine:(id)arg1 needHideTipsWithType:(id)arg2;
- (void)recordEngine:(id)arg1 needShowTips:(id)arg2 type:(id)arg3 duration:(double)arg4;
- (void)recordEngine:(id)arg1 didChangeCaptureMode:(unsigned long long)arg2;
- (void)recordEngine:(id)arg1 didFailAtSection:(unsigned long long)arg2 error:(id)arg3;
- (void)recordEngine:(id)arg1 finishAtSection:(unsigned long long)arg2 success:(_Bool)arg3 error:(id)arg4;
- (void)recordEngine:(id)arg1 motionItemDidChange:(id)arg2;
- (void)recordEngine:(id)arg1 didDeleteVideoItem:(id)arg2;
- (void)recordEngine:(id)arg1 didRecordOverTime:(double)arg2;
- (void)recordEngine:(id)arg1 filterIndexDidChange:(long long)arg2;
- (void)recordEngine:(id)arg1 updateRecordingTime:(double)arg2;
- (void)gotoVideoPickerController;
- (void)checkVideoItems;
- (void)bottomBar:(id)arg1 handleZoomGesture:(id)arg2;
- (void)removeRemoveLasetVideoItem;
- (_Bool)canBeginRecord;
- (void)bottomBar:(id)arg1 didSelectMusicItem:(id)arg2;
- (void)bottomBar:(id)arg1 onFilterPannelShowed:(_Bool)arg2;
- (void)bottomBar:(id)arg1 onMotionPannelShowed:(_Bool)arg2;
- (void)bottomBar:(id)arg1 onSelectSpeedRate:(double)arg2;
- (void)bottomBar:(id)arg1 didSelectFilter:(id)arg2;
- (_Bool)bottomBar:(id)arg1 shouldSelectFilter:(id)arg2;
- (void)bottomBar:(id)arg1 didSelectMotionItem:(id)arg2;
- (void)battomBar:(id)arg1 didSelectMotionItem:(id)arg2;
- (void)bottomBar:(id)arg1 onTapMusicBtn:(id)arg2;
- (void)bottomBar:(id)arg1 onTapAlbumBtn:(id)arg2;
- (void)bottomBar:(id)arg1 onTapDoneBtn:(id)arg2;
- (void)bottomBar:(id)arg1 recordDidChangeFromState:(unsigned long long)arg2 toState:(unsigned long long)arg3;
- (void)bottomBar:(id)arg1 willChangeRecordStateTo:(unsigned long long)arg2;
- (_Bool)bottomBar:(id)arg1 shouldChangeRecordStateTo:(unsigned long long)arg2;
- (void)updateButtomBarTime;
- (struct CGRect)videoRenderRectWithSize:(struct CGSize)arg1;
- (void)switchCamera;
- (_Bool)startCountDown;
- (void)nextAnimation:(id)arg1 num:(long long)arg2;
- (void)topBar:(id)arg1 onTapCountDownBtn:(id)arg2;
- (void)topBar:(id)arg1 onTapTorchBtn:(id)arg2;
- (void)topBar:(id)arg1 onTapSwitchCameraBtn:(id)arg2;
- (void)topBar:(id)arg1 onTapBackBtn:(id)arg2;
- (void)resetDelegingPreviewState;
- (void)onTouchViewIgnorePanel:(_Bool)arg1 ignoreDeletingState:(_Bool)arg2;
- (void)onTouchView;
- (void)initFocusControl;
- (void)initFilterPicker;
- (void)initRecordProgressView;
- (void)initGradientViews;
- (void)loadContext;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeCameraConfigObserver;
- (void)addCameraConfigObserver;
- (void)appBecomeActive:(id)arg1;
- (void)appResignActive:(id)arg1;
- (void)unregisterAppNotification;
- (void)registerAppNotification;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithContext:(id)arg1;
- (void)p_showForbiddenAlert:(id)arg1 message:(id)arg2;
- (void)p_showPhotoLibraryAuthorizationForbiddenAlert;
- (_Bool)p_hasPhotoLibraryAuthorization;
- (void)handleZoomByTouch:(id)arg1;
- (void)handleLongPressZoomGesture:(id)arg1;
- (void)handleZoom:(id)arg1;
- (_Bool)handleDoublePanGesture:(id)arg1;
- (_Bool)handleSinglePanGesture:(id)arg1;
- (_Bool)handlePinchGesture:(id)arg1;
- (_Bool)handleDoubleTapGesture:(id)arg1;
- (_Bool)handleSingleTapGesture:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)mc_handleDoublePan:(id)arg1;
- (void)mc_handleSinglePan:(id)arg1;
- (void)mc_handlePinch:(id)arg1;
- (void)mc_handleDoubleTap:(id)arg1;
- (void)mc_handleSingleTap:(id)arg1;
- (void)removeDoublePanGesture;
- (void)addDoublePanGesture;
- (void)removeSinglePanGesture;
- (void)addSinglePanGesture;
- (void)setupGesturesForItemType:(unsigned long long)arg1;
- (void)setupBasicGestures;
- (_Bool)checkFreeDiskSpaceEnough;
- (void)exitRecord;
- (void)updateWhenDraftLoadSuccess;
- (void)recordFromDraft:(id)arg1;
- (void)refreshRecordModelForEditing;
- (void)generateNewRecordModel;
- (void)promptUnfinishedWork;
- (void)setupRecordModel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

