//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MVEffectDirector.h"

#import "MVPlayer.h"

@class GPUImageView, MVModel, MVVideoSettings, NSMutableDictionary, NSString;

@interface MVEffectPlayer : MVEffectDirector <MVPlayer>
{
    _Bool _loops;
    _Bool _optimizesForPlaying;
    _Bool _playsAfterReady;
    _Bool _seeksAfterReady;
    _Bool _needsReloadAVChannels;
    GPUImageView *_renderView;
    double _pendingSeekTime;
    MVVideoSettings *_videoSettings;
    NSMutableDictionary *_observerMap;
}

+ (id)playerWithModel:(id)arg1 renderView:(id)arg2;
@property(retain, nonatomic) NSMutableDictionary *observerMap; // @synthesize observerMap=_observerMap;
@property(retain, nonatomic) MVVideoSettings *videoSettings; // @synthesize videoSettings=_videoSettings;
@property(nonatomic) double pendingSeekTime; // @synthesize pendingSeekTime=_pendingSeekTime;
@property(nonatomic) _Bool needsReloadAVChannels; // @synthesize needsReloadAVChannels=_needsReloadAVChannels;
@property(nonatomic) _Bool seeksAfterReady; // @synthesize seeksAfterReady=_seeksAfterReady;
@property(nonatomic) _Bool playsAfterReady; // @synthesize playsAfterReady=_playsAfterReady;
@property(nonatomic) _Bool optimizesForPlaying; // @synthesize optimizesForPlaying=_optimizesForPlaying;
@property(nonatomic) _Bool loops; // @synthesize loops=_loops;
@property(retain, nonatomic) GPUImageView *renderView; // @synthesize renderView=_renderView;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)changePlayVideoMode;
- (_Bool)needsReloadActionsForVideoChannel;
- (void)reloadAVChannels;
- (void)reloadChannels;
- (void)removePlaybackTimeObserver:(id)arg1;
- (void)addPlaybackTimeObserver:(id)arg1;
- (void)didReachEndTime;
- (void)channelsDidChangeReadyState;
- (void)startPreview;
- (void)play;
- (void)seekToTime:(double)arg1;
- (void)stop;
- (void)pause;
- (void)start;
- (void)setNeedsReloadAVChannels;
@property(readonly, nonatomic) long long playbackStatus;
@property(readonly, nonatomic) struct CGSize renderSize;
@property(retain, nonatomic) MVModel *model;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, nonatomic) double currentTime;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) double duration;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isPlaying;
@property(nonatomic) long long mediaContentMode;
@property(readonly, nonatomic) float rate;
@property(readonly) Class superclass;

@end

