//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUImageFourInputFilter.h"

@interface MVGhostTrailBlendFilter : GPUImageFourInputFilter
{
    int alpha_uni;
    int alpha2_uni;
    int alpha3_uni;
    int alpha4_uni;
}

- (void)setAlpha4:(double)arg1;
- (void)setAlpha3:(double)arg1;
- (void)setAlpha2:(double)arg1;
- (void)setAlpha:(double)arg1;
- (id)init;

@end

