//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MVGPUImageMaskFilter.h"

@class NSArray, UIImage;

@interface MVGPUImageMaskImageListFilter : MVGPUImageMaskFilter
{
    double _interval;
    NSArray *_imagePaths;
    UIImage *_currentImage;
    long long _currentImageIndex;
}

+ (id)filter;
@property(nonatomic) long long currentImageIndex; // @synthesize currentImageIndex=_currentImageIndex;
@property(retain, nonatomic) UIImage *currentImage; // @synthesize currentImage=_currentImage;
@property(retain, nonatomic) NSArray *imagePaths; // @synthesize imagePaths=_imagePaths;
@property(nonatomic) double interval; // @synthesize interval=_interval;
- (void).cxx_destruct;
- (void)updateWithTime:(double)arg1;

@end

