//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class MVModel, MVModelImageGenerator, MVMultipleRangeBar, NSArray, NSMutableDictionary, NSString, UICollectionView, UIColor, UIImage, UIImageView, UIPanGestureRecognizer;

@interface MVMediaTimelineBar : UIView <UIGestureRecognizerDelegate>
{
    _Bool _usingOverallAsset;
    _Bool _isDraggingTimeCursor;
    MVModel *_media;
    NSArray *_maskRanges;
    double _progress;
    double _currentTime;
    long long _imageCount;
    UIImageView *_timeCursor;
    UIView *_contentView;
    UICollectionView *_imageListView;
    UIColor *_timeCursorColor;
    MVMultipleRangeBar *_rangeMaskView;
    UIPanGestureRecognizer *_timePanGesture;
    CDUnknownBlockType _didMoveTimeCursor;
    CDUnknownBlockType _fetchDraggableAreaOfTimeCursor;
    UIView *_imageListBgView;
    NSMutableDictionary *_images;
    MVModelImageGenerator *_imageGenerator;
    UIImage *_timeCursorImage;
    struct UIEdgeInsets _padding;
    struct CGRect _draggableAreaOfTimeCursor;
}

+ (double)imageAspectRatio;
@property(retain, nonatomic) UIImage *timeCursorImage; // @synthesize timeCursorImage=_timeCursorImage;
@property(retain, nonatomic) MVModelImageGenerator *imageGenerator; // @synthesize imageGenerator=_imageGenerator;
@property(retain, nonatomic) NSMutableDictionary *images; // @synthesize images=_images;
@property(retain, nonatomic) UIView *imageListBgView; // @synthesize imageListBgView=_imageListBgView;
@property(copy, nonatomic) CDUnknownBlockType fetchDraggableAreaOfTimeCursor; // @synthesize fetchDraggableAreaOfTimeCursor=_fetchDraggableAreaOfTimeCursor;
@property(copy, nonatomic) CDUnknownBlockType didMoveTimeCursor; // @synthesize didMoveTimeCursor=_didMoveTimeCursor;
@property(retain, nonatomic) UIPanGestureRecognizer *timePanGesture; // @synthesize timePanGesture=_timePanGesture;
@property(nonatomic) __weak MVMultipleRangeBar *rangeMaskView; // @synthesize rangeMaskView=_rangeMaskView;
@property(retain, nonatomic) UIColor *timeCursorColor; // @synthesize timeCursorColor=_timeCursorColor;
@property(nonatomic) __weak UICollectionView *imageListView; // @synthesize imageListView=_imageListView;
@property(readonly, nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak UIImageView *timeCursor; // @synthesize timeCursor=_timeCursor;
@property(readonly, nonatomic) struct CGRect draggableAreaOfTimeCursor; // @synthesize draggableAreaOfTimeCursor=_draggableAreaOfTimeCursor;
@property(nonatomic) _Bool isDraggingTimeCursor; // @synthesize isDraggingTimeCursor=_isDraggingTimeCursor;
@property(nonatomic) long long imageCount; // @synthesize imageCount=_imageCount;
@property(nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
@property(nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) NSArray *maskRanges; // @synthesize maskRanges=_maskRanges;
@property(nonatomic) _Bool usingOverallAsset; // @synthesize usingOverallAsset=_usingOverallAsset;
@property(retain, nonatomic) MVModel *media; // @synthesize media=_media;
- (void).cxx_destruct;
- (struct CGRect)draggableAreaOfTimeCursorWithBoundingRect:(struct CGRect)arg1;
- (void)setTimeCursorWithImage:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)handleTapGesture:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (void)setImage:(id)arg1 atIndex:(long long)arg2;
- (id)imageAtIndex:(long long)arg1;
- (void)reloadImagesWithCount:(long long)arg1;
- (void)reloadImages;
- (void)updateDraggableAreaOfTimeCursor;
- (void)updateImageForTimeCursor;
- (void)initTimeCursorGestures;
- (void)initTimeCursor;
- (void)initRangeMaskView;
- (void)initImageListView;
- (void)initContentView;
- (void)initTimelineBarUI;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

