//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class MVMotionMaterial;

@interface MVMotionItem : NSObject <NSCoding, NSCopying>
{
    MVMotionMaterial *_material;
}

@property(retain, nonatomic) MVMotionMaterial *material; // @synthesize material=_material;
- (void).cxx_destruct;

@end

