//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MVVideoSourceAction.h"

@class MVMediaRealtimeTimelineReference;

@interface MVVideoPlayAction : MVVideoSourceAction
{
    _Bool _playsAfterSeeking;
    _Bool _updatesAfterFlushOutput;
    float _volume;
    CDUnknownBlockType _didReadToEndTime;
    CDUnknownBlockType _didFlushOutput;
    MVMediaRealtimeTimelineReference *_timelineReference;
}

@property(nonatomic) _Bool updatesAfterFlushOutput; // @synthesize updatesAfterFlushOutput=_updatesAfterFlushOutput;
@property(nonatomic) _Bool playsAfterSeeking; // @synthesize playsAfterSeeking=_playsAfterSeeking;
@property(retain, nonatomic) MVMediaRealtimeTimelineReference *timelineReference; // @synthesize timelineReference=_timelineReference;
@property(copy, nonatomic) CDUnknownBlockType didFlushOutput; // @synthesize didFlushOutput=_didFlushOutput;
@property(copy, nonatomic) CDUnknownBlockType didReadToEndTime; // @synthesize didReadToEndTime=_didReadToEndTime;
@property(nonatomic) float volume; // @synthesize volume=_volume;
- (void).cxx_destruct;
- (void)processControlData:(id)arg1;
- (void)setRate:(float)arg1;
- (void)setMediaState:(long long)arg1;
- (void)seekToTime:(struct _QZEVMediaTime)arg1;
- (void)updateWithTime:(struct _QZEVMediaTime)arg1;
- (void)setVideoComposition:(id)arg1 audioMix:(id)arg2 takesOverVideoComposition:(_Bool)arg3;
- (id)makeReader;

@end

