//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTObject.h"

@interface MVVideoWordingAnimationFrameRange : TTObject
{
    long long _start;
    long long _end;
}

@property(nonatomic) long long end; // @synthesize end=_end;
@property(nonatomic) long long start; // @synthesize start=_start;
- (id)initWithDataSource:(id)arg1;

@end

