//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MVVideoEffectAction, MVVideoEffectActionGroup, NSArray, NSString, UIImage;

@protocol MVVideoEffectGroupDelegate <NSObject>

@optional
- (double)videoIntervalForVideoEffectGroup:(MVVideoEffectActionGroup *)arg1;
- (double)durationForVideoEffectGroup:(MVVideoEffectActionGroup *)arg1 action:(MVVideoEffectAction *)arg2;
- (struct CGSize)videoSizeForVideoEffectGroup:(MVVideoEffectActionGroup *)arg1 action:(MVVideoEffectAction *)arg2;
- (UIImage *)userIconForVideoEffectGroup:(MVVideoEffectActionGroup *)arg1 action:(MVVideoEffectAction *)arg2;
- (NSString *)userNameForVideoEffectGroup:(MVVideoEffectActionGroup *)arg1 action:(MVVideoEffectAction *)arg2;
- (NSString *)wordingTitlePinyinForVideoEffectGroup:(MVVideoEffectActionGroup *)arg1 action:(MVVideoEffectAction *)arg2;
- (NSString *)wordingTitleForVideoEffectGroup:(MVVideoEffectActionGroup *)arg1 action:(MVVideoEffectAction *)arg2;
- (NSArray *)videoEffectGroup:(MVVideoEffectActionGroup *)arg1 action:(MVVideoEffectAction *)arg2 imagesForTimestamps:(NSArray *)arg3;
@end

