//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NLLoginData, NSString;

@interface NLAccountMgr : NSObject
{
    _Bool _bLogin;
    _Bool _bSetAccount;
    NLLoginData *_loginData;
    NSString *_tinyId;
    NSString *_tinyA2;
    NSString *_selfUid;
}

+ (id)shareInstance;
@property(nonatomic) _Bool bSetAccount; // @synthesize bSetAccount=_bSetAccount;
@property(nonatomic) _Bool bLogin; // @synthesize bLogin=_bLogin;
@property(retain, nonatomic) NSString *selfUid; // @synthesize selfUid=_selfUid;
@property(retain, nonatomic) NSString *tinyA2; // @synthesize tinyA2=_tinyA2;
@property(retain, nonatomic) NSString *tinyId; // @synthesize tinyId=_tinyId;
@property(retain, nonatomic) NLLoginData *loginData; // @synthesize loginData=_loginData;
- (void).cxx_destruct;
- (void)onAccountInvalid;
- (id)getDomain;
- (void)clearAccountCookies;
- (void)setAccountCookies;
- (id)extParamStrForLoginType:(unsigned long long)arg1;
- (void)getTinyIdWith:(id)arg1;
- (void)updateLoginData:(id)arg1;
- (void)logout;
- (id)init;

@end

