//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLSingletonBase.h"

#import "NLLogProtocol.h"

@class NSFileHandle, NSString;

@interface NLLogDefaultImpl : NLSingletonBase <NLLogProtocol>
{
    NSFileHandle *_todayFileHandler;
    NSString *_logDirPath;
    NSString *_lastFileName;
}

@property(copy, nonatomic) NSString *lastFileName; // @synthesize lastFileName=_lastFileName;
@property(copy, nonatomic) NSString *logDirPath; // @synthesize logDirPath=_logDirPath;
- (void).cxx_destruct;
- (id)todayFileHandler;
- (id)getTodayFileName;
- (id)getCurDateStr;
- (void)logToFile:(id)arg1;
- (void)logFinalFilter:(id)arg1 file:(id)arg2 func:(const char *)arg3 line:(int)arg4 format:(id)arg5;
- (void)logDebugFilter:(id)arg1 file:(id)arg2 func:(const char *)arg3 line:(int)arg4 format:(id)arg5;
- (id)mkTodayFile;
- (void)mkLogDir;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

