//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLSingletonBase.h"

@class NSString;

@interface NLPayHelper : NLSingletonBase
{
    NSString *_callback;
    id <NLPayHelperDelegate> _delegate;
}

@property(nonatomic) __weak id <NLPayHelperDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *callback; // @synthesize callback=_callback;
- (void).cxx_destruct;
- (id)jsWithName:(id)arg1 Result:(int)arg2 data:(id)arg3;
- (void)onIAPPayComplete:(id)arg1;
- (void)payWithParam:(id)arg1 parent:(id)arg2 delegate:(id)arg3;
- (void)dealloc;
- (id)init;

@end

