//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAttributedString.h"

@interface NSAttributedString (QNAttributedLabel)
- (struct CGRect)qn_lastLineRectWithSize:(struct CGSize)arg1 config:(id)arg2;
- (struct CGRect)qn_lastLineRectWithSize:(struct CGSize)arg1;
- (struct CGSize)qn_constrainedToSize:(struct CGSize)arg1 truncated:(_Bool *)arg2 numberOfLines:(unsigned long long *)arg3;
- (struct CGSize)qn_constrainedToSize:(struct CGSize)arg1 truncated:(_Bool *)arg2;
- (struct CGSize)qn_constrainedToSize:(struct CGSize)arg1 config:(id)arg2;
- (struct CGSize)qn_constrainedToSize:(struct CGSize)arg1;
@end

