//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAttributedString.h"

@interface NSAttributedString (QNAttributedLabel_CustomProperty)
- (id)qn_links;
- (id)qn_images;
- (id)qn_imageAtIndex:(unsigned long long)arg1;
- (id)qn_endingIconImage;
- (double)qn_endingIconImageLeftMargin;
- (id)qn_truncationString;
- (_Bool)qn_skipLineStartWhitespaceCharacters;
- (unsigned long long)qn_lastLineMinimumCharacters;
- (unsigned long long)qn_tailStayCharNum;
- (unsigned long long)qn_numberOfLines;
- (struct UIEdgeInsets)qn_contentInsets;
@end

