//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableArray.h"

@interface NSMutableArray (QNUtilsSafe)
+ (id)qn_array:(CDUnknownBlockType)arg1;
- (void)qn_shuffle;
- (id)qn_set;
- (void)safeInsertObject:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)safeReplaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (void)safeAddObject:(id)arg1;
- (void)qn_removeObjectsAtIndexes:(id)arg1;
- (void)qn_insertObject:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)qn_replaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (void)qn_addObject:(id)arg1;
- (void)qn_build:(CDUnknownBlockType)arg1;
@end

