//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (MVMediaAction)
- (id)inputFromGraph:(id)arg1;
- (id)outputToGraph:(id)arg1;
- (id)inputFromAction:(id)arg1;
- (id)outputToAction:(id)arg1;
- (id)mergeAction:(id)arg1;
@end

