//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface NWTLV : NSObject
{
    long long typeId;
    NSData *typeValue;
}

+ (id)read:(id)arg1 endian:(_Bool)arg2;
@property(retain) NSData *typeValue; // @synthesize typeValue;
@property long long typeId; // @synthesize typeId;
- (void).cxx_destruct;
- (id)stringValue;
- (_Bool)boolValue;
- (int)byteValue;
- (int)shortValue;
- (int)intValue;
- (unsigned int)unsignedIntValue;
- (long long)int64Value;
- (void)readFrom:(id)arg1 endian:(_Bool)arg2;
- (void)writeTo:(id)arg1 endian:(_Bool)arg2;
- (unsigned long long)length;
- (void)dealloc;

@end

