//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NWUtilByte : NSObject
{
}

+ (_Bool)data:(const void *)arg1 size:(unsigned long long)arg2 endWithData:(const void *)arg3 length:(unsigned long long)arg4;
+ (_Bool)buffer:(id)arg1 endWithData:(const void *)arg2 length:(unsigned long long)arg3;
+ (int)buffer:(id)arg1 indexWithData:(const void *)arg2 length:(unsigned long long)arg3;
+ (int)data:(const void *)arg1 size:(unsigned long long)arg2 indexWithData:(const void *)arg3 length:(unsigned long long)arg4;
+ (_Bool)data:(const void *)arg1 startWithData:(const void *)arg2 length:(unsigned long long)arg3;
+ (_Bool)buffer:(id)arg1 startWithData:(const void *)arg2 length:(unsigned long long)arg3;

@end

