//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NWAVPlayJitterSinkDelegate.h"
#import "NWFrameExtractorDelegate.h"

@class NSCondition, NSLock, NSMutableArray, NSString, NSThread;

@interface NWVideoDecoder : NSObject <NWFrameExtractorDelegate, NWAVPlayJitterSinkDelegate>
{
    struct CGSize _video_size;
    struct CGSize _output_size;
    _Bool _created;
    NSThread *_decode_thread;
    _Bool _should_exit;
    int _acc_status;
    unsigned int _sync_timestamp;
    NSMutableArray *_decode_queue;
    NSLock *_decode_lock;
    NSMutableArray *_render_queue;
    NSLock *_render_lock;
    NSLock *_clear_lock;
    unsigned int _recvpackets;
    unsigned int _recvbytes;
    int _width;
    int _height;
    unsigned long long _lastVideoInfoTime;
    _Bool _bPause;
    unsigned long long _last_decoded_seq;
    _Bool _need_ignores;
    _Bool _isFirstFrame;
    _Bool _should_received;
    NSCondition *_join_lock;
    _Bool _decoding;
    _Bool _need_key_frame;
    int _should_discard_count;
    _Bool _should_discard;
    int _exit_code;
    _Bool _init_VideoDecoder;
    struct NWIAVPlayJitterSink *JitterSink;
    int _kadatatimes;
    int _kadataframe;
    unsigned int _cur_seq;
    unsigned int _last_timestamp;
    _Bool _hasBFrame;
}

@property(nonatomic) _Bool hasBFrame; // @synthesize hasBFrame=_hasBFrame;
@property(readonly, nonatomic) struct CGSize video_size; // @synthesize video_size=_video_size;
@property(readonly) unsigned int sync_frame_timestamp; // @synthesize sync_frame_timestamp=_sync_timestamp;
- (void).cxx_destruct;
- (void)reInit;
- (void)resume;
- (void)pause;
- (unsigned long long)getBufferedFrameCount;
- (unsigned long long)getDecodeCount;
- (unsigned long long)getFrameCount;
- (void)setExitCode:(int)arg1;
- (void)stop;
- (void)kill;
- (unsigned int)getVideoBufferFirstTS;
- (int)setClearVideoData:(unsigned int)arg1;
- (int)setClearVideoDataReally:(unsigned int)arg1;
- (void)setSyncTimeFirst;
- (id)nextFrame:(unsigned int *)arg1;
- (id)nextFrameReally:(unsigned int *)arg1;
- (void)doDecode;
- (void)doDecodeReally;
- (_Bool)shouldDiscard:(id)arg1;
- (void)enableDiscard:(_Bool)arg1;
- (_Bool)start;
- (void)waitStopped;
- (void)signalStopped;
- (void)threadMain;
- (void)onFrameExtracted:(id)arg1;
- (void)setVideoParam:(CDStruct_dcb0dccc *)arg1;
- (void)onCompleted;
- (_Bool)onMetaPrepared:(id)arg1;
- (_Bool)doPrepared:(id)arg1;
- (_Bool)getVideoInfo:(CDStruct_5164b2cd *)arg1;
- (void)destroy;
- (id)decodeFrame:(id)arg1 discard:(_Bool)arg2;
- (_Bool)create:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)DelJitterSink;
- (void)SetJitterSink:(void *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

