//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TVKNetworkCheckerDelegate.h"

@class NSString, QLActivityLabel, UILabel;

@interface QLWaitingView : UIView <TVKNetworkCheckerDelegate>
{
    id <QLWaitingViewDelegate> _delegate;
    QLActivityLabel *_loadingTabel;
    UILabel *_speedLabel;
    UILabel *_labelTip;
    _Bool _isShowTipMode;
    int _mode;
}

@property(nonatomic) __weak id <QLWaitingViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)networkCheckerUpdateFinish;
- (void)onVisibilityChanged:(_Bool)arg1;
- (void)updateShowMode:(_Bool)arg1;
- (void)showSpeed:(_Bool)arg1;
- (void)setWaitingViewMode:(int)arg1;
- (void)showTips:(id)arg1;
- (void)changePromptText:(id)arg1 withErrorCode:(id)arg2;
- (void)changePrompt:(id)arg1;
- (void)hide:(_Bool)arg1;
- (void)resetState;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

