//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSSet;

@interface QN3DTouchQuickActionManager : NSObject
{
    NSMutableDictionary *_validChannelDic;
    NSSet *_channelBlackList;
    NSMutableDictionary *_targetChannelDic;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *targetChannelDic; // @synthesize targetChannelDic=_targetChannelDic;
@property(retain, nonatomic) NSSet *channelBlackList; // @synthesize channelBlackList=_channelBlackList;
@property(retain, nonatomic) NSMutableDictionary *validChannelDic; // @synthesize validChannelDic=_validChannelDic;
- (void).cxx_destruct;
- (void)_updateApplicationQuickActionConfig;
- (void)_checkValidityForChannelId:(id)arg1;
- (void)_checkAndRemoveInvalidChannel;
- (void)updateApplicationQuickActionNotification:(id)arg1;
- (void)checkValidityChannelNotification:(id)arg1;
- (_Bool)performActionForShortcutItem:(id)arg1;
- (void)writeDataToDisk;
- (void)readDataFromDisk;
- (void)dealloc;
- (id)init;

@end

