//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBaseDetailViewController.h"

#import "QNShareActivityControllerDelegate.h"
#import "SKStoreProductViewControllerDelegate.h"
#import "TADLandingControlDelegate.h"
#import "TADLandingViewControllerDelegate.h"

@class NSString, QNAdItem, QNAdWebDetailParam, QNBarButton, QNEnlargeHitTestButton, QNListNewsItem, TADGDTPageLoadingItem, TADLandingViewController, TADNJKWebViewProgressView, TADQNLandingDurationItem, TADStoreViewController, UIActivityIndicatorView, UIButton, UILabel, UIView;

@interface QNAdWebDetailViewController : CBaseDetailViewController <SKStoreProductViewControllerDelegate, QNShareActivityControllerDelegate, TADLandingViewControllerDelegate, TADLandingControlDelegate>
{
    _Bool _landingViewRedirected;
    _Bool _loadingFinished;
    _Bool _willBeDismissed;
    _Bool _appstoreIsPresenting;
    _Bool _isEmptyWebview;
    _Bool _adLoadingAppStoreViewIsShowing;
    _Bool _commentEnabled;
    _Bool _disableQuitGestrue;
    _Bool _webCanGoBack;
    _Bool _ifDisableQuitGestureAsked;
    _Bool _closeLandingViewInBackground;
    double _startLoadTime;
    TADQNLandingDurationItem *_landingDurationItem;
    TADGDTPageLoadingItem *_gdtPageLoadingItem;
    TADGDTPageLoadingItem *_gdtClickCGIItem;
    UILabel *_loadingAppStoreLabel;
    TADStoreViewController *_storeViewController;
    UIActivityIndicatorView *_adLoadingView;
    QNAdItem *_adItem;
    QNBarButton *_adBackBtn;
    QNBarButton *_adCloseBtn;
    QNBarButton *_adActionBtn;
    TADLandingViewController *_landingViewController;
    TADNJKWebViewProgressView *_loadingProgressView;
    QNAdWebDetailParam *_adWebDetailParam;
    UIView *_webviewLeftBtnView;
    UIButton *_complaintBtn;
    QNEnlargeHitTestButton *_returnBtnView;
}

@property(nonatomic) _Bool closeLandingViewInBackground; // @synthesize closeLandingViewInBackground=_closeLandingViewInBackground;
@property(nonatomic) _Bool ifDisableQuitGestureAsked; // @synthesize ifDisableQuitGestureAsked=_ifDisableQuitGestureAsked;
@property(nonatomic) _Bool webCanGoBack; // @synthesize webCanGoBack=_webCanGoBack;
@property(retain, nonatomic) QNEnlargeHitTestButton *returnBtnView; // @synthesize returnBtnView=_returnBtnView;
@property(retain, nonatomic) UIButton *complaintBtn; // @synthesize complaintBtn=_complaintBtn;
@property(retain, nonatomic) UIView *webviewLeftBtnView; // @synthesize webviewLeftBtnView=_webviewLeftBtnView;
@property(retain, nonatomic) QNAdWebDetailParam *adWebDetailParam; // @synthesize adWebDetailParam=_adWebDetailParam;
@property(nonatomic) _Bool disableQuitGestrue; // @synthesize disableQuitGestrue=_disableQuitGestrue;
@property(retain, nonatomic) TADNJKWebViewProgressView *loadingProgressView; // @synthesize loadingProgressView=_loadingProgressView;
@property(retain, nonatomic) TADLandingViewController *landingViewController; // @synthesize landingViewController=_landingViewController;
@property(retain, nonatomic) QNBarButton *adActionBtn; // @synthesize adActionBtn=_adActionBtn;
@property(retain, nonatomic) QNBarButton *adCloseBtn; // @synthesize adCloseBtn=_adCloseBtn;
@property(retain, nonatomic) QNBarButton *adBackBtn; // @synthesize adBackBtn=_adBackBtn;
@property(retain, nonatomic) QNAdItem *adItem; // @synthesize adItem=_adItem;
@property(retain, nonatomic) UIActivityIndicatorView *adLoadingView; // @synthesize adLoadingView=_adLoadingView;
@property(retain, nonatomic) TADStoreViewController *storeViewController; // @synthesize storeViewController=_storeViewController;
@property(nonatomic) _Bool commentEnabled; // @synthesize commentEnabled=_commentEnabled;
@property(nonatomic) _Bool adLoadingAppStoreViewIsShowing; // @synthesize adLoadingAppStoreViewIsShowing=_adLoadingAppStoreViewIsShowing;
@property(nonatomic) _Bool isEmptyWebview; // @synthesize isEmptyWebview=_isEmptyWebview;
@property(nonatomic) _Bool appstoreIsPresenting; // @synthesize appstoreIsPresenting=_appstoreIsPresenting;
@property(retain, nonatomic) UILabel *loadingAppStoreLabel; // @synthesize loadingAppStoreLabel=_loadingAppStoreLabel;
@property(nonatomic) _Bool willBeDismissed; // @synthesize willBeDismissed=_willBeDismissed;
@property(nonatomic) _Bool loadingFinished; // @synthesize loadingFinished=_loadingFinished;
@property(retain, nonatomic) TADGDTPageLoadingItem *gdtClickCGIItem; // @synthesize gdtClickCGIItem=_gdtClickCGIItem;
@property(retain, nonatomic) TADGDTPageLoadingItem *gdtPageLoadingItem; // @synthesize gdtPageLoadingItem=_gdtPageLoadingItem;
@property(retain, nonatomic) TADQNLandingDurationItem *landingDurationItem; // @synthesize landingDurationItem=_landingDurationItem;
@property(nonatomic) _Bool landingViewRedirected; // @synthesize landingViewRedirected=_landingViewRedirected;
@property(nonatomic) double startLoadTime; // @synthesize startLoadTime=_startLoadTime;
- (void).cxx_destruct;
- (void)jumpUrl:(id)arg1;
- (_Bool)p_needReportClick;
- (void)tadWebViewDidReceiveServerRedirect;
- (void)tadWebViewDidFailedWithStatusCode:(long long)arg1 error:(id)arg2;
- (_Bool)tadWebViewShouldStartLoadWithRequest:(id)arg1;
- (void)didEnterBackground;
- (void)handleNotificctoinForSendCommentComplate:(id)arg1;
@property(readonly, copy) NSString *description;
- (_Bool)tadWebViewCanShowPanel;
- (_Bool)tadWebViewShouldRecognitionQRCodeByGesture;
- (void)tadWebViewAddWXCards:(id)arg1;
- (void)onComplaintSumUpdated:(long long)arg1;
- (void)tadWebViewTitle:(id)arg1;
- (void)adLandingViewDidDisappear;
- (void)willOpenInappAppStore;
- (void)tadWebViewLoadingUpdateProgress:(float)arg1;
- (void)refreshCurrentPage;
- (id)getCustomShareInfo;
- (id)getShareToEmailInfo;
- (_Bool)qnNavigationController:(id)arg1 shouldInteractiveGestureRecognizerBegin:(id)arg2;
- (_Bool)shouldUseNoRedirectUrLForShare:(id)arg1;
- (void)tadWebViewDidFinishLoad;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)closeADLandingViewController;
- (void)complaintAd;
- (void)p_showCloseButton;
- (void)onBack:(id)arg1;
- (void)webviewGoBack;
- (void)p_configComplaintBtn:(id)arg1 withText:(id)arg2;
- (void)p_setComplaintAndMoreBtn;
- (void)p_updateBackAndCloseBtn;
- (void)p_setBackAndCloseBtn;
- (void)onAdAction:(id)arg1;
- (void)viewWillLayoutSubviews;
- (_Bool)supportAttachMiniPlayerView;
- (void)viewDidLoad;
- (void)refreshContentData;
- (void)dealloc;
- (id)initWithParam:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) QNListNewsItem *listItem;
@property(readonly) Class superclass;

@end

