//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QNAppearanceManager : NSObject
{
    double _titleFont;
    double _lineSpan;
    double _imageRadius;
    double _detailLeftRightMargin;
    double _detailImageRadius;
    long long _detailFontStyle;
    unsigned long long _type;
    struct CGSize _imageSize;
    struct CGSize _focusImageSize;
    struct CGSize _focusVideoImageSize;
    struct UIEdgeInsets _cellInsets;
}

+ (id)sharedInstance;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, nonatomic) long long detailFontStyle; // @synthesize detailFontStyle=_detailFontStyle;
@property(readonly, nonatomic) double detailImageRadius; // @synthesize detailImageRadius=_detailImageRadius;
@property(readonly, nonatomic) double detailLeftRightMargin; // @synthesize detailLeftRightMargin=_detailLeftRightMargin;
@property(nonatomic) double imageRadius; // @synthesize imageRadius=_imageRadius;
@property(nonatomic) struct CGSize focusVideoImageSize; // @synthesize focusVideoImageSize=_focusVideoImageSize;
@property(nonatomic) struct CGSize focusImageSize; // @synthesize focusImageSize=_focusImageSize;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
@property(nonatomic) double lineSpan; // @synthesize lineSpan=_lineSpan;
@property(nonatomic) double titleFont; // @synthesize titleFont=_titleFont;
@property(nonatomic) struct UIEdgeInsets cellInsets; // @synthesize cellInsets=_cellInsets;
- (void)setDetailFontStyle:(id)arg1;
- (void)setDetailImageRadius:(id)arg1;
- (void)setDetailLeftRightMargin:(id)arg1;
- (void)setTBOffset:(double)arg1;
- (void)setRLOffset:(double)arg1;
- (void)updateWithType:(unsigned long long)arg1;
- (void)p_config;
- (id)init;

@end

