//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAbstractModelBuilder.h"

@interface QNArticleContentNodeQABuilder : QNAbstractModelBuilder
{
}

+ (id)builderWithModelCopy:(id)arg1;
+ (id)builder;
+ (id)fromDictionary:(id)arg1;
- (id)setFrame:(struct CGRect)arg1;
- (struct CGRect)frame;
- (id)setNodeKey:(id)arg1;
- (id)nodeKey;
- (id)setCommentId:(id)arg1;
- (id)commentId;
- (id)setArticleId:(id)arg1;
- (id)articleId;
- (id)setArticleUrl:(id)arg1;
- (id)articleUrl;
- (id)setTime:(id)arg1;
- (id)time;
- (id)setReplyCount:(unsigned long long)arg1;
- (unsigned long long)replyCount;
- (id)setAbstract:(id)arg1;
- (id)abstract;
- (id)setShowTitle:(id)arg1;
- (id)showTitle;
- (id)setTitle:(id)arg1;
- (id)title;
- (id)setQaType:(unsigned long long)arg1;
- (unsigned long long)qaType;
- (id)build;
- (id)do_createModelObject;
- (id)initWithModelCopy:(id)arg1;
- (id)init;
- (id)initWithDictionaryStub:(id)arg1;
- (void)do_customMapping:(id)arg1;

@end

