//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBundleBase.h"

@interface QNAutoBundle : QNBundleBase
{
}

+ (id)priceDownOptBtn;
+ (id)iconStartendsliderUpSlider;
+ (id)iconStartendsliderIndicatorBg;
+ (id)iconStartendsliderBellowSlider;
+ (id)icUp;
+ (id)icReduce;
+ (id)icLocation;
+ (id)icKeep;
+ (id)icHotTuiguang;
+ (id)icHotBrowse;
+ (id)icCar;
+ (id)cityIconLocation;
+ (id)carpickerSelectBg;
+ (id)carpickerBtnEnterClick;
+ (id)carpickerBtnEnter;
+ (id)carTagSelected;
+ (id)carTagPriceDown;
+ (id)carTagNor;
+ (id)carTagNewPriceDown;
+ (id)carRetSorry;
+ (id)carImageScale;
+ (id)carIconSuvPress;
+ (id)carIconSuvNor;
+ (id)carIconSportsPress;
+ (id)carIconSportsNor;
+ (id)carIconSmallPress;
+ (id)carIconSmallNor;
+ (id)carIconMpvPress;
+ (id)carIconMpvNor;
+ (id)carIconMidPress;
+ (id)carIconMidNor;
+ (id)carIconMicroPress;
+ (id)carIconMicroNor;
+ (id)carIconLuxuryPress;
+ (id)carIconLuxuryNor;
+ (id)carIconLargePress;
+ (id)carIconLargeNor;
+ (id)carIconCompactPress;
+ (id)carIconCompactNor;
+ (id)carConditionMore2;
+ (id)btnXuanchePressed;
+ (id)btnXuancheNormal;
+ (id)adviewdefault;
+ (id)pdfResources;
+ (id)sharedInstance;

@end

