//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QNAwardGetAwardInfoApi, QNAwardStoreUserAddressApi, QNTADGetWXCardInfoApi, QNWeixinCard;

@interface QNAwardManager : NSObject
{
    QNWeixinCard *_weixinCard;
    QNAwardGetAwardInfoApi *_getAwardInfoApi;
    QNAwardStoreUserAddressApi *_storeUserAddressApi;
}

+ (id)sharedInstance;
@property(retain, nonatomic) QNAwardStoreUserAddressApi *storeUserAddressApi; // @synthesize storeUserAddressApi=_storeUserAddressApi;
@property(retain, nonatomic) QNAwardGetAwardInfoApi *getAwardInfoApi; // @synthesize getAwardInfoApi=_getAwardInfoApi;
@property(retain, nonatomic) QNWeixinCard *weixinCard; // @synthesize weixinCard=_weixinCard;
- (void).cxx_destruct;
- (void)storeUserAddressWithCardIds:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)getCardInfoWithCardIds:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)addCardsToWXCardPackage:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)onWXResp:(id)arg1;
- (id)init;
- (void)tadAddWXCards:(id)arg1;
- (void)getTADCardInfoWithCardIds:(id)arg1 callback:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) QNTADGetWXCardInfoApi *wxCardInfoApi;

@end

