//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBaseModelObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class CArticleContentVideoAlbumNodeType, NSString;

@interface QNBaseDetailParam : QNBaseModelObject <NSCopying, NSCoding>
{
    NSString *_albumDetailsSelecetdID;
    CArticleContentVideoAlbumNodeType *_videoAlbumNode;
}

+ (id)build:(CDUnknownBlockType)arg1;
+ (_Bool)isImmutable;
@property(retain, nonatomic) CArticleContentVideoAlbumNodeType *videoAlbumNode; // @synthesize videoAlbumNode=_videoAlbumNode;
@property(copy, nonatomic) NSString *albumDetailsSelecetdID; // @synthesize albumDetailsSelecetdID=_albumDetailsSelecetdID;
- (void).cxx_destruct;
- (id)copyInstance;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

