//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, QNBundleBase;

@interface QNBundleResource : NSObject
{
    QNBundleBase *_bundle;
    unsigned long long _folderType;
    NSString *_basename;
    NSString *_extension;
}

@property(readonly, copy, nonatomic) NSString *extension; // @synthesize extension=_extension;
@property(readonly, copy, nonatomic) NSString *basename; // @synthesize basename=_basename;
@property(readonly, nonatomic) unsigned long long folderType; // @synthesize folderType=_folderType;
@property(readonly, nonatomic) QNBundleBase *bundle; // @synthesize bundle=_bundle;
- (void).cxx_destruct;
- (id)relativePathWithTimeStamp;
- (id)absolutePath;
- (id)relativePath;
- (id)filename;
- (id)initWithBundle:(id)arg1 basename:(id)arg2 extension:(id)arg3 folderType:(unsigned long long)arg4;

@end

