//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QNCacheFilesDebug : NSObject
{
    unsigned long long _displayType;
}

@property(nonatomic) unsigned long long displayType; // @synthesize displayType=_displayType;
- (id)p_HtmlStringFromFileItems:(id)arg1;
- (id)directoryAndFilesTree:(id)arg1 verbose:(_Bool)arg2 totalSize:(unsigned long long *)arg3 displayType:(unsigned long long)arg4;

@end

