//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface QNCellTimeConsumeFeedBack : NSObject
{
    NSMutableDictionary *_consumeItemCacheDic;
}

+ (id)strictVisibleCellsOfUICollectionView:(id)arg1 topOffset:(double)arg2 bottomOffset:(double)arg3;
+ (id)strictVisibleCellsOfTableView:(id)arg1 topOffset:(double)arg2 bottomOffset:(double)arg3;
+ (id)p_keyOfChannel:(id)arg1 isSpecial:(_Bool)arg2;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *consumeItemCacheDic; // @synthesize consumeItemCacheDic=_consumeItemCacheDic;
- (void).cxx_destruct;
- (void)reportReadyCellTimeConsumeInChannel:(id)arg1 items:(id)arg2 isSpecial:(_Bool)arg3;
- (void)reportReadyCellTimeConsumeInChannel:(id)arg1 items:(id)arg2;
- (void)reportCellTimeConsumeInChannel:(id)arg1 isSpecial:(_Bool)arg2;
- (void)reportCellTimeConsumeInChannel:(id)arg1;

@end

