//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface QNCellExplosureReportManager : NSObject
{
    _Bool _isBottomLineExplosure;
    NSMutableDictionary *_explosureDic;
    NSMutableDictionary *_showExplosureDic;
    double _time;
    long long _currentExplosureType;
    NSString *_currentChannelId;
    NSString *_previousChannelId;
    NSString *_detailArticleId;
    double _bottomLineExplosureStartTime;
}

+ (id)sharedInstance;
@property(nonatomic) double bottomLineExplosureStartTime; // @synthesize bottomLineExplosureStartTime=_bottomLineExplosureStartTime;
@property(nonatomic) _Bool isBottomLineExplosure; // @synthesize isBottomLineExplosure=_isBottomLineExplosure;
@property(copy, nonatomic) NSString *detailArticleId; // @synthesize detailArticleId=_detailArticleId;
@property(copy, nonatomic) NSString *previousChannelId; // @synthesize previousChannelId=_previousChannelId;
@property(copy, nonatomic) NSString *currentChannelId; // @synthesize currentChannelId=_currentChannelId;
@property(nonatomic) long long currentExplosureType; // @synthesize currentExplosureType=_currentExplosureType;
@property(nonatomic) double time; // @synthesize time=_time;
@property(retain, nonatomic) NSMutableDictionary *showExplosureDic; // @synthesize showExplosureDic=_showExplosureDic;
@property(retain, nonatomic) NSMutableDictionary *explosureDic; // @synthesize explosureDic=_explosureDic;
- (void).cxx_destruct;
- (void)listWillLeaveNotification:(id)arg1;
- (void)detailDidLeaveNotification:(id)arg1;
- (void)detailDidEnterNotification:(id)arg1;
- (void)currentChannelChanged:(id)arg1;
- (void)_clearAndReportAll;
- (void)_checkArticleBottomExplosure:(_Bool)arg1 explosureType:(long long)arg2 channelId:(id)arg3 articleId:(id)arg4;
- (void)checkArticleBottomExplosure:(id)arg1 containerScrollView:(id)arg2 explosureType:(long long)arg3 channelId:(id)arg4 articleId:(id)arg5;
- (void)_checkExplosureAndReportWithStartRow:(long long)arg1 endRow:(long long)arg2 explosureType:(long long)arg3 channelId:(id)arg4 articleId:(id)arg5 explosureStatisticType:(long long)arg6;
- (void)checkExplosureAndReportWithListView:(id)arg1 containerScrollView:(id)arg2 explosureType:(long long)arg3 channelId:(id)arg4 articleId:(id)arg5;
- (void)dealloc;
- (id)init;

@end

