//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBundleBase.h"

@interface QNChannelaudioBundle : QNBundleBase
{
}

+ (id)audioTabIconDownloadPause;
+ (id)audioTabIconDownloadInit;
+ (id)audioTabIconDownloadDisabled;
+ (id)audioTabIconDownload;
+ (id)audioTabIconBlueBg;
+ (id)audioTabIconDownloadmanager;
+ (id)audioPlayLoadingGif;
+ (id)audioListIconPlayOrder;
+ (id)audioListIconPlayOne;
+ (id)audioListIconPause;
+ (id)audioListIconMusicPlaying;
+ (id)audioListIconMusicNotplaying;
+ (id)audioListIconLivestatusOver;
+ (id)audioListIconLivestatusNotstarted;
+ (id)audioListIconLivestatusAlreadystarted;
+ (id)audioListIconLive;
+ (id)audioListIconDownloadPressed;
+ (id)audioListIconDownloadOk;
+ (id)audioListIconDownload;
+ (id)audioFlotBg;
+ (id)audioDetailCommonSlider;
+ (id)audioDetailCommonPlaybutton;
+ (id)audioDetailCommonPausebutton;
+ (id)audioDetailBgMusic;
+ (id)audioControlUnbtPrevious;
+ (id)audioControlUnbtNext;
+ (id)audioControlIconId;
+ (id)audioControlBtPlayPress;
+ (id)audioControlBtPlay;
+ (id)audioControlBtPausePress;
+ (id)audioControlBtPause;
+ (id)audioControlBtNextPress;
+ (id)audioControlBtNext;
+ (id)audioControlBtLastPress;
+ (id)audioControlBtLast;
+ (id)audioControlBgLoading;
+ (id)audioControlBgId;
+ (id)audioBtMorePress;
+ (id)audioBtMore;
+ (id)audioBtFlotPlayNew;
+ (id)audioBtFlotDownload;
+ (id)audioBannerBg;
+ (id)pdfResources;
+ (id)sharedInstance;

@end

