//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAbstractModelBuilder.h"

@interface QNControllerParamBuilder : QNAbstractModelBuilder
{
}

+ (id)builderWithModelCopy:(id)arg1;
+ (id)builder;
- (id)setReportParam:(id)arg1;
- (id)reportParam;
- (id)setSubscribeChannelParam:(id)arg1;
- (id)subscribeChannelParam;
- (id)setSportsParam:(id)arg1;
- (id)sportsParam;
- (id)setDaylikeParam:(id)arg1;
- (id)daylikeParam;
- (id)setHotEventsListParam:(id)arg1;
- (id)hotEventsListParam;
- (id)setEventTimeLineParam:(id)arg1;
- (id)eventTimeLineParam;
- (id)setUgcVideoDetailParam:(id)arg1;
- (id)ugcVideoDetailParam;
- (id)setLiveDetailListParam:(id)arg1;
- (id)liveDetailListParam;
- (id)setMediaPickerParam:(id)arg1;
- (id)mediaPickerParam;
- (id)setAnswersListParam:(id)arg1;
- (id)answersListParam;
- (id)setReplyInfoParam:(id)arg1;
- (id)replyInfoParam;
- (id)setPortraitVideoParam:(id)arg1;
- (id)portraitVideoParam;
- (id)setRoseParam:(id)arg1;
- (id)roseParam;
- (id)setTopicParam:(id)arg1;
- (id)topicParam;
- (id)setCNewsViewParam:(id)arg1;
- (id)cNewsViewParam;
- (id)setListTagVideoParam:(id)arg1;
- (id)listTagVideoParam;
- (id)setBaseDetailParam:(id)arg1;
- (id)baseDetailParam;
- (id)setAwNewsListParam:(id)arg1;
- (id)awNewsListParam;
- (id)setSearchResultTagAndMediaParam:(id)arg1;
- (id)searchResultTagAndMediaParam;
- (id)setVideoViewParam:(id)arg1;
- (id)videoViewParam;
- (id)setPreciousDetailParam:(id)arg1;
- (id)preciousDetailParam;
- (id)setPrivateLetterParam:(id)arg1;
- (id)privateLetterParam;
- (id)setSearchNewsParam:(id)arg1;
- (id)searchNewsParam;
- (id)setSearchResultParam:(id)arg1;
- (id)searchResultParam;
- (id)setSubscribeManagerParam:(id)arg1;
- (id)subscribeManagerParam;
- (id)setSubscribeViewParam:(id)arg1;
- (id)subscribeViewParam;
- (id)setSpecialViewParam:(id)arg1;
- (id)specialViewParam;
- (id)setCarWebViewParam:(id)arg1;
- (id)carWebViewParam;
- (id)setPortfolioParam:(id)arg1;
- (id)portfolioParam;
- (id)setMatchDetailParam:(id)arg1;
- (id)matchDetailParam;
- (id)setGuestMainParam:(id)arg1;
- (id)guestMainParam;
- (id)setAdWebDetailParam:(id)arg1;
- (id)adWebDetailParam;
- (id)setWebViewParam:(id)arg1;
- (id)webViewParam;
- (id)setCommonParam:(id)arg1;
- (id)commonParam;
- (id)build;
- (id)do_createModelObject;
- (id)initWithModelCopy:(id)arg1;
- (id)init;

@end

