//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNCommentCellBaseUnitModel.h"

@class NSAttributedString, NSURL, QNBaseViewModel;

@interface QNCommentCellMyMentionContentUnitModel : QNCommentCellBaseUnitModel
{
    _Bool _shouldUnfoldInCurrentPage;
    _Bool _showImage;
    QNBaseViewModel *_contentUnit;
    QNBaseViewModel *_viewCommentUnit;
    NSAttributedString *_content;
    NSAttributedString *_viewCommentTitle;
    QNBaseViewModel *_picUnit;
    NSURL *_picUrl;
}

@property(nonatomic) _Bool showImage; // @synthesize showImage=_showImage;
@property(nonatomic) _Bool shouldUnfoldInCurrentPage; // @synthesize shouldUnfoldInCurrentPage=_shouldUnfoldInCurrentPage;
@property(copy, nonatomic) NSURL *picUrl; // @synthesize picUrl=_picUrl;
@property(retain, nonatomic) QNBaseViewModel *picUnit; // @synthesize picUnit=_picUnit;
@property(copy, nonatomic) NSAttributedString *viewCommentTitle; // @synthesize viewCommentTitle=_viewCommentTitle;
@property(copy, nonatomic) NSAttributedString *content; // @synthesize content=_content;
@property(retain, nonatomic) QNBaseViewModel *viewCommentUnit; // @synthesize viewCommentUnit=_viewCommentUnit;
@property(retain, nonatomic) QNBaseViewModel *contentUnit; // @synthesize contentUnit=_contentUnit;
- (void).cxx_destruct;
- (void)setBgColor:(id)arg1;
- (double)p_textLineSpacing:(id)arg1;
- (id)p_textFont:(id)arg1;
- (id)p_unfoldTextColor:(id)arg1;
- (id)p_contentTextColor:(id)arg1;
- (_Bool)p_shouldUnfoldInCurrentPage:(id)arg1;
- (unsigned long long)p_linesIfTruncatedWithContext:(id)arg1;
- (unsigned long long)p_maxLinesWithContext:(id)arg1;
- (void)calculateWithData:(id)arg1 referRect:(struct CGRect)arg2 context:(id)arg3;

@end

