//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableTableViewCell.h"

#import "CContextMenuDelegate.h"
#import "QNListCellProtocol.h"

@class NSString, QNCommentCellBaseUnitModel;

@interface QNCommentBaseCell : QNThemableTableViewCell <CContextMenuDelegate, QNListCellProtocol>
{
    id <QNCommentCellActionDelegate> _actionDelegate;
    QNCommentCellBaseUnitModel *_cellModel;
}

+ (id)reuseIdentifierForData:(id)arg1;
@property(retain, nonatomic) QNCommentCellBaseUnitModel *cellModel; // @synthesize cellModel=_cellModel;
@property(nonatomic) __weak id <QNCommentCellActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (void).cxx_destruct;
- (_Bool)p_weiboContextMenuSelector:(SEL)arg1;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)contextMenuSortItems:(id)arg1;
- (void)contextMenuWillDisAppear;
- (void)contextMenuWillAppear;
- (void)prepareForReuse;
- (void)layoutWithViewModel:(id)arg1 context:(id)arg2;
- (void)addSubview:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

