//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KBAbstractListController.h"

#import "KBListControllerSubclassProtocol.h"
#import "KBListModelDelegate.h"
#import "KBRefreshAnimationDelegate.h"
#import "QNCommonListControllerDelegate.h"
#import "QNExplosureReportDelegate.h"
#import "QNListVideoAssistorDelegate.h"
#import "QNWeiboCellActionDelegate.h"
#import "QSVerticalScheduleCellDelegate.h"
#import "TADStreamManagerDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSDate, NSString, NSTimer, QNAdItem, QNChannelsRecommendCell, QNColorButton, QNCombineLocationChannelsRemindView, QNListCellAnimationMonitor, QNListShowVerticalCellTipView, QNListVideoAssistor, QNPair, QNSyncHashMap, QNTopicItem, UIView;

@interface QNCommonListController : KBAbstractListController <TADStreamManagerDelegate, QNListVideoAssistorDelegate, QNExplosureReportDelegate, QNWeiboCellActionDelegate, UIGestureRecognizerDelegate, QSVerticalScheduleCellDelegate, KBListControllerSubclassProtocol, QNCommonListControllerDelegate, KBRefreshAnimationDelegate, KBListModelDelegate>
{
    QNPair *_itemPairForSeparator;
    _Bool _enableShowTabBarNewsTabHelpView;
    _Bool _topToolBarNeedAutoScroll;
    _Bool _isPlayerControl;
    _Bool _isFromDetail;
    QNListVideoAssistor *_videoAssistor;
    CDUnknownBlockType _didCheckedTopToolBarHiddenBlock;
    QNAdItem *_firstCellAdItem;
    QNColorButton *_bottomButton;
    NSString *_currentCityID;
    NSString *_parentChannelID;
    NSDate *_lastRefreshDate;
    double _tipsViewAnimTimeInterval;
    QNListShowVerticalCellTipView *_showVerticalTipView;
    QNListCellAnimationMonitor *_cellAnimationMonitor;
    QNSyncHashMap *_visableAnimatingCellsMap;
    NSTimer *_refreshTipCheckTimer;
    UIView *_matchBgView;
    QNChannelsRecommendCell *_recChannelsRecommendCell;
    QNTopicItem *_topicItem;
    QNCombineLocationChannelsRemindView *_combineLocationChannelsTip;
}

@property(nonatomic) _Bool isFromDetail; // @synthesize isFromDetail=_isFromDetail;
@property(retain, nonatomic) QNCombineLocationChannelsRemindView *combineLocationChannelsTip; // @synthesize combineLocationChannelsTip=_combineLocationChannelsTip;
@property(retain, nonatomic) QNTopicItem *topicItem; // @synthesize topicItem=_topicItem;
@property(retain, nonatomic) QNChannelsRecommendCell *recChannelsRecommendCell; // @synthesize recChannelsRecommendCell=_recChannelsRecommendCell;
@property(retain, nonatomic) UIView *matchBgView; // @synthesize matchBgView=_matchBgView;
@property(retain, nonatomic) NSTimer *refreshTipCheckTimer; // @synthesize refreshTipCheckTimer=_refreshTipCheckTimer;
@property(retain, nonatomic) QNSyncHashMap *visableAnimatingCellsMap; // @synthesize visableAnimatingCellsMap=_visableAnimatingCellsMap;
@property(retain, nonatomic) QNListCellAnimationMonitor *cellAnimationMonitor; // @synthesize cellAnimationMonitor=_cellAnimationMonitor;
@property(retain, nonatomic) QNListShowVerticalCellTipView *showVerticalTipView; // @synthesize showVerticalTipView=_showVerticalTipView;
@property(nonatomic) double tipsViewAnimTimeInterval; // @synthesize tipsViewAnimTimeInterval=_tipsViewAnimTimeInterval;
@property(retain, nonatomic) NSDate *lastRefreshDate; // @synthesize lastRefreshDate=_lastRefreshDate;
@property(nonatomic) _Bool isPlayerControl; // @synthesize isPlayerControl=_isPlayerControl;
@property(copy, nonatomic) NSString *parentChannelID; // @synthesize parentChannelID=_parentChannelID;
@property(copy, nonatomic) NSString *currentCityID; // @synthesize currentCityID=_currentCityID;
@property(nonatomic) _Bool topToolBarNeedAutoScroll; // @synthesize topToolBarNeedAutoScroll=_topToolBarNeedAutoScroll;
@property(retain, nonatomic) QNColorButton *bottomButton; // @synthesize bottomButton=_bottomButton;
@property(retain, nonatomic) QNAdItem *firstCellAdItem; // @synthesize firstCellAdItem=_firstCellAdItem;
@property(copy, nonatomic) CDUnknownBlockType didCheckedTopToolBarHiddenBlock; // @synthesize didCheckedTopToolBarHiddenBlock=_didCheckedTopToolBarHiddenBlock;
@property(readonly, nonatomic) QNListVideoAssistor *videoAssistor; // @synthesize videoAssistor=_videoAssistor;
@property(nonatomic) _Bool enableShowTabBarNewsTabHelpView; // @synthesize enableShowTabBarNewsTabHelpView=_enableShowTabBarNewsTabHelpView;
- (void).cxx_destruct;
- (void)_handleHelpViewDidDisappear;
- (void)_handleAppStoreVCDismiss;
- (void)p_checkAdCellExposureFrom:(unsigned long long)arg1;
- (void)p_removeUnvisableAnimatingCellIfNeed:(id)arg1;
- (void)p_tryMonitorAnimatingCellInVisableMap;
- (void)p_addMonitorToAnimatingCell:(id)arg1;
- (id)p_keyForAnimatingCell:(id)arg1;
- (void)p_checkAndMonitorToCellIfNeed:(id)arg1;
- (id)p_fakeAnswerListItem:(id)arg1;
- (id)subclassControllerStateForReusable;
- (void)recoverSubclassControllerState:(id)arg1;
- (_Bool)shouldRecoverSubclassControllerState:(id)arg1;
- (void)handlePlayerTypeAutoToPlay;
- (void)didComeInThisControllWithFromContorller:(id)arg1 changeType:(long long)arg2;
- (_Bool)needContinuePlayCurrentVideo:(long long)arg1;
- (void)didLeaveThisControllWithToContorller:(id)arg1 changeType:(long long)arg2;
- (void)willComeInThisControllWithFromContorller:(id)arg1 changeType:(long long)arg2;
- (void)willLeaveThisControllWithToContorller:(id)arg1 changeType:(long long)arg2;
- (void)_startVideoPreLoadWithVideoList:(id)arg1;
- (void)p_prefetchVideoData;
- (void)_initVideoAssistor;
- (void)weiboCell:(id)arg1 actionToViewDetail:(id)arg2 viewComment:(_Bool)arg3;
- (void)weiboCell:(id)arg1 actionToDelete:(id)arg2;
- (void)weiboCell:(id)arg1 actionToPlayVideo:(id)arg2 isAutoPlay:(_Bool)arg3;
- (void)weiboCell:(id)arg1 actionToViewTopic:(id)arg2;
- (void)weiboCell:(id)arg1 actionToShare:(id)arg2;
- (void)weiboCell:(id)arg1 actionToLike:(id)arg2;
- (void)weiboCell:(id)arg1 actionToViewPersonalDetail:(id)arg2;
- (void)allMatchButtonDidTapInVerticalScheduleCell:(id)arg1;
- (_Bool)canPlayVideoWithListVideoAssistor:(id)arg1;
- (void)checkInfoForReport;
- (void)_cleanChannelDataAndRefresh;
- (void)_updateCityDataIfNeed;
- (void)_checkCurrentCity;
- (void)_handleCityRemoteConfChecked:(id)arg1;
- (void)updateCurrentChannelIDIfNeed:(id)arg1;
- (void)_handleVideoPlay;
- (void)commonListContollerPackupCell:(id)arg1 packup:(_Bool)arg2 listItem:(id)arg3;
- (void)commonListContollerRefreshCell:(id)arg1 listItem:(id)arg2 animation:(long long)arg3;
- (void)commonListContollerDeleteCell:(id)arg1 listItem:(id)arg2;
- (void)complaintAdItem:(id)arg1;
- (void)loadStreamAd;
- (void)loadAdList;
- (_Bool)isFastRefresh;
- (void)_reportUnexposedRecommendVideoNews:(id)arg1 channelID:(id)arg2;
- (_Bool)_addRecommendVideo:(id)arg1 origChannel:(id)arg2 origIdStr:(id)arg3;
- (void)p_handlePlayRecommendPersentEvent:(id)arg1;
- (void)p_resetChannelBtnState;
- (void)p_setTopToolBarSwitchBlockForCity;
- (void)p_setTopToolBarSwitchBlockForChannelWithItem:(id)arg1;
- (void)p_showSwitchBtnForLocalWithShowVerticalCell:(_Bool)arg1;
- (void)p_showLocationInfo;
- (void)checkTopToolBarStateIsRefreshing:(_Bool)arg1;
- (void)_initTopToolBar;
- (void)_checkExplosureCellForReport;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)p_tapOnMatchBgView:(id)arg1;
- (_Bool)_isSportsChannel;
- (void)p_hideMatchView:(_Bool)arg1;
- (void)p_showMatchView:(id)arg1 originY:(float)arg2;
- (void)_handleSportsCloseMatchEntranceListViewNotification:(id)arg1;
- (void)_handleSportsShowMatchEntranceListViewNotification:(id)arg1;
- (void)_handleSportsDetailScheduleNotification:(id)arg1;
- (void)_handleUserHasConfirmChannelsRecommend;
- (void)p_scrollUpIfCellAtBottom;
- (void)p_showActivityWeltViewIfNeeded;
- (void)_handleWeiboDeleted:(id)arg1;
- (void)p_resetToolBarState;
- (void)_delayPackUpSearchBar:(id)arg1;
- (void)_handleWillEnterForegroundNotification:(id)arg1;
- (void)themeChanged:(long long)arg1;
- (void)p_startAnimations;
- (void)refreshCurrentChannel;
- (void)forceToRefreshCurrentChannel;
- (void)didBecomeActiveAsCurrentChannel;
- (void)didEnterBackgroundAsCurrentChannel;
- (void)p_checkRefreshTipRemindWithAllCheck:(_Bool)arg1;
- (void)p_checkRefreshTipRemind;
- (void)p_checkRefreshTipRemindFireWithTimer;
- (void)do_selectedAsCurrentChannel:(id)arg1;
- (void)do_deselectedAsCurrentChannel:(id)arg1;
- (void)showTopTipsView:(id)arg1;
- (void)refreshAnimationEnd:(id)arg1;
- (void)refreshAnimationBegin:(id)arg1;
- (void)listModel:(id)arg1 didDeleteItemsAtIndexes:(id)arg2;
- (void)listModel:(id)arg1 didInsertItemsAtIndexes:(id)arg2;
- (void)p_configSeparatorItems;
- (void)listModeldidReplaceAllItems:(id)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)handlePushRequestOpen:(_Bool)arg1 type:(long long)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)p_hotSpotCellItemClickWithlistItem:(id)arg1 newsItems:(id)arg2 indexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)p_newsViewControllerNavigate:(id)arg1 indexPath:(id)arg2 cellType:(long long)arg3;
- (_Bool)p_openTopicDetailWithItem:(id)arg1;
- (_Bool)p_openModuleMorePageView:(id)arg1;
- (void)p_openVideoChannelGuidance;
- (_Bool)p_openCategorySelectionWithModuleItem:(id)arg1 type:(id)arg2;
- (void)p_openSpecialListWithModuleItem:(id)arg1 type:(id)arg2;
- (void)p_openSpecialListOfModuleItem:(id)arg1 specialType:(long long)arg2;
- (void)openNewsAtIndexPath:(id)arg1;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)willPullToRefresh;
- (_Bool)canShowJumpToRecommendListTip;
- (void)modelDidPullData;
- (void)p_loadWeatherInfo;
- (void)additionalOperationsAfterLoadModelSuccess:(id)arg1;
- (void)p_additionalOperationsAfterLoadModelForAllOrTop:(id)arg1;
- (void)p_additionalOperationsAfterLoadModelForTop:(id)arg1;
- (void)p_checkPushAlertView;
- (id)customLIstTopToolBar;
- (id)customListDataAdapter;
- (id)customViewModel;
- (id)headerView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)pageTypeForReport;
- (void)dealloc;
- (void)_addNotificationsObserver;
- (void)configBarButtons;
- (id)initWithID:(id)arg1;
- (_Bool)p_openHotEventsPageViewWithModuleItem:(id)arg1 type:(id)arg2;
- (_Bool)p_openHotEventsPageView:(id)arg1;
- (_Bool)p_openHotSpot24HourPageView:(id)arg1;
- (void)p_checkCurrentChannelWithCityItem:(id)arg1;
- (void)p_cleanChannelDataAndRefresh;
- (_Bool)p_shouldAutoPlayVideo;
- (void)p_handleCityDataUpdate:(id)arg1;
- (void)p_handleChangeCity:(id)arg1;
- (void)p_handleVerticalCellNotAutoHideNotification;
- (void)p_handleWillEnterForegroundNotification:(id)arg1;
- (void)p_addNotificationsObserver;
- (void)_packupVerticalCell:(_Bool)arg1 indexPath:(id)arg2 position:(id)arg3 isAuto:(_Bool)arg4;
- (void)p_packupVerticalCell:(_Bool)arg1 indexPath:(id)arg2 position:(id)arg3 isAuto:(_Bool)arg4;
- (void)p_checkTopToolBarForHiddenWithAnimation:(_Bool)arg1;
- (void)p_showPackupVerticalCellBtn:(_Bool)arg1 animation:(_Bool)arg2 checkHidden:(_Bool)arg3;
- (void)p_showPackupVertical;
- (void)p_reportModuleCellClickWithItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

