//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBaseModelObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSArray, NSObject<NSCoding>, NSString, QNListExtendData, QNListModelMemeryInfo;

@interface QNControllerMemeryInfo : QNBaseModelObject <NSCopying, NSCoding>
{
    _Bool _hasNextPage;
    _Bool _isTextMode;
    NSString *_channelID;
    double _timestamp;
    long long _tableViewOffsetY;
    long long _pageNumber;
    unsigned long long _refreshMode;
    QNListExtendData *_extendData;
    NSArray *_kbListItems;
    NSArray *_dbListItems;
    NSObject<NSCoding> *_subClassInfo;
    QNListModelMemeryInfo *_listModelInfo;
    long long _fontType;
    double _lastRefreshTime;
}

+ (id)build:(CDUnknownBlockType)arg1;
+ (_Bool)isImmutable;
@property(nonatomic) double lastRefreshTime; // @synthesize lastRefreshTime=_lastRefreshTime;
@property(nonatomic) long long fontType; // @synthesize fontType=_fontType;
@property(nonatomic) _Bool isTextMode; // @synthesize isTextMode=_isTextMode;
@property(retain, nonatomic) QNListModelMemeryInfo *listModelInfo; // @synthesize listModelInfo=_listModelInfo;
@property(retain, nonatomic) NSObject<NSCoding> *subClassInfo; // @synthesize subClassInfo=_subClassInfo;
@property(copy, nonatomic) NSArray *dbListItems; // @synthesize dbListItems=_dbListItems;
@property(copy, nonatomic) NSArray *kbListItems; // @synthesize kbListItems=_kbListItems;
@property(retain, nonatomic) QNListExtendData *extendData; // @synthesize extendData=_extendData;
@property(nonatomic) unsigned long long refreshMode; // @synthesize refreshMode=_refreshMode;
@property(nonatomic) long long pageNumber; // @synthesize pageNumber=_pageNumber;
@property(nonatomic) _Bool hasNextPage; // @synthesize hasNextPage=_hasNextPage;
@property(nonatomic) long long tableViewOffsetY; // @synthesize tableViewOffsetY=_tableViewOffsetY;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(copy, nonatomic) NSString *channelID; // @synthesize channelID=_channelID;
- (void).cxx_destruct;
- (id)copyInstance;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

