//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNCommentCellBaseUnitView.h"

@class QNBaseLabel;

@interface QNCommentCellRelevantRefNewsUnitView : QNCommentCellBaseUnitView
{
    CDUnknownBlockType _titleClickedBlock;
    QNBaseLabel *_titleLabel;
}

@property(retain, nonatomic) QNBaseLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType titleClickedBlock; // @synthesize titleClickedBlock=_titleClickedBlock;
- (void).cxx_destruct;
- (void)p_newsTitleClicked;
- (void)updateBgColor:(_Bool)arg1;
- (void)prepareForReuse;
- (void)layoutWithViewModel:(id)arg1 context:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

