//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNCommentCellBaseUnitModel.h"

#import "QNListTextUnitModel.h"

@class NSAttributedString, NSString, UIColor;

@interface QNCommentCellTopicUnitModel : QNCommentCellBaseUnitModel <QNListTextUnitModel>
{
    _Bool _showUnfoldLabel;
    _Bool _enableTapGesture;
    _Bool _showOrigTitle;
    NSAttributedString *_attributedText;
    struct CGRect _textRect;
}

@property(readonly, nonatomic) _Bool showOrigTitle; // @synthesize showOrigTitle=_showOrigTitle;
@property(readonly, nonatomic) _Bool enableTapGesture; // @synthesize enableTapGesture=_enableTapGesture;
@property(readonly, nonatomic) _Bool showUnfoldLabel; // @synthesize showUnfoldLabel=_showUnfoldLabel;
@property(readonly, nonatomic) struct CGRect textRect; // @synthesize textRect=_textRect;
@property(readonly, copy, nonatomic) NSAttributedString *attributedText; // @synthesize attributedText=_attributedText;
- (void).cxx_destruct;
- (void)calculateWithData:(id)arg1 referRect:(struct CGRect)arg2 context:(id)arg3;

// Remaining properties
@property(readonly, nonatomic) UIColor *bgColor;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) unsigned long long lineBoundsOption;
@property(readonly, nonatomic) struct CGRect rect;
@property(readonly) Class superclass;
@property(readonly, nonatomic) struct CGRect unfoldLabelRect;
@property(readonly, copy, nonatomic) NSAttributedString *unfoldText;

@end

