//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class QNListNewsItem;

@protocol QNCommonListChannelVideoControllerProtocol

@optional
- (void)didPlayWithItem:(QNListNewsItem *)arg1;
- (void)willPlayWithItem:(QNListNewsItem *)arg1;
@end

