//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNNetworkJSONDictionaryApi.h"

#import "NSCopying.h"

@class NSString;

@interface QNConcernTagWhiteListApi : QNNetworkJSONDictionaryApi <NSCopying>
{
    NSString *_version;
}

@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithVersion:(id)arg1;

@end

