//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class QNBaseLabel, UIButton;

@interface QNCommentDeclareView : UIView
{
    UIButton *_declareButton;
    QNBaseLabel *_countLabel;
}

@property(retain, nonatomic) QNBaseLabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UIButton *declareButton; // @synthesize declareButton=_declareButton;
- (void).cxx_destruct;
- (void)setBackgroundColor:(id)arg1;
- (void)p_doPlus1Animation;
- (void)p_doDislikeAnimation;
- (void)p_doLikeAnimation;
- (void)layoutWithDeclareCountSize:(struct CGSize)arg1 countString:(id)arg2 declareState:(long long)arg3 clicked:(_Bool)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

