//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, QNCommentItem, QNListNewsItem;

@interface QNCommentsViewModel : NSObject
{
    _Bool _isLoading;
    _Bool _isLive;
    id <QNDanmuUpdateProtocol> _delegate;
    QNListNewsItem *_listItem;
    QNCommentItem *_refCommentItem;
    NSString *_refReplyId;
}

@property(readonly, nonatomic) _Bool isLive; // @synthesize isLive=_isLive;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(copy, nonatomic) NSString *refReplyId; // @synthesize refReplyId=_refReplyId;
@property(retain, nonatomic) QNCommentItem *refCommentItem; // @synthesize refCommentItem=_refCommentItem;
@property(retain, nonatomic) QNListNewsItem *listItem; // @synthesize listItem=_listItem;
@property(nonatomic) __weak id <QNDanmuUpdateProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)p_loadMoreCommentsFinished:(id)arg1 hasMore:(_Bool)arg2;
- (void)p_loadMoreNewsComments;
- (void)p_updateNewsComments;
- (void)p_loadMoreDanmuComments;
- (void)p_updateDanmuComments;
- (void)sendComment:(id)arg1;
- (void)loadMoreComments;
- (void)updateComments;
- (id)initWithListItem:(id)arg1;

@end

