//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBaseViewModel.h"

#import "QNListUnitModelProtocol.h"

@class NSString, QNComment, UIColor;

@interface QNCommentCellBaseUnitModel : QNBaseViewModel <QNListUnitModelProtocol>
{
    QNComment *_comment;
}

@property(retain, nonatomic) QNComment *comment; // @synthesize comment=_comment;
- (void).cxx_destruct;
- (void)calculateWithData:(id)arg1 referRect:(struct CGRect)arg2 context:(id)arg3;

// Remaining properties
@property(readonly, nonatomic) UIColor *bgColor;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) struct CGRect rect;
@property(readonly) Class superclass;

@end

