//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNDetailComponentBase.h"

#import "QNDetailVideoFloatingViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSMutableDictionary, NSString, QNDetailVideoFloatingView, QNVideoRecommendModel, UIView;

@interface QNDetailComponentVideo : QNDetailComponentBase <QNDetailVideoFloatingViewDelegate, UIGestureRecognizerDelegate>
{
    _Bool _isVideoPlayerControl;
    _Bool _hasReportFloatingView;
    NSMutableDictionary *_videoReportStateDictionary;
    QNDetailVideoFloatingView *_videoFloatingView;
    UIView *_floatingClipView;
    QNVideoRecommendModel *_recommendModel;
    NSArray *_recommendList;
    NSString *_currentRequestRecommendVid;
    NSString *_textModeClickIndex;
}

@property(nonatomic) _Bool hasReportFloatingView; // @synthesize hasReportFloatingView=_hasReportFloatingView;
@property(copy, nonatomic) NSString *textModeClickIndex; // @synthesize textModeClickIndex=_textModeClickIndex;
@property(retain, nonatomic) NSString *currentRequestRecommendVid; // @synthesize currentRequestRecommendVid=_currentRequestRecommendVid;
@property(copy, nonatomic) NSArray *recommendList; // @synthesize recommendList=_recommendList;
@property(retain, nonatomic) QNVideoRecommendModel *recommendModel; // @synthesize recommendModel=_recommendModel;
@property(nonatomic) _Bool isVideoPlayerControl; // @synthesize isVideoPlayerControl=_isVideoPlayerControl;
@property(retain, nonatomic) UIView *floatingClipView; // @synthesize floatingClipView=_floatingClipView;
@property(retain, nonatomic) QNDetailVideoFloatingView *videoFloatingView; // @synthesize videoFloatingView=_videoFloatingView;
@property(retain, nonatomic) NSMutableDictionary *videoReportStateDictionary; // @synthesize videoReportStateDictionary=_videoReportStateDictionary;
- (void).cxx_destruct;
- (void)enterVideoDetailWithListItem:(id)arg1 isRelatedVideo:(_Bool)arg2;
- (void)showRecommendViewWithNode:(id)arg1 view:(id)arg2;
- (void)requestRecommentListWithVideoInfo:(id)arg1;
- (void)p_onPlayerCountDown:(id)arg1;
- (void)p_didEnterFullScreenNotification:(id)arg1;
- (void)enterVideoDetailBtnClicked;
- (void)playerViewWillRemoved;
- (void)swipeGestureToTop;
- (void)closeBtnClickedOfFloatingView:(id)arg1;
- (void)p_hideVideoFloatingView;
- (void)p_hideVideoFloatingViewClose;
- (void)showVideoFloatingView;
- (void)onlyHideVideoFloatingView;
- (_Bool)containesCurrentPlayingVideo;
- (void)p_videoShowReportOnWebView;
- (void)p_videoActionDidScroll:(id)arg1 topAdjustedOffset:(double)arg2 bottomAdjustedOffset:(double)arg3;
- (void)configSmartVideoForReload;
- (void)onVideoDescClicked:(id)arg1;
- (struct CGRect)currentVideoFrame;
- (id)currentVideoKey;
- (void)enterVideoDetailWithPreFrame:(struct CGRect)arg1 videoNode:(id)arg2;
- (void)enterVideoAlbumWithPreFrame:(struct CGRect)arg1 videoNode:(id)arg2;
- (void)p_videoAlbumContinuePlay;
- (void)p_videoPlayButtonPressedDownWithNode:(id)arg1 view:(id)arg2;
- (void)_imageClickedInTextModeWithContentNode:(id)arg1;
- (void)_layoutImageWithView:(id)arg1 model:(id)arg2;
- (void)webViewCommonInit:(id)arg1;
- (void)webViewDidShow:(id)arg1;
- (void)containerScrollViewDidScroll:(id)arg1;
- (void)didComeInThisControllWithFromContorller:(id)arg1 changeType:(long long)arg2;
- (void)willComeInThisControllWithFromContorller:(id)arg1 changeType:(long long)arg2;
- (void)willLeaveThisControllWithToContorller:(id)arg1 changeType:(long long)arg2;
- (void)scrollViewWillPrepareComponentView:(id)arg1 componentModel:(id)arg2;
- (void)scrollViewRelayoutComponentView:(id)arg1 componentModel:(id)arg2;
- (void)controllerDidReceiveDataAndWillRenderHTML;
- (_Bool)shouldResponseWithComponentView:(id)arg1 componentModel:(id)arg2;
- (id)initWithDetailHandler:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

