//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KBTableViewCell.h"

@class QNAttributedLabel, QNDetailQAAllStandPointBottomBar, QNDetailQAAllStandPointModel, QNFollowListCellBaseInfoHeaderView, QNListMultiImagesUnit, QNListNewsItem, UIView;

@interface QNDetailQAAllStandPointCell : KBTableViewCell
{
    _Bool _qAExposured;
    QNListNewsItem *_listItem;
    id <QNWeiboCellActionDelegate> _actionDelegate;
    CDUnknownBlockType _declaredBtnBlock;
    CDUnknownBlockType _commentBtnBlock;
    CDUnknownBlockType _shareBtnBlock;
    CDUnknownBlockType _headTapGestBlock;
    QNFollowListCellBaseInfoHeaderView *_headerView;
    QNAttributedLabel *_titleLabel;
    QNAttributedLabel *_descLabel;
    QNListMultiImagesUnit *_multiImagesUnit;
    QNDetailQAAllStandPointBottomBar *_bottomBar;
    QNDetailQAAllStandPointModel *_allStandPointModel;
    UIView *_separatorLine;
}

@property(retain, nonatomic) UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(retain, nonatomic) QNDetailQAAllStandPointModel *allStandPointModel; // @synthesize allStandPointModel=_allStandPointModel;
@property(retain, nonatomic) QNDetailQAAllStandPointBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(retain, nonatomic) QNListMultiImagesUnit *multiImagesUnit; // @synthesize multiImagesUnit=_multiImagesUnit;
@property(retain, nonatomic) QNAttributedLabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) QNAttributedLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) QNFollowListCellBaseInfoHeaderView *headerView; // @synthesize headerView=_headerView;
@property(copy, nonatomic) CDUnknownBlockType headTapGestBlock; // @synthesize headTapGestBlock=_headTapGestBlock;
@property(copy, nonatomic) CDUnknownBlockType shareBtnBlock; // @synthesize shareBtnBlock=_shareBtnBlock;
@property(copy, nonatomic) CDUnknownBlockType commentBtnBlock; // @synthesize commentBtnBlock=_commentBtnBlock;
@property(copy, nonatomic) CDUnknownBlockType declaredBtnBlock; // @synthesize declaredBtnBlock=_declaredBtnBlock;
@property(nonatomic) __weak id <QNWeiboCellActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
@property(nonatomic) _Bool qAExposured; // @synthesize qAExposured=_qAExposured;
@property(retain, nonatomic) QNListNewsItem *listItem; // @synthesize listItem=_listItem;
- (void).cxx_destruct;
- (void)themeChanged:(long long)arg1;
- (id)p_imageBroswerItems;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)p_onClickDetailQAAllStandPointCell;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)layoutWithViewModel:(id)arg1 context:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

