//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBaseModelObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString;

@interface QNDetailViewTagItem : QNBaseModelObject <NSCopying, NSCoding>
{
    long long _tagType;
    NSString *_url;
    NSString *_nightUrl;
    NSString *_md5;
    NSString *_nightMd5;
    NSString *_type;
    NSString *_version;
    NSString *_filePath;
    NSString *_nightFilePath;
}

+ (id)build:(CDUnknownBlockType)arg1;
+ (_Bool)isImmutable;
+ (id)idStrWithTagType:(long long)arg1 type:(id)arg2;
+ (id)fullFilePathWithFileName:(id)arg1;
+ (id)fullFilePathWithTagType:(long long)arg1 type:(id)arg2 night:(_Bool)arg3;
+ (id)fileNameWithTagType:(long long)arg1 type:(id)arg2 night:(_Bool)arg3;
@property(copy, nonatomic) NSString *nightFilePath; // @synthesize nightFilePath=_nightFilePath;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *nightMd5; // @synthesize nightMd5=_nightMd5;
@property(copy, nonatomic) NSString *md5; // @synthesize md5=_md5;
@property(copy, nonatomic) NSString *nightUrl; // @synthesize nightUrl=_nightUrl;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) long long tagType; // @synthesize tagType=_tagType;
- (void).cxx_destruct;
- (id)copyInstance;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)checkCacheAllFiles;
- (id)urlPathForResource;
- (void)setCachedFilePath:(id)arg1 url:(id)arg2;
- (id)getUncachedFileUrl;
- (_Bool)p_cachedNightFile;
- (_Bool)p_cachedDayFile;
- (_Bool)hasUncachedFile;
- (id)description;
- (_Bool)isValid;
- (id)idStr;

@end

