//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAccountQACell.h"

@interface QNDetailAccountQACell : QNAccountQACell
{
}

+ (struct UIEdgeInsets)do_cellInsets;
+ (struct CGSize)do_imageSize;
- (void)layoutWithData:(id)arg1 context:(id)arg2;

@end

