//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, QNQualityCourseCommonTitleViewModel, UIColor, UIFont;

@interface QNDeDaoPlayListViewModel : NSObject
{
    UIColor *_bgColor;
    QNQualityCourseCommonTitleViewModel *_commonTitleViewModel;
    NSArray *_cellModels;
    UIColor *_bgViewBgColor;
    UIColor *_buttonTopLineColor;
    UIColor *_closeButtonTitleColor;
    UIFont *_closeButtonTitleFont;
    struct CGSize _viewSize;
    struct CGRect _bgViewRect;
    struct CGRect _titleViewRect;
    struct CGRect _tableViewRect;
    struct CGRect _buttonTopLineRect;
    struct CGRect _closeButtonRect;
}

@property(nonatomic) struct CGRect closeButtonRect; // @synthesize closeButtonRect=_closeButtonRect;
@property(retain, nonatomic) UIFont *closeButtonTitleFont; // @synthesize closeButtonTitleFont=_closeButtonTitleFont;
@property(retain, nonatomic) UIColor *closeButtonTitleColor; // @synthesize closeButtonTitleColor=_closeButtonTitleColor;
@property(retain, nonatomic) UIColor *buttonTopLineColor; // @synthesize buttonTopLineColor=_buttonTopLineColor;
@property(nonatomic) struct CGRect buttonTopLineRect; // @synthesize buttonTopLineRect=_buttonTopLineRect;
@property(nonatomic) struct CGRect tableViewRect; // @synthesize tableViewRect=_tableViewRect;
@property(nonatomic) struct CGRect titleViewRect; // @synthesize titleViewRect=_titleViewRect;
@property(retain, nonatomic) UIColor *bgViewBgColor; // @synthesize bgViewBgColor=_bgViewBgColor;
@property(nonatomic) struct CGRect bgViewRect; // @synthesize bgViewRect=_bgViewRect;
@property(copy, nonatomic) NSArray *cellModels; // @synthesize cellModels=_cellModels;
@property(retain, nonatomic) QNQualityCourseCommonTitleViewModel *commonTitleViewModel; // @synthesize commonTitleViewModel=_commonTitleViewModel;
@property(retain, nonatomic) UIColor *bgColor; // @synthesize bgColor=_bgColor;
@property(nonatomic) struct CGSize viewSize; // @synthesize viewSize=_viewSize;
- (void).cxx_destruct;
- (void)updateWithLesson:(id)arg1 status:(unsigned long long)arg2;
- (void)calculateWithCourseModel:(id)arg1;
- (id)cellModelAtIndex:(long long)arg1;
- (long long)numberOfRows;
- (id)init;

@end

