//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QNListCellModelProtocol.h"

@class KBTableViewCellLayoutContext, NSAttributedString, NSString, QNListFlagItem, UIColor, UIFont, UIImage;

@interface QNDeDaoCellModel : NSObject <QNListCellModelProtocol>
{
    id <QNListModelProtocol> _data;
    UIColor *_bgColor;
    NSAttributedString *_title;
    NSAttributedString *_desc;
    NSAttributedString *_countString;
    NSString *_coverUrl;
    UIImage *_placeholderImage;
    QNListFlagItem *_iconFlagItem;
    QNListFlagItem *_textFlagItem;
    UIFont *_textFlagFont;
    KBTableViewCellLayoutContext *_context;
    struct CGRect _rect;
    struct CGRect _titleRect;
    struct CGRect _iconFlagRect;
    struct CGRect _textFlagRect;
    struct CGRect _descRect;
    struct CGRect _countRect;
    struct CGRect _imageRect;
    struct CGRect _dislikeRect;
    struct CGRect _separatorRect;
}

@property(readonly, nonatomic) KBTableViewCellLayoutContext *context; // @synthesize context=_context;
@property(readonly, nonatomic) struct CGRect separatorRect; // @synthesize separatorRect=_separatorRect;
@property(readonly, nonatomic) struct CGRect dislikeRect; // @synthesize dislikeRect=_dislikeRect;
@property(readonly, nonatomic) struct CGRect imageRect; // @synthesize imageRect=_imageRect;
@property(readonly, nonatomic) struct CGRect countRect; // @synthesize countRect=_countRect;
@property(readonly, nonatomic) struct CGRect descRect; // @synthesize descRect=_descRect;
@property(readonly, nonatomic) struct CGRect textFlagRect; // @synthesize textFlagRect=_textFlagRect;
@property(readonly, nonatomic) struct CGRect iconFlagRect; // @synthesize iconFlagRect=_iconFlagRect;
@property(readonly, nonatomic) struct CGRect titleRect; // @synthesize titleRect=_titleRect;
@property(readonly, nonatomic) UIFont *textFlagFont; // @synthesize textFlagFont=_textFlagFont;
@property(readonly, nonatomic) QNListFlagItem *textFlagItem; // @synthesize textFlagItem=_textFlagItem;
@property(readonly, nonatomic) QNListFlagItem *iconFlagItem; // @synthesize iconFlagItem=_iconFlagItem;
@property(readonly, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(readonly, copy, nonatomic) NSString *coverUrl; // @synthesize coverUrl=_coverUrl;
@property(readonly, copy, nonatomic) NSAttributedString *countString; // @synthesize countString=_countString;
@property(readonly, copy, nonatomic) NSAttributedString *desc; // @synthesize desc=_desc;
@property(readonly, copy, nonatomic) NSAttributedString *title; // @synthesize title=_title;
@property(readonly, nonatomic) UIColor *bgColor; // @synthesize bgColor=_bgColor;
@property(readonly, nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(readonly, nonatomic) id <QNListModelProtocol> data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)calculateWithData:(id)arg1 referRect:(struct CGRect)arg2 context:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

