//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CAAnimationDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSString, QNArticleContentNodeTagLinkNode, QNBaseLabel, QNDetailTagWebView, QNListNewsItem, UIButton, UIPanGestureRecognizer;

@interface QNDetailTagPageView : UIView <CAAnimationDelegate, UIGestureRecognizerDelegate>
{
    _Bool _isFullScreenType;
    float _halfScreenHeight;
    id <QNDetailTagPageViewDelegate> _delegate;
    QNDetailTagWebView *_webView;
    QNArticleContentNodeTagLinkNode *_linkNode;
    QNListNewsItem *_listItem;
    UIView *_containerView;
    QNBaseLabel *_tagNamelabel;
    QNBaseLabel *_rankinglabel;
    UIButton *_closeButton;
    UIButton *_footerButton;
    UIView *_topView;
    UIPanGestureRecognizer *_panGesture;
    struct CGPoint _touchBeginPoint;
    struct CGPoint _touchEndPoint;
    struct CGPoint _touchMovePoint;
}

@property(retain, nonatomic) UIPanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
@property(nonatomic) _Bool isFullScreenType; // @synthesize isFullScreenType=_isFullScreenType;
@property(nonatomic) float halfScreenHeight; // @synthesize halfScreenHeight=_halfScreenHeight;
@property(nonatomic) struct CGPoint touchMovePoint; // @synthesize touchMovePoint=_touchMovePoint;
@property(nonatomic) struct CGPoint touchEndPoint; // @synthesize touchEndPoint=_touchEndPoint;
@property(nonatomic) struct CGPoint touchBeginPoint; // @synthesize touchBeginPoint=_touchBeginPoint;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UIButton *footerButton; // @synthesize footerButton=_footerButton;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) QNBaseLabel *rankinglabel; // @synthesize rankinglabel=_rankinglabel;
@property(retain, nonatomic) QNBaseLabel *tagNamelabel; // @synthesize tagNamelabel=_tagNamelabel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) QNListNewsItem *listItem; // @synthesize listItem=_listItem;
@property(retain, nonatomic) QNArticleContentNodeTagLinkNode *linkNode; // @synthesize linkNode=_linkNode;
@property(retain, nonatomic) QNDetailTagWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) __weak id <QNDetailTagPageViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)panGestureChanged:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)animationDidStart:(id)arg1;
- (void)footerButtonPressed:(id)arg1;
- (void)closeButtonPressed:(id)arg1;
- (void)p_updateRankingLabelWithText:(id)arg1;
- (void)p_reloadWebView;
- (float)p_topViewHeight;
- (id)p_getPositionAnimationWithStartPoint:(struct CGPoint)arg1 endPoint:(struct CGPoint)arg2 controlPoint_1:(struct CGPoint)arg3 controlPoint_2:(struct CGPoint)arg4 animationName:(id)arg5 duration:(double)arg6;
- (void)p_doCloseAnimation;
- (void)p_doFullScreenAnimation;
- (void)p_doShowAnimation;
- (void)p_transformToFullScreen;
- (void)showInView:(id)arg1 viewHeight:(float)arg2;
- (void)layoutSubviews;
- (id)initWithLinkNode:(id)arg1 listItem:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

