//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableCollectionViewCell.h"

#import "QNExclusiveListCellProtocol.h"

@class CAShapeLayer, NSString, QNAttributedLabel, QNCommonGIFImageView, QNListNewsItem, UIButton, UIImageView, UILabel;

@interface QNExclusiveListCell : QNThemableCollectionViewCell <QNExclusiveListCellProtocol>
{
    id <QNExclusiveListCellActionDelegate> _actionDelegate;
    NSString *_currentChannelId;
    QNCommonGIFImageView *_coverImageView;
    UIImageView *_avatarImageView;
    UIImageView *_liveIconImageView;
    QNAttributedLabel *_titleLabel;
    UILabel *_descriptionLabel;
    UIButton *_playButton;
    QNListNewsItem *_listItem;
    CAShapeLayer *_maskLayer;
    UILabel *_commentLabel;
}

+ (id)getTitleLabelText:(id)arg1;
+ (double)heightWithData:(id)arg1 type:(long long)arg2 width:(double)arg3;
+ (double)height;
+ (id)identifier;
@property(retain, nonatomic) UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) CAShapeLayer *maskLayer; // @synthesize maskLayer=_maskLayer;
@property(retain, nonatomic) QNListNewsItem *listItem; // @synthesize listItem=_listItem;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) QNAttributedLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *liveIconImageView; // @synthesize liveIconImageView=_liveIconImageView;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) QNCommonGIFImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
@property(copy, nonatomic) NSString *currentChannelId; // @synthesize currentChannelId=_currentChannelId;
@property(nonatomic) __weak id <QNExclusiveListCellActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (void).cxx_destruct;
- (void)p_setTitleLabelText:(id)arg1;
- (void)layoutWithData:(id)arg1;
- (void)themeChanged:(long long)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

