//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class CAGradientLayer, QNSubscribeButton, UIImageView, UILabel;

@interface QNExclusiveColumnCollectionViewCell : UICollectionViewCell
{
    UIImageView *_coverImageView;
    UILabel *_titleLabel;
    UILabel *_descriptionLabel;
    QNSubscribeButton *_attentionBtn;
    CAGradientLayer *_coverImageGradientLayer;
}

+ (double)height;
+ (id)identifier;
@property(retain, nonatomic) CAGradientLayer *coverImageGradientLayer; // @synthesize coverImageGradientLayer=_coverImageGradientLayer;
@property(retain, nonatomic) QNSubscribeButton *attentionBtn; // @synthesize attentionBtn=_attentionBtn;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
- (void).cxx_destruct;
- (void)p_updateDescriptionLabelText:(id)arg1;
- (void)layoutWithData:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

