//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface QNFavoriteStateResult : NSObject
{
    NSString *_idStr;
    NSString *_srcId;
    long long _ret;
}

@property(nonatomic) long long ret; // @synthesize ret=_ret;
@property(copy, nonatomic) NSString *srcId; // @synthesize srcId=_srcId;
@property(copy, nonatomic) NSString *idStr; // @synthesize idStr=_idStr;
- (void).cxx_destruct;
- (_Bool)isValid;

@end

