//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class UIImageView, UIView;

@interface QNFakeNewsMenuView : QNThemableView
{
    id <QNFakeNewsMenuViewProtocol> _delegate;
    UIImageView *_searchImgView;
    UIImageView *_searchAnimationImgView;
    UIImageView *_settingImgView;
    UIImageView *_closeImgView;
    UIView *_backView;
    UIImageView *_rightShadowView;
    double _searchImgLeft;
}

@property(nonatomic) double searchImgLeft; // @synthesize searchImgLeft=_searchImgLeft;
@property(retain, nonatomic) UIImageView *rightShadowView; // @synthesize rightShadowView=_rightShadowView;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) UIImageView *closeImgView; // @synthesize closeImgView=_closeImgView;
@property(retain, nonatomic) UIImageView *settingImgView; // @synthesize settingImgView=_settingImgView;
@property(retain, nonatomic) UIImageView *searchAnimationImgView; // @synthesize searchAnimationImgView=_searchAnimationImgView;
@property(retain, nonatomic) UIImageView *searchImgView; // @synthesize searchImgView=_searchImgView;
@property(nonatomic) __weak id <QNFakeNewsMenuViewProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)p_setBarSkinStyle;
- (void)p_initBarSkinStyle;
- (void)setSearchViewHiden:(_Bool)arg1;
- (void)setSlideAnimationWithProcess:(double)arg1;
- (void)_changeFakeNewsMenuStyle;
- (double)_getSearchImageOringX;
- (void)themeChanged:(long long)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

