//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary;

@interface QNFavoriteListIndexAndItemsResponse : NSObject
{
    _Bool _noMoreData;
    long long _limitIndexCount;
    NSArray *_indexList;
    NSArray *_listItems;
    NSDictionary *_commentCountDict;
    NSArray *_lostItemIds;
}

@property(nonatomic) _Bool noMoreData; // @synthesize noMoreData=_noMoreData;
@property(copy, nonatomic) NSArray *lostItemIds; // @synthesize lostItemIds=_lostItemIds;
@property(copy, nonatomic) NSDictionary *commentCountDict; // @synthesize commentCountDict=_commentCountDict;
@property(copy, nonatomic) NSArray *listItems; // @synthesize listItems=_listItems;
@property(copy, nonatomic) NSArray *indexList; // @synthesize indexList=_indexList;
@property(nonatomic) long long limitIndexCount; // @synthesize limitIndexCount=_limitIndexCount;
- (void).cxx_destruct;

@end

