//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class QNBaseLabel, UIButton;

@interface QNFollowCellDeclareView : QNThemableView
{
    UIButton *_declareButton;
    QNBaseLabel *_countLabel;
    long long _currentPageType;
}

@property(nonatomic) long long currentPageType; // @synthesize currentPageType=_currentPageType;
@property(retain, nonatomic) QNBaseLabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UIButton *declareButton; // @synthesize declareButton=_declareButton;
- (void).cxx_destruct;
- (void)themeChanged:(long long)arg1;
- (void)p_doPlus1Animation;
- (void)p_doDislikeAnimation;
- (void)p_doLikeAnimation;
- (void)layoutDeclaredViewWithNum:(id)arg1 hasSupported:(_Bool)arg2 clicked:(_Bool)arg3;
- (void)layoutDeclaredViewWithNum:(id)arg1 hasSupported:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1 withPageType:(long long)arg2;

@end

