//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QNReverseGeocoderDelegate.h"

@class CLGeocoder, NSString, QNReverseGeocoder;

@interface QNGeocoder : NSObject <QNReverseGeocoderDelegate>
{
    QNReverseGeocoder *_qnGeocoder;
    CLGeocoder *_clGeocoder;
    long long _status;
    CDUnknownBlockType _completionHandler;
    long long _source;
    struct CLLocationCoordinate2D _coordinate;
}

@property(nonatomic) long long source; // @synthesize source=_source;
@property(nonatomic) struct CLLocationCoordinate2D coordinate; // @synthesize coordinate=_coordinate;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void).cxx_destruct;
- (void)p_invokeComplationHandlerWith:(id)arg1 error:(id)arg2;
- (void)p_startCLGeocoder;
- (void)p_startQnGeocoder;
- (void)p_hasTimeout;
- (void)p_startTimeoutDetection;
- (void)reverseGeocoder:(id)arg1 didFailWithError:(unsigned long long)arg2;
- (void)reverseGeocoder:(id)arg1 didFindPlacemark:(id)arg2;
- (void)cancel;
- (void)reverseGeocodeCoordinate:(struct CLLocationCoordinate2D)arg1 source:(long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)isGeocoding;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

