//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class UIColor;

@interface QNGlowLabel : UILabel
{
    UIColor *_glowColor;
}

@property(retain, nonatomic) UIColor *glowColor; // @synthesize glowColor=_glowColor;
- (void).cxx_destruct;
- (id)initWithGlowColor:(id)arg1;

@end

