//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

#import "QNDetailContentElementProtocol.h"

@class NSString, QNAnswerImagesView, QNDetailContentContainer;

@interface QNGridImagesView : QNThemableView <QNDetailContentElementProtocol>
{
    QNAnswerImagesView *_imagesView;
    QNDetailContentContainer *_contentContainer;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) __weak QNDetailContentContainer *contentContainer; // @synthesize contentContainer=_contentContainer;
@property(retain, nonatomic) QNAnswerImagesView *imagesView; // @synthesize imagesView=_imagesView;
- (void).cxx_destruct;
- (double)heightOfElementView;
- (void)resetAllImage;
- (void)reloadWithImageBrowserItems:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

