//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAbstractLevelDBDataStore.h"

@interface QNHelperDataStore : QNAbstractLevelDBDataStore
{
}

+ (id)nameOfDB;
- (id)channelGuideItem:(id)arg1;
- (void)saveChannelGuideItem:(id)arg1;
- (id)_keyForChannelGuideItem:(id)arg1;

@end

