//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAbstractModelBuilder.h"

@interface QNHolidayGiftEggItemBuilder : QNAbstractModelBuilder
{
}

+ (id)builderWithModelCopy:(id)arg1;
+ (id)builder;
+ (id)fromDictionary:(id)arg1;
- (id)setNotLoginImageLoader:(id)arg1;
- (id)notLoginImageLoader;
- (id)setNotLoginImageTryCount:(long long)arg1;
- (long long)notLoginImageTryCount;
- (id)setLoader:(id)arg1;
- (id)loader;
- (id)setTryCount:(long long)arg1;
- (long long)tryCount;
- (id)setShareInfo:(id)arg1;
- (id)shareInfo;
- (id)setDuration:(double)arg1;
- (double)duration;
- (id)setWording:(id)arg1;
- (id)wording;
- (id)setTextType:(long long)arg1;
- (long long)textType;
- (id)setNeedAddClientInfo:(_Bool)arg1;
- (_Bool)needAddClientInfo;
- (id)setNeedCacheWebView:(_Bool)arg1;
- (_Bool)needCacheWebView;
- (id)setLoginType:(id)arg1;
- (id)loginType;
- (id)setNotLoginImage:(id)arg1;
- (id)notLoginImage;
- (id)setNotLoginImageMd5:(id)arg1;
- (id)notLoginImageMd5;
- (id)setNotLoginImageUrl:(id)arg1;
- (id)notLoginImageUrl;
- (id)setLinkUrl:(id)arg1;
- (id)linkUrl;
- (id)setImageScale:(double)arg1;
- (double)imageScale;
- (id)setImage:(id)arg1;
- (id)image;
- (id)setEndTime:(double)arg1;
- (double)endTime;
- (id)setStartTime:(double)arg1;
- (double)startTime;
- (id)setScaleWidth:(double)arg1;
- (double)scaleWidth;
- (id)setCount:(unsigned long long)arg1;
- (unsigned long long)count;
- (id)setFullMd5:(id)arg1;
- (id)fullMd5;
- (id)setFull:(id)arg1;
- (id)full;
- (id)build;
- (id)do_createModelObject;
- (id)initWithModelCopy:(id)arg1;
- (id)init;
- (id)initWithDictionaryStub:(id)arg1;
- (void)do_customMapping:(id)arg1;

@end

