//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, QNGetHotTopicListApi, QNHotTopicListData, QNListNewsItem, UIColor;

@interface QNHotTopicListViewModel : NSObject
{
    _Bool _isSelectedTopicList;
    QNListNewsItem *_listItem;
    UIColor *_headerColor;
    CDUnknownBlockType _finishedBlock;
    QNHotTopicListData *_listData;
    NSMutableArray *_topicArray;
    QNGetHotTopicListApi *_api;
}

@property(retain, nonatomic) QNGetHotTopicListApi *api; // @synthesize api=_api;
@property(retain, nonatomic) NSMutableArray *topicArray; // @synthesize topicArray=_topicArray;
@property(retain, nonatomic) QNHotTopicListData *listData; // @synthesize listData=_listData;
@property(nonatomic) _Bool isSelectedTopicList; // @synthesize isSelectedTopicList=_isSelectedTopicList;
@property(copy, nonatomic) CDUnknownBlockType finishedBlock; // @synthesize finishedBlock=_finishedBlock;
@property(retain, nonatomic) UIColor *headerColor; // @synthesize headerColor=_headerColor;
@property(retain, nonatomic) QNListNewsItem *listItem; // @synthesize listItem=_listItem;
- (void).cxx_destruct;
- (void)cancelAllRequest;
- (void)loadDataWithType:(long long)arg1;
- (id)topicItemAtIndex:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)numberOfRowsInSection:(long long)arg1;
- (long long)numberOfSections;
- (_Bool)hasValidData;
- (id)init;

@end

