//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class NSMutableArray, QNHotEventSpecialNewsFocusView, QNHotEventSpecialNewsFooterView, QNHotEventSpecialNewsNormalView, QNListModuleItem, QNReportParam, UIImageView, UIScrollView;

@interface QNHotEventSpecialNewsBackgroundView : QNThemableView
{
    _Bool _didAddScrollObserver;
    CDUnknownBlockType _focusClickBlock;
    CDUnknownBlockType _normalClickBlock;
    CDUnknownBlockType _footerClickBlock;
    QNReportParam *_reportParam;
    QNListModuleItem *_moduleItem;
    QNHotEventSpecialNewsFocusView *_focusView;
    QNHotEventSpecialNewsNormalView *_normalView1;
    QNHotEventSpecialNewsNormalView *_normalView2;
    QNHotEventSpecialNewsFooterView *_footerView;
    UIImageView *_bottomLine;
    NSMutableArray *_exposuredNews;
    UIScrollView *_observerdScrollView;
}

+ (double)viewHeight:(id)arg1 context:(id)arg2;
@property(nonatomic) _Bool didAddScrollObserver; // @synthesize didAddScrollObserver=_didAddScrollObserver;
@property(nonatomic) __weak UIScrollView *observerdScrollView; // @synthesize observerdScrollView=_observerdScrollView;
@property(retain, nonatomic) NSMutableArray *exposuredNews; // @synthesize exposuredNews=_exposuredNews;
@property(retain, nonatomic) UIImageView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) QNHotEventSpecialNewsFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) QNHotEventSpecialNewsNormalView *normalView2; // @synthesize normalView2=_normalView2;
@property(retain, nonatomic) QNHotEventSpecialNewsNormalView *normalView1; // @synthesize normalView1=_normalView1;
@property(retain, nonatomic) QNHotEventSpecialNewsFocusView *focusView; // @synthesize focusView=_focusView;
@property(retain, nonatomic) QNListModuleItem *moduleItem; // @synthesize moduleItem=_moduleItem;
@property(retain, nonatomic) QNReportParam *reportParam; // @synthesize reportParam=_reportParam;
@property(copy, nonatomic) CDUnknownBlockType footerClickBlock; // @synthesize footerClickBlock=_footerClickBlock;
@property(copy, nonatomic) CDUnknownBlockType normalClickBlock; // @synthesize normalClickBlock=_normalClickBlock;
@property(copy, nonatomic) CDUnknownBlockType focusClickBlock; // @synthesize focusClickBlock=_focusClickBlock;
- (void).cxx_destruct;
- (void)layoutWithData:(id)arg1 context:(id)arg2;
- (void)themeChanged:(long long)arg1;
- (void)p_addScrollViewObserver:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

