//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class CSimpleImageView, QNAttributedLabel, QNBaseLabel, QNFlagTextView, QNListNewsItem, UIImageView, UITapGestureRecognizer;

@interface QNHotEventSpecialNewsFocusView : QNThemableView
{
    CDUnknownBlockType _focusClickBlock;
    CSimpleImageView *_moduleIconImageView;
    QNBaseLabel *_moduleTitleLbl;
    CSimpleImageView *_simpleImageView;
    UIImageView *_imageBlackCoverView;
    UIImageView *_specialTypeFlagView;
    QNAttributedLabel *_titleLbl;
    QNAttributedLabel *_descLbl;
    QNAttributedLabel *_authorLbl;
    QNFlagTextView *_flagView;
    UITapGestureRecognizer *_tapGestureRecognizer;
    QNListNewsItem *_listItem;
}

+ (id)p_titleAttributedString:(id)arg1;
+ (id)p_attributedStringWithString:(id)arg1 icon:(id)arg2;
+ (double)viewHeight;
+ (struct CGSize)imageSize;
@property(retain, nonatomic) QNListNewsItem *listItem; // @synthesize listItem=_listItem;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) QNFlagTextView *flagView; // @synthesize flagView=_flagView;
@property(retain, nonatomic) QNAttributedLabel *authorLbl; // @synthesize authorLbl=_authorLbl;
@property(retain, nonatomic) QNAttributedLabel *descLbl; // @synthesize descLbl=_descLbl;
@property(retain, nonatomic) QNAttributedLabel *titleLbl; // @synthesize titleLbl=_titleLbl;
@property(retain, nonatomic) UIImageView *specialTypeFlagView; // @synthesize specialTypeFlagView=_specialTypeFlagView;
@property(retain, nonatomic) UIImageView *imageBlackCoverView; // @synthesize imageBlackCoverView=_imageBlackCoverView;
@property(retain, nonatomic) CSimpleImageView *simpleImageView; // @synthesize simpleImageView=_simpleImageView;
@property(retain, nonatomic) QNBaseLabel *moduleTitleLbl; // @synthesize moduleTitleLbl=_moduleTitleLbl;
@property(retain, nonatomic) CSimpleImageView *moduleIconImageView; // @synthesize moduleIconImageView=_moduleIconImageView;
@property(copy, nonatomic) CDUnknownBlockType focusClickBlock; // @synthesize focusClickBlock=_focusClickBlock;
- (void).cxx_destruct;
- (void)themeChanged:(long long)arg1;
- (void)p_updateDescWithListItem:(id)arg1 configItem:(id)arg2;
- (void)p_tapFocusView;
- (void)layoutWithModuleItem:(id)arg1 andListItem:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

