//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class QNEnlargeHitTestButton;

@interface QNHotEventSpecialNewsFooterView : QNThemableView
{
    CDUnknownBlockType _footerClickBlock;
    QNEnlargeHitTestButton *_openBtn;
}

+ (double)viewHeight;
@property(retain, nonatomic) QNEnlargeHitTestButton *openBtn; // @synthesize openBtn=_openBtn;
@property(copy, nonatomic) CDUnknownBlockType footerClickBlock; // @synthesize footerClickBlock=_footerClickBlock;
- (void).cxx_destruct;
- (void)p_openBtnClick;
- (void)themeChanged:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

