//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNRootViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSMutableArray, NSString, QNAssetSelectButton, QNImagePreviewBottomBar, QNMediaPickerControllerParam, UICollectionView;

@interface QNImagePreviewViewController : QNRootViewController <UIScrollViewDelegate, UICollectionViewDelegate, UICollectionViewDataSource, UIGestureRecognizerDelegate>
{
    _Bool _isBrowserHidden;
    NSArray *_models;
    NSMutableArray *_selectedModels;
    long long _currentIndex;
    CDUnknownBlockType _previewAssetSelectChangeBlock;
    CDUnknownBlockType _previewCompletionButtonClickBlock;
    UICollectionView *_collectionView;
    QNImagePreviewBottomBar *_bottomBar;
    QNAssetSelectButton *_selectButton;
    QNMediaPickerControllerParam *_mediaPickerParam;
    unsigned long long _pageType;
    unsigned long long _panGestureRecognizerSwipeDirection;
    double _containerViewOriginalXPosition;
    double _containerViewOriginalYPosition;
}

@property(nonatomic) double containerViewOriginalYPosition; // @synthesize containerViewOriginalYPosition=_containerViewOriginalYPosition;
@property(nonatomic) double containerViewOriginalXPosition; // @synthesize containerViewOriginalXPosition=_containerViewOriginalXPosition;
@property(nonatomic) unsigned long long panGestureRecognizerSwipeDirection; // @synthesize panGestureRecognizerSwipeDirection=_panGestureRecognizerSwipeDirection;
@property(nonatomic) _Bool isBrowserHidden; // @synthesize isBrowserHidden=_isBrowserHidden;
@property(nonatomic) unsigned long long pageType; // @synthesize pageType=_pageType;
@property(retain, nonatomic) QNMediaPickerControllerParam *mediaPickerParam; // @synthesize mediaPickerParam=_mediaPickerParam;
@property(retain, nonatomic) QNAssetSelectButton *selectButton; // @synthesize selectButton=_selectButton;
@property(retain, nonatomic) QNImagePreviewBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(copy, nonatomic) CDUnknownBlockType previewCompletionButtonClickBlock; // @synthesize previewCompletionButtonClickBlock=_previewCompletionButtonClickBlock;
@property(copy, nonatomic) CDUnknownBlockType previewAssetSelectChangeBlock; // @synthesize previewAssetSelectChangeBlock=_previewAssetSelectChangeBlock;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) NSMutableArray *selectedModels; // @synthesize selectedModels=_selectedModels;
@property(copy, nonatomic) NSArray *models; // @synthesize models=_models;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)p_getAnimationBackgroundColorWithAlphaComponent:(double)arg1;
- (void)p_updateBarComponentColorWithAlphaComponent:(double)arg1;
- (void)p_handlePanGesture:(id)arg1;
- (void)p_buildUserPanGestureAction;
- (void)p_buildGestures;
- (void)p_configViewSetting;
- (void)p_showElasticAnimation;
- (void)onAction:(id)arg1;
- (void)onBack:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)p_refreshSelectButtonUI;
- (void)scrollViewDidScroll:(id)arg1;
- (void)configBarButtons;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithMediaPickerParam:(id)arg1 entrancePageType:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

