//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QNIpDirectConnectionHelper : NSObject
{
}

+ (void)qn_reportIpDirectConnectionResult:(id)arg1 result:(_Bool)arg2 withIpAddress:(id)arg3 cost:(double)arg4 userInfo:(id)arg5 error:(id)arg6 responseStatusCode:(long long)arg7;
+ (id)qn_convertToIpDirectConnectionURL:(id)arg1 userInfo:(id)arg2;

@end

