//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CUIScrollView.h"

#import "CUIScrollViewSubClassProtocol.h"

@class NSString, QNPageView;

@interface QNListScrollView : CUIScrollView <CUIScrollViewSubClassProtocol>
{
    long long _tabType;
    QNPageView *_pageView;
}

@property(nonatomic) __weak QNPageView *pageView; // @synthesize pageView=_pageView;
@property(nonatomic) long long tabType; // @synthesize tabType=_tabType;
- (void).cxx_destruct;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)viewsToDisableCancel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

