//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNPlayerControlViewMutePlayNormalBase.h"

#import "QNTVKProgressControlDelegate.h"

@class NSString, QNAttributedLabel, QNFlagImageView, QNListLiveVideoDanmakuContentView, QNListVideoDescContentView, QNVolumeAndTimeView, UIView;

@interface QNListLiveVideoDanmakuCoverView : QNPlayerControlViewMutePlayNormalBase <QNTVKProgressControlDelegate>
{
    _Bool _showVolumeAndDuration;
    QNFlagImageView *_flagView;
    UIView *_textContentView;
    QNAttributedLabel *_titleLbl;
    QNListVideoDescContentView *_descView;
    QNListLiveVideoDanmakuContentView *_danmakuContentView;
    UIView *_maskImageView;
    double _hideTitleBeginTime;
    NSString *_durationStr;
    QNVolumeAndTimeView *_volumeView;
}

@property(retain, nonatomic) QNVolumeAndTimeView *volumeView; // @synthesize volumeView=_volumeView;
@property(nonatomic) _Bool showVolumeAndDuration; // @synthesize showVolumeAndDuration=_showVolumeAndDuration;
@property(copy, nonatomic) NSString *durationStr; // @synthesize durationStr=_durationStr;
@property(nonatomic) double hideTitleBeginTime; // @synthesize hideTitleBeginTime=_hideTitleBeginTime;
@property(retain, nonatomic) UIView *maskImageView; // @synthesize maskImageView=_maskImageView;
@property(retain, nonatomic) QNListLiveVideoDanmakuContentView *danmakuContentView; // @synthesize danmakuContentView=_danmakuContentView;
@property(retain, nonatomic) QNListVideoDescContentView *descView; // @synthesize descView=_descView;
@property(retain, nonatomic) QNAttributedLabel *titleLbl; // @synthesize titleLbl=_titleLbl;
@property(retain, nonatomic) UIView *textContentView; // @synthesize textContentView=_textContentView;
@property(retain, nonatomic) QNFlagImageView *flagView; // @synthesize flagView=_flagView;
- (void).cxx_destruct;
- (void)willLeave;
- (void)willShow;
- (void)hideControls;
- (void)showControls;
- (void)_updateDurationView;
- (void)updateProgress:(double)arg1 bufferTime:(double)arg2 duration:(double)arg3;
- (void)hideDanamaku;
- (void)showDanmakuAndVolumeWithMessage:(id)arg1;
- (void)updateSubViewsWithListItem:(id)arg1;
- (void)p_hideTitleView;
- (void)p_hideTitleAndShowVolume;
- (void)p_showDanmakuAndVolumeWithMessage:(id)arg1;
- (id)p_titleAttrString:(id)arg1;
- (void)_setupTextContentView;
- (void)_setupMaskView;
- (void)layoutSubviews;
- (void)dealloc;
- (void)tryShowDanmaku;
- (void)createSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

