//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNListUnitModelProtocol.h"

@class NSAttributedString, NSURL, QNImageProcessConfig, UIImage;

@protocol QNListUserInfoUnitModel <QNListUnitModelProtocol>
@property(readonly, nonatomic) QNImageProcessConfig *avatarProcessConfig;
@property(readonly, nonatomic) struct CGRect descRect;
@property(readonly, nonatomic) struct CGRect nameRect;
@property(readonly, copy, nonatomic) NSAttributedString *descString;
@property(readonly, copy, nonatomic) NSAttributedString *nameString;
@property(readonly, nonatomic) struct CGRect flagRect;
@property(readonly, nonatomic) struct CGSize flagSize;
@property(readonly, nonatomic) NSURL *flagIconUrl;
@property(readonly, nonatomic) UIImage *defaultAvatar;
@property(readonly, nonatomic) struct CGRect avatarRect;
@property(readonly, nonatomic) _Bool vipPlaceRight;
@property(readonly, nonatomic) NSURL *avatarUrl;

@optional
@property(readonly, nonatomic) double flagOffset;
@end

