//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBasicListViewModel.h"

#import "KBListModelDelegate.h"
#import "QNBasicListViewModelSubclassProtocol.h"

@class NSString;

@interface QNLikeVideoListModelPortrait : QNBasicListViewModel <QNBasicListViewModelSubclassProtocol, KBListModelDelegate>
{
}

- (void)listModel:(id)arg1 didDeleteItemsAtIndexes:(id)arg2;
- (void)listModel:(id)arg1 didInsertItemsAtIndexes:(id)arg2;
- (void)listModeldidReplaceAllItems:(id)arg1 animated:(_Bool)arg2;
- (id)loaderContextForPullupToRefresh;
- (id)loaderContextForPulldownToRefresh;
- (id)loaderContextForRefreshAll;
- (void)addListItems:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

