//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QNListModuleItem, QNPlayerManager, QNRootViewController, UIScrollView;

@interface QNListVideoAssistor : NSObject
{
    _Bool _closingScheduled;
    QNRootViewController *_viewController;
    id <QNListVideoAssistorDelegate> _delegate;
    unsigned long long _playVideoTypeOptions;
    QNListModuleItem *_moduleItem;
    double _attachViewShowPercentForPlay;
    double _attachViewDismissPercentForStop;
    long long _currentStrategy;
    QNPlayerManager *_playerManager;
    UIScrollView *_listView;
}

@property(nonatomic) __weak UIScrollView *listView; // @synthesize listView=_listView;
@property(nonatomic) __weak QNPlayerManager *playerManager; // @synthesize playerManager=_playerManager;
@property(nonatomic) long long currentStrategy; // @synthesize currentStrategy=_currentStrategy;
@property(nonatomic) double attachViewDismissPercentForStop; // @synthesize attachViewDismissPercentForStop=_attachViewDismissPercentForStop;
@property(nonatomic) double attachViewShowPercentForPlay; // @synthesize attachViewShowPercentForPlay=_attachViewShowPercentForPlay;
@property(retain, nonatomic) QNListModuleItem *moduleItem; // @synthesize moduleItem=_moduleItem;
@property(nonatomic) unsigned long long playVideoTypeOptions; // @synthesize playVideoTypeOptions=_playVideoTypeOptions;
@property(nonatomic) __weak id <QNListVideoAssistorDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) __weak QNRootViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (id)p_getCurrentControllerFromContainer:(id)arg1;
- (id)p_getControllerWithrootViewController;
- (void)_handleRemoteConfigRequestFinished;
- (id)getSubParamsSelectIndexPath:(id)arg1 cellShowType:(long long)arg2;
- (void)p_playVideoForMutiVideoCellWithListItem:(id)arg1 inCell:(id)arg2;
- (void)p_playMutiVideoCellVideoWithVideoInfo:(id)arg1 listItem:(id)arg2 inCell:(id)arg3;
- (_Bool)p_canPlayWithListItem:(id)arg1;
- (id)p_getRealVideoViewForPlayer:(id)arg1;
- (id)p_getVideoViewForPlayer:(id)arg1;
- (double)_topInMyNaviViewWithCell:(id)arg1;
- (struct CGRect)_listVisibleRect;
- (id)p_getPlayCellForAbstractController;
- (struct CGRect)p_getListVisibleRect;
- (id)p_getVideoCellInfoWithIdStr:(id)arg1 inList:(id)arg2;
- (id)p_getPlayCellForOtherController;
- (_Bool)_isNowPlayingCell:(id)arg1 withListItem:(id)arg2;
- (id)_getPlayCell;
- (id)p_getPlayingVideoCellFromScroll:(_Bool)arg1;
- (void)_playCurrentVideo;
- (_Bool)_canAttachPlayInCell:(id)arg1;
- (id)p_cellAtIndexPath:(id)arg1;
- (id)_listViewVisibleCells;
- (_Bool)isCenterPlayView:(id)arg1;
- (id)visibleCellToAddPlayerByListItem:(id)arg1;
- (void)cancelPlayVideo;
- (void)afterDelayPlayWithVisiableChanelID:(id)arg1;
- (_Bool)checkPlayerHaveOwner;
- (void)reAttachePlayerView;
- (void)handlePlayerTypeChange:(_Bool)arg1 videoIndexPath:(id)arg2;
- (void)handlePlayerTypeChange:(_Bool)arg1 withDataList:(id)arg2;
- (id)p_controlViewClassWithCell:(id)arg1 listItem:(id)arg2;
- (_Bool)forcePlayVideoWithListItem:(id)arg1 inCell:(id)arg2 isAutoPlay:(_Bool)arg3 isContinue:(_Bool)arg4 isSupprotDoubleTopPrais:(_Bool)arg5 muteType:(unsigned long long)arg6 lockRotation:(_Bool)arg7 finishBlock:(CDUnknownBlockType)arg8;
- (void)playVideoWithListItem:(id)arg1 inCell:(id)arg2;
- (void)dealloc;
- (id)init;
- (void)resetStrategy;
- (id)initWithController:(id)arg1 listView:(id)arg2 delegate:(id)arg3;

@end

