//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableTableViewCell.h"

@class CSubMenuItem, UIImageView, UILabel, UIView;

@interface QNLocalChannelSwitchCell : QNThemableTableViewCell
{
    CSubMenuItem *_data;
    unsigned long long _cellType;
    UIImageView *_remindIcoView;
    UILabel *_label;
    CSubMenuItem *_dataItem;
    UIView *_bottomLine;
    UIImageView *_addedIconView;
    UILabel *_addedDescLable;
}

+ (double)getLocalChannelCellHeight;
+ (id)getReusableCellId;
@property(retain, nonatomic) UILabel *addedDescLable; // @synthesize addedDescLable=_addedDescLable;
@property(retain, nonatomic) UIImageView *addedIconView; // @synthesize addedIconView=_addedIconView;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) CSubMenuItem *dataItem; // @synthesize dataItem=_dataItem;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImageView *remindIcoView; // @synthesize remindIcoView=_remindIcoView;
@property(nonatomic) unsigned long long cellType; // @synthesize cellType=_cellType;
@property(retain, nonatomic) CSubMenuItem *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)themeChanged:(long long)arg1;
- (void)layoutChannelCellWithItem:(id)arg1 isAdded:(_Bool)arg2 isLast:(_Bool)arg3;
- (void)layoutChannelCellWithItem:(id)arg1 isAdded:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

