//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNRootViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CSubMenuItem, NSArray, NSIndexPath, NSMutableSet, NSString, UITableView;

@interface QNLocalChannelSwitchViewController : QNRootViewController <UITableViewDelegate, UITableViewDataSource>
{
    NSString *_switchSourceLocalChannelID;
    CSubMenuItem *_switchSourceSubMenuItem;
    CDUnknownBlockType _channelSwitchBlock;
    UITableView *_tableView;
    NSIndexPath *_selectedIndexPath;
    NSArray *_cellDataList;
    NSMutableSet *_selectListOfLocal;
}

@property(retain, nonatomic) NSMutableSet *selectListOfLocal; // @synthesize selectListOfLocal=_selectListOfLocal;
@property(retain, nonatomic) NSArray *cellDataList; // @synthesize cellDataList=_cellDataList;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) CDUnknownBlockType channelSwitchBlock; // @synthesize channelSwitchBlock=_channelSwitchBlock;
@property(retain, nonatomic) CSubMenuItem *switchSourceSubMenuItem; // @synthesize switchSourceSubMenuItem=_switchSourceSubMenuItem;
@property(retain, nonatomic) NSString *switchSourceLocalChannelID; // @synthesize switchSourceLocalChannelID=_switchSourceLocalChannelID;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)p_updateTableView:(id)arg1 withAddList:(id)arg2 andDelList:(id)arg3;
- (id)tableView:(id)arg1 firstLevelCellWithSubMenuItem:(id)arg2 indexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)p_isProvinceHasNewChannelWithSection:(long long)arg1;
- (void)localChannelSwitchWithDescItem:(id)arg1;
- (void)registerTableViewCellWithTableView:(id)arg1;
- (id)p_getFormatLocalNewsArray:(id)arg1;
- (void)p_setChannelSettingViewModel;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)configBarButtons;
- (id)initWithCurrentLocalChannelID:(id)arg1 switchBlock:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

