//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAbstractModelBuilder.h"

@interface QNMediaPickerControllerParamBuilder : QNAbstractModelBuilder
{
}

+ (id)builderWithModelCopy:(id)arg1;
+ (id)builder;
+ (id)fromDictionary:(id)arg1;
- (id)setAllowStoreImage:(_Bool)arg1;
- (_Bool)allowStoreImage;
- (id)setAllowTakePhoto:(_Bool)arg1;
- (_Bool)allowTakePhoto;
- (id)setMaxVideoRecordDuration:(long long)arg1;
- (long long)maxVideoRecordDuration;
- (id)setMinVideoRecordDuration:(long long)arg1;
- (long long)minVideoRecordDuration;
- (id)setMaxVideoSelectCount:(long long)arg1;
- (long long)maxVideoSelectCount;
- (id)setMaxImageSelectCount:(long long)arg1;
- (long long)maxImageSelectCount;
- (id)setColumnNumber:(long long)arg1;
- (long long)columnNumber;
- (id)setAllowType:(unsigned long long)arg1;
- (unsigned long long)allowType;
- (id)build;
- (id)do_createModelObject;
- (id)initWithModelCopy:(id)arg1;
- (id)init;
- (void)do_customMapping:(id)arg1;

@end

