//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class CArticleContentVideoExtendNode, NSString, UICollectionView;

@interface QNMultiStreamLiveVideoContainer : NSObject <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    UICollectionView *_collectionView;
    CDUnknownBlockType _liveVideoBlock;
    CArticleContentVideoExtendNode *_videoExtendNode;
    NSString *_currentBroadcastId;
    struct CGRect _frame;
}

@property(copy, nonatomic) NSString *currentBroadcastId; // @synthesize currentBroadcastId=_currentBroadcastId;
@property(retain, nonatomic) CArticleContentVideoExtendNode *videoExtendNode; // @synthesize videoExtendNode=_videoExtendNode;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(copy, nonatomic) CDUnknownBlockType liveVideoBlock; // @synthesize liveVideoBlock=_liveVideoBlock;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)_getMultiStreamLiveVideoItemWithIndexPath:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withVideoInfo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

