//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNNetworkJSONDictionaryApi.h"

@interface QNMyAccountQAApi : QNNetworkJSONDictionaryApi
{
}

- (id)_parseResponseInfo:(id)arg1;
- (id)initWithType:(long long)arg1 channelId:(id)arg2 coralUin:(id)arg3 coralUid:(id)arg4 lastReplyId:(id)arg5 lastPubTime:(double)arg6;
- (id)initWithType:(long long)arg1 channelId:(id)arg2 coralUin:(id)arg3 coralUid:(id)arg4;
- (id)initWithType:(long long)arg1 coralUin:(id)arg2 coralUid:(id)arg3 lastReplyId:(id)arg4 lastPubTime:(double)arg5;
- (id)initWithType:(long long)arg1 coralUin:(id)arg2 coralUid:(id)arg3;
- (id)initWithType:(long long)arg1 channelId:(id)arg2 lastReplyId:(id)arg3 lastPubTime:(double)arg4;
- (id)initWithType:(long long)arg1 channelId:(id)arg2;
- (void)startWithSuccess:(CDUnknownBlockType)arg1 fail:(CDUnknownBlockType)arg2;
- (Class)callbackResultClass;

@end

