//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAbstractModelBuilder.h"

@interface QNNewsDetailDBItemBuilder : QNAbstractModelBuilder
{
}

+ (id)builderWithModelCopy:(id)arg1;
+ (id)builder;
+ (id)fromDictionary:(id)arg1;
- (id)setDetailContent:(id)arg1;
- (id)detailContent;
- (id)setCategory:(id)arg1;
- (id)category;
- (id)setNewsVersion:(id)arg1;
- (id)newsVersion;
- (id)setNewsId:(id)arg1;
- (id)newsId;
- (id)build;
- (id)do_createModelObject;
- (id)initWithModelCopy:(id)arg1;
- (id)init;
- (void)do_customMapping:(id)arg1;

@end

