//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBaseModelObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSObject<NSCoding>, NSString;

@interface QNNewsDetailDBItem : QNBaseModelObject <NSCopying, NSCoding>
{
    NSString *_newsId;
    NSString *_newsVersion;
    NSString *_category;
    NSObject<NSCoding> *_detailContent;
}

+ (id)build:(CDUnknownBlockType)arg1;
+ (_Bool)isImmutable;
@property(retain, nonatomic) NSObject<NSCoding> *detailContent; // @synthesize detailContent=_detailContent;
@property(copy, nonatomic) NSString *category; // @synthesize category=_category;
@property(copy, nonatomic) NSString *newsVersion; // @synthesize newsVersion=_newsVersion;
@property(copy, nonatomic) NSString *newsId; // @synthesize newsId=_newsId;
- (void).cxx_destruct;
- (id)copyInstance;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (_Bool)isValid;

@end

