//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

#import "UIScrollViewDelegate.h"
#import "WKNavigationDelegate.h"

@class CAGradientLayer, NSString, QNEnlargeHitTestButton, QNLoadingShimmerView, QNWebView;

@interface QNNewUserActivityRuleDetailView : QNThemableView <WKNavigationDelegate, UIScrollViewDelegate>
{
    CDUnknownBlockType _didClickCloseButtonBlock;
    QNWebView *_webView;
    CAGradientLayer *_gradientLayer;
    QNLoadingShimmerView *_loadingView;
    QNEnlargeHitTestButton *_closeButton;
}

@property(nonatomic) __weak QNEnlargeHitTestButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak QNLoadingShimmerView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) __weak CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(retain, nonatomic) QNWebView *webView; // @synthesize webView=_webView;
@property(copy, nonatomic) CDUnknownBlockType didClickCloseButtonBlock; // @synthesize didClickCloseButtonBlock=_didClickCloseButtonBlock;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)endLoadingAnimation;
- (void)startLoadingAnimation;
- (void)closeButtonDidClick:(id)arg1;
- (void)loadRuleDetailWithUrlString:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

