//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QNNewUserActivityManagerProtocol.h"

@class LOTAnimationView, NSString, NSTimer, QNSignInActivityModel;

@interface QNNewUserSignInActivityManager : NSObject <QNNewUserActivityManagerProtocol>
{
    QNSignInActivityModel *_cacheActivityModel;
    LOTAnimationView *_weltView;
    NSTimer *_timer;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) __weak LOTAnimationView *weltView; // @synthesize weltView=_weltView;
@property(retain, nonatomic) QNSignInActivityModel *cacheActivityModel; // @synthesize cacheActivityModel=_cacheActivityModel;
- (void).cxx_destruct;
- (id)p_bossPageType;
- (unsigned long long)p_currentDays;
- (void)p_bossType:(id)arg1 area:(id)arg2 pageType:(id)arg3 error:(_Bool)arg4;
- (void)p_bossExposureArea:(id)arg1 error:(_Bool)arg2;
- (void)p_bossExposureArea:(id)arg1;
- (void)p_bossClickArea:(id)arg1;
- (void)bossLoginDismiss;
- (void)bossLoginSuccessWechat;
- (void)bossLoginSuccessQQ;
- (void)bossLoginExposure;
- (void)bossCloseAlertClick;
- (void)bossRuleDetailClick;
- (void)bossNeverRemindClick;
- (void)bossAlertConfirmClick;
- (void)bossAlertExposureError;
- (void)bossAlertExposure;
- (void)bossWeltClick;
- (void)bossWeltExposure;
- (_Bool)hasPresentedActivityAlert;
- (void)setHasPresentedActivityAlert:(_Bool)arg1;
- (_Bool)neverRemindMeSignInActivity;
- (void)setNeverRemindMeSignInActivity;
- (void)clearNewUserSignInActivity;
- (id)newUserSignInActivity;
- (void)setNewUserSignInActivity:(id)arg1;
- (void)showLoginFrom:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3 cancel:(CDUnknownBlockType)arg4;
- (void)presentActivityControllerWithDoSignIn:(_Bool)arg1;
- (void)p_stopTimer;
- (void)p_removeWeltView;
- (void)p_hideWeltViewIfNeeded;
- (void)removeWeltView;
- (void)weltViewDidClickAction:(id)arg1;
- (void)fixWeltAnimationInterrupt;
- (void)changeWeltViewToMiniStyle;
- (void)showNewUserActivityWeltIfNeededOnListView:(id)arg1 withChannelId:(id)arg2;
- (_Bool)p_isInNewsTop;
- (_Bool)p_needPresentActivityController;
- (void)showNewUserActivityAlertIfNeeded;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

