//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, QNAsyncSerialTask, QNAsyncTask<QNNewsDetailApiProtocol>, QNNewsDetailLoaderParams;

@interface QNNewsDetailLoader : NSObject
{
    _Bool _isLoading;
    _Bool _cacheRemoteData;
    _Bool _isCacheData;
    CDUnknownBlockType _apiCreatBlock;
    CDUnknownBlockType _cacheLoadBlock;
    CDUnknownBlockType _cacheSaveBlock;
    QNNewsDetailLoaderParams *_detailParam;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failedBlock;
    QNAsyncSerialTask *_serialTask;
    QNAsyncTask<QNNewsDetailApiProtocol> *_remoteRequestTask;
    NSError *_loadError;
}

@property(retain, nonatomic) NSError *loadError; // @synthesize loadError=_loadError;
@property(nonatomic) _Bool isCacheData; // @synthesize isCacheData=_isCacheData;
@property(retain, nonatomic) QNAsyncTask<QNNewsDetailApiProtocol> *remoteRequestTask; // @synthesize remoteRequestTask=_remoteRequestTask;
@property(retain, nonatomic) QNAsyncSerialTask *serialTask; // @synthesize serialTask=_serialTask;
@property(copy, nonatomic) CDUnknownBlockType failedBlock; // @synthesize failedBlock=_failedBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(retain, nonatomic) QNNewsDetailLoaderParams *detailParam; // @synthesize detailParam=_detailParam;
@property(copy, nonatomic) CDUnknownBlockType cacheSaveBlock; // @synthesize cacheSaveBlock=_cacheSaveBlock;
@property(copy, nonatomic) CDUnknownBlockType cacheLoadBlock; // @synthesize cacheLoadBlock=_cacheLoadBlock;
@property(copy, nonatomic) CDUnknownBlockType apiCreatBlock; // @synthesize apiCreatBlock=_apiCreatBlock;
@property(nonatomic) _Bool cacheRemoteData; // @synthesize cacheRemoteData=_cacheRemoteData;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
- (void).cxx_destruct;
- (void)monitor_loadFailed;
- (void)monitor_loadSuccess;
- (void)monitor_remoteDataLoaded;
- (void)monitor_remoteApiCreated;
- (void)monitor_cacheDataLoaded;
- (void)monitor_loadStart;
- (id)p_aggregateTaskResults:(id)arg1 isCacheData:(_Bool)arg2;
- (void)loadNewsDetailDataWithDetailParam:(id)arg1 cachePolicy:(unsigned long long)arg2 success:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;

@end

