//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FMDatabaseQueue, NSObject<OS_dispatch_queue>;

@interface QNNetworkLogCache : NSObject
{
    long long _currentEntryCountInDB;
    FMDatabaseQueue *_logDB;
    NSObject<OS_dispatch_queue> *_serialQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(retain, nonatomic) FMDatabaseQueue *logDB; // @synthesize logDB=_logDB;
@property(nonatomic) long long currentEntryCountInDB; // @synthesize currentEntryCountInDB=_currentEntryCountInDB;
- (void).cxx_destruct;
- (id)getNetworkLogCachePath;
- (id)getNetworkLogCacheFile;
- (void)_commonInitDB;
- (void)_deleteEntriesByCountLimit;
- (void)_syncCacheEntriesCount;
- (void)clearAllNetworkLog;
- (void)getNetworkLogFromDBWithPage:(long long)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)saveNetworkLogToDBWithArray:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

@end

