//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class QNBaseLabel, QNEnlargeHitTestButton, QNNewUserTaskActivityButton, QNTaskActivityModel;

@interface QNNewUserTaskActivityFooter : UIView
{
    unsigned long long _footerType;
    QNTaskActivityModel *_activityModel;
    QNBaseLabel *_nextDescLbl;
    QNNewUserTaskActivityButton *_confirmBtn;
    QNEnlargeHitTestButton *_leftButton;
    QNEnlargeHitTestButton *_rightButton;
    QNNewUserTaskActivityButton *_moreBtn;
    QNNewUserTaskActivityButton *_obtainBadgeBtn;
}

@property(retain, nonatomic) QNNewUserTaskActivityButton *obtainBadgeBtn; // @synthesize obtainBadgeBtn=_obtainBadgeBtn;
@property(retain, nonatomic) QNNewUserTaskActivityButton *moreBtn; // @synthesize moreBtn=_moreBtn;
@property(retain, nonatomic) QNEnlargeHitTestButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) QNEnlargeHitTestButton *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) QNNewUserTaskActivityButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) QNBaseLabel *nextDescLbl; // @synthesize nextDescLbl=_nextDescLbl;
@property(retain, nonatomic) QNTaskActivityModel *activityModel; // @synthesize activityModel=_activityModel;
@property(nonatomic) unsigned long long footerType; // @synthesize footerType=_footerType;
- (void).cxx_destruct;
- (void)updateConfirmBtnWithActivityModel:(id)arg1;
- (void)updateFooterType:(unsigned long long)arg1;
- (void)layoutFooterViewWithActivityModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

