//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

#import "CSimpleImageViewDelegate.h"

@class CSimpleImageViewEx, NSString, QNBaseLabel, QNListNewsItem, UIButton, UIImageView, UILabel;

@interface QNNormalTitleBaseView : QNThemableView <CSimpleImageViewDelegate>
{
    UIImageView *_flagImageView;
    CSimpleImageViewEx *_avatorImageView;
    QNBaseLabel *_titleLabel;
    UIButton *_viewerButton;
    UIButton *_likeButton;
    QNListNewsItem *_listItem;
    UILabel *_matchTimeLabel;
    unsigned long long _currentType;
}

@property(nonatomic) unsigned long long currentType; // @synthesize currentType=_currentType;
@property(retain, nonatomic) UILabel *matchTimeLabel; // @synthesize matchTimeLabel=_matchTimeLabel;
@property(retain, nonatomic) QNListNewsItem *listItem; // @synthesize listItem=_listItem;
@property(retain, nonatomic) UIButton *likeButton; // @synthesize likeButton=_likeButton;
@property(retain, nonatomic) UIButton *viewerButton; // @synthesize viewerButton=_viewerButton;
@property(retain, nonatomic) QNBaseLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) CSimpleImageViewEx *avatorImageView; // @synthesize avatorImageView=_avatorImageView;
@property(retain, nonatomic) UIImageView *flagImageView; // @synthesize flagImageView=_flagImageView;
- (void).cxx_destruct;
- (void)p_hostAvatorClicked;
- (void)layoutControlsWithCurrentOrientation;
- (void)setImageCompletedWithImageView:(id)arg1 image:(id)arg2;
- (void)setForecastDefaultTitle;
- (void)updateWithTitle:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

