//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

#import "UIScrollViewDelegate.h"

@class NSString, UIPageControl, UIScrollView;

@interface QNPayGridView : QNThemableView <UIScrollViewDelegate>
{
    unsigned long long _maxItemCountPerPage;
    CDUnknownBlockType _selectedBlock;
    UIScrollView *_container;
    UIPageControl *_pageControl;
    struct CGSize _itemSize;
    struct UIEdgeInsets _contentInsets;
}

+ (double)p_itemSpaceWithItemSize:(struct CGSize)arg1 containerWidth:(double)arg2;
+ (double)defaultHeight;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIScrollView *container; // @synthesize container=_container;
@property(copy, nonatomic) CDUnknownBlockType selectedBlock; // @synthesize selectedBlock=_selectedBlock;
@property(nonatomic) unsigned long long maxItemCountPerPage; // @synthesize maxItemCountPerPage=_maxItemCountPerPage;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
@property(nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)p_didSelectProduct:(id)arg1;
- (void)p_productSelected:(id)arg1;
- (void)updateWithPayInfo:(id)arg1 targetDiamond:(long long)arg2;
- (void)updateWithPayInfo:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

