//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QNPersonalInfoHelper : NSObject
{
}

+ (struct CGSize)getStringSizeWithString:(id)arg1 font:(id)arg2;
+ (id)titleAttributedString:(id)arg1 font:(id)arg2 color:(id)arg3;
+ (double)cellHeightWithMultiLineText:(id)arg1;
+ (id)personalInfoFormDatas;

@end

