//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, QNPickCityDataApi;

@interface QNPickCityManager : NSObject
{
    QNPickCityDataApi *_requestApi;
    NSMutableDictionary *_pickCityDataInfo;
}

+ (id)keyForUserHasSetCurrentCityStateWithChannelID:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *pickCityDataInfo; // @synthesize pickCityDataInfo=_pickCityDataInfo;
@property(retain, nonatomic) QNPickCityDataApi *requestApi; // @synthesize requestApi=_requestApi;
- (void).cxx_destruct;
- (void)_handleRemoteConfigChangedNotification:(id)arg1;
- (void)_resetCurrentCity;
- (void)_updatePickCityData:(id)arg1;
- (void)_updateOriginData:(id)arg1;
- (void)_updateDataWithRemoteData:(id)arg1;
- (void)_updateCityDataWithChannelIDS:(id)arg1;
- (void)_loadCityDataForChannel:(id)arg1;
- (_Bool)saveCurrentCity:(id)arg1 forChannel:(id)arg2 triggerByUser:(_Bool)arg3;
- (id)originCityDataForChannel:(id)arg1;
- (void)saveOriginCityDataInitFinished:(_Bool)arg1 forChannel:(id)arg2;
- (_Bool)isOriginCityDataInitFinishedForChannel:(id)arg1;
- (id)getCityItemWithCityID:(id)arg1 fromChannel:(id)arg2;
- (void)setCurrentSelectCity:(id)arg1 forChannel:(id)arg2 triggerByUser:(_Bool)arg3;
- (id)pickCityDataForChannel:(id)arg1;
- (void)tryUpdateCityDataForChannel:(id)arg1;
- (void)tryUpdateAllCityDataIfNeed;
- (void)updateCityData;
- (void)dealloc;
- (id)init;

@end

