//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNPlayerControlViewFullScreenBase.h"

#import "QNChannelVideoPromptViewCallBack.h"

@class NSString, QNTVKPlayerPartsTopControl;

@interface QNPlayerControlViewOnDemandFullScreen : QNPlayerControlViewFullScreenBase <QNChannelVideoPromptViewCallBack>
{
    QNTVKPlayerPartsTopControl *_topControl;
}

@property(retain, nonatomic) QNTVKPlayerPartsTopControl *topControl; // @synthesize topControl=_topControl;
- (void).cxx_destruct;
- (void)_showPlayNextPromptOfFullScreenWithCountdown:(long long)arg1;
- (void)_hidePlayNextPromptOfFullScreen;
- (void)playNextVideo;
- (void)replayCurrentVideo;
- (void)updateProgress:(double)arg1 bufferTime:(double)arg2 duration:(double)arg3;
- (void)hideControls;
- (void)showControls;
- (unsigned long long)getCurrentPlayerType;
- (void)layoutSubviews;
- (void)updateSubViews;
- (void)willShow;
- (void)updateTopView;
- (void)setTowEyesState:(_Bool)arg1;
- (_Bool)isTowEyeState;
- (void)createSubViews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

