//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UITableViewDataSource.h"

@class NSString, QNBasicListViewModel<QNBasicListViewModelSubclassProtocol>, QNPortraitVideoDetailViewController;

@interface QNPortraitVideoDetailDataSourceAdapter : NSObject <UITableViewDataSource>
{
    QNPortraitVideoDetailViewController *_viewController;
    QNBasicListViewModel<QNBasicListViewModelSubclassProtocol> *_listViewModel;
}

@property(retain, nonatomic) QNBasicListViewModel<QNBasicListViewModelSubclassProtocol> *listViewModel; // @synthesize listViewModel=_listViewModel;
@property(nonatomic) __weak QNPortraitVideoDetailViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)initAdapterWithController:(id)arg1 listViewModel:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

