//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBundleBase.h"

@interface QNPreciousBundle : QNBundleBase
{
}

+ (id)rankMore;
+ (id)rank3;
+ (id)rank2;
+ (id)rank1;
+ (id)moreSmall;
+ (id)moreBig;
+ (id)favoritedSmall;
+ (id)favoritedBig;
+ (id)favoriteSmall;
+ (id)favoriteBig;
+ (id)detailSupported;
+ (id)detailSupport;
+ (id)complain;
+ (id)commentSmall;
+ (id)commentBig;
+ (id)camera;
+ (id)box;
+ (id)pdfResources;
+ (id)sharedInstance;

@end

