//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNRootViewController.h"

@interface QNPreloadViewController : QNRootViewController
{
    long long _articleType;
}

@property(nonatomic) long long articleType; // @synthesize articleType=_articleType;
- (void)showError:(_Bool)arg1 animated:(_Bool)arg2;
- (void)useTranslucentNavigationBar;
- (void)configBarButtons;
- (id)loadingView;
- (void)viewDidLoad;
- (id)initWithParam:(id)arg1 articleType:(long long)arg2;

@end

