//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBaseViewModel.h"

@class NSURL, QNUserItem, UIImage;

@interface QNPraiseAvatarViewModel : QNBaseViewModel
{
    NSURL *_headImageURL;
    UIImage *_defaultHeadImage;
    QNUserItem *_userItem;
}

@property(retain, nonatomic) QNUserItem *userItem; // @synthesize userItem=_userItem;
@property(retain, nonatomic) UIImage *defaultHeadImage; // @synthesize defaultHeadImage=_defaultHeadImage;
@property(retain, nonatomic) NSURL *headImageURL; // @synthesize headImageURL=_headImageURL;
- (void).cxx_destruct;

@end

