//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface QNPullToRefreshManager : NSObject
{
    NSMutableArray *_pullToRefreshData;
    NSMutableDictionary *_pullToRefreshDataChannelDic;
    NSString *_version;
}

+ (id)shareInstance;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
- (void).cxx_destruct;
- (id)pullToRefrshViewWithType:(long long)arg1 allowCustom:(_Bool)arg2 channelId:(id)arg3;
- (void)p_handleError:(id)arg1;
- (void)p_handleResponse:(id)arg1;
- (void)loadLastPullConfig;
- (void)refreshVersion:(id)arg1;
- (void)writeDataToDisk;
- (void)readDataFromDisk;
- (id)getConfigPath;
- (id)init;

@end

