//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNRootViewController.h"

#import "QNContentPurchasedCheckAllCoursesViewActionDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, QNContentPurchasedCheckAllCoursesView, QNLayoutTableView, QNLoadingShimmerView, QNPurchasedQuizzesListModel;

@interface QNPurchasedQuizzesController : QNRootViewController <UITableViewDelegate, UITableViewDataSource, QNContentPurchasedCheckAllCoursesViewActionDelegate>
{
    QNPurchasedQuizzesListModel *_listModel;
    QNLayoutTableView *_tableView;
    QNLoadingShimmerView *_loadingShimmerView;
    QNContentPurchasedCheckAllCoursesView *_checkAllCoursesView;
}

@property(retain, nonatomic) QNContentPurchasedCheckAllCoursesView *checkAllCoursesView; // @synthesize checkAllCoursesView=_checkAllCoursesView;
@property(retain, nonatomic) QNLoadingShimmerView *loadingShimmerView; // @synthesize loadingShimmerView=_loadingShimmerView;
@property(retain, nonatomic) QNLayoutTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) QNPurchasedQuizzesListModel *listModel; // @synthesize listModel=_listModel;
- (void).cxx_destruct;
- (void)checkAllCoursesViewDidTapped;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)p_enterToWebView:(id)arg1;
- (void)p_setFooterView;
- (void)p_loadingSuccess;
- (void)p_loadingFailed;
- (void)p_showTipView;
- (void)p_loadData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

