//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface QNPushHistoryViewModel : NSObject
{
    NSMutableArray *_newsList;
    NSArray *_itemList;
}

@property(copy, nonatomic) NSArray *itemList; // @synthesize itemList=_itemList;
@property(retain, nonatomic) NSMutableArray *newsList; // @synthesize newsList=_newsList;
- (void).cxx_destruct;
- (id)p_dislikeTypeStringWithType:(long long)arg1;
- (id)p_dateStringWithIndex:(long long)arg1 timestamp:(double)arg2;
- (void)p_processResponse:(id)arg1 type:(long long)arg2;
- (void)dislikeItem:(id)arg1 withType:(long long)arg2;
- (_Bool)hasValidData;
- (id)itemForIndexPath:(id)arg1;
- (unsigned long long)countOfItems;
- (void)loadWithType:(long long)arg1 finishBlock:(CDUnknownBlockType)arg2;

@end

