//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThreeImageNewsCell.h"

@interface QNQAThreeImageNewsCell : QNThreeImageNewsCell
{
}

+ (double)heightForData:(id)arg1 width:(double)arg2 context:(id)arg3;
- (void)layoutWithData:(id)arg1 context:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

