//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAbstractModelBuilder.h"

@interface QNQAEditorAnswerModelBuilder : QNAbstractModelBuilder
{
}

+ (id)builderWithModelCopy:(id)arg1;
+ (id)builder;
- (id)setImageModels:(id)arg1;
- (id)imageModels;
- (id)setHtmlContent:(id)arg1;
- (id)htmlContent;
- (id)setCurrentReplyId:(id)arg1;
- (id)currentReplyId;
- (id)setCommentId:(id)arg1;
- (id)commentId;
- (id)setRequestId:(id)arg1;
- (id)requestId;
- (id)setQuestionId:(id)arg1;
- (id)questionId;
- (id)setUserId:(id)arg1;
- (id)userId;
- (id)build;
- (id)do_createModelObject;
- (id)initWithModelCopy:(id)arg1;
- (id)init;

@end

