//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface QNQQLoginModel : NSObject
{
    _Bool _isVip;
    _Bool _isGroupVip;
    NSString *_qqnick;
    NSString *_weiboNick;
    NSString *_weiboicon;
    NSString *_mediaID;
    NSString *_encodedUin;
    NSString *_qqHeadUrl;
    long long _sex;
    NSString *_starSign;
    NSMutableDictionary *_userInfoCookies;
}

@property(retain, nonatomic) NSMutableDictionary *userInfoCookies; // @synthesize userInfoCookies=_userInfoCookies;
@property(nonatomic) _Bool isGroupVip; // @synthesize isGroupVip=_isGroupVip;
@property(nonatomic) _Bool isVip; // @synthesize isVip=_isVip;
@property(copy, nonatomic) NSString *starSign; // @synthesize starSign=_starSign;
@property(nonatomic) long long sex; // @synthesize sex=_sex;
@property(copy, nonatomic) NSString *qqHeadUrl; // @synthesize qqHeadUrl=_qqHeadUrl;
@property(copy, nonatomic) NSString *encodedUin; // @synthesize encodedUin=_encodedUin;
@property(copy, nonatomic) NSString *mediaID; // @synthesize mediaID=_mediaID;
@property(copy, nonatomic) NSString *weiboicon; // @synthesize weiboicon=_weiboicon;
@property(copy, nonatomic) NSString *weiboNick; // @synthesize weiboNick=_weiboNick;
@property(copy, nonatomic) NSString *qqnick; // @synthesize qqnick=_qqnick;
- (void).cxx_destruct;
- (id)getCookieHeader;

@end

