//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QNQRCodeHelper : NSObject
{
}

+ (id)p_adjustCIImage:(id)arg1 withSize:(double)arg2;
+ (id)p_generateQRCodeImageWithContentString:(id)arg1;
+ (id)generateQRCodeImageWithContentString:(id)arg1 size:(double)arg2;

@end

