//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBaseCell.h"

@class LOTAnimationView, QNBaseLabel, QNEnlargeHitTestButton, QNQualityCourseLessonCellModel, UIImageView, UIView;

@interface QNQualityCourseLessonCell : CBaseCell
{
    CDUnknownBlockType _iconClickBlock;
    QNQualityCourseLessonCellModel *_cellModel;
    UIImageView *_playIcon;
    LOTAnimationView *_playingAnimationView;
    QNBaseLabel *_titleLabel;
    QNBaseLabel *_subTitleLabel;
    QNEnlargeHitTestButton *_rightIcon;
    UIView *_leftLine;
}

@property(retain, nonatomic) UIView *leftLine; // @synthesize leftLine=_leftLine;
@property(retain, nonatomic) QNEnlargeHitTestButton *rightIcon; // @synthesize rightIcon=_rightIcon;
@property(retain, nonatomic) QNBaseLabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) QNBaseLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) LOTAnimationView *playingAnimationView; // @synthesize playingAnimationView=_playingAnimationView;
@property(retain, nonatomic) UIImageView *playIcon; // @synthesize playIcon=_playIcon;
@property(retain, nonatomic) QNQualityCourseLessonCellModel *cellModel; // @synthesize cellModel=_cellModel;
@property(copy, nonatomic) CDUnknownBlockType iconClickBlock; // @synthesize iconClickBlock=_iconClickBlock;
- (void).cxx_destruct;
- (void)p_applyDefaultSelectedBackgroundView;
- (void)p_rightIconPress:(id)arg1;
- (void)layoutWithCellModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

