//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, QNDeDaoLessonModel, UIColor, UIImage;

@interface QNQualityCourseLessonCellModel : NSObject
{
    _Bool _rightIconEnabled;
    _Bool _bottomLineHidden;
    _Bool _leftLineHidden;
    QNDeDaoLessonModel *_lessonModel;
    UIColor *_bgColor;
    UIImage *_playIcon;
    UIImage *_rightIcon;
    NSAttributedString *_title;
    NSAttributedString *_subTitle;
    UIColor *_bottomLineColor;
    UIColor *_leftLineColor;
    struct CGSize _viewSize;
    struct CGRect _playIconRect;
    struct CGRect _rightIconRect;
    struct CGRect _titleRect;
    struct CGRect _subTitleRect;
    struct CGRect _bottomLineRect;
    struct CGRect _leftLineRect;
}

@property(nonatomic) _Bool leftLineHidden; // @synthesize leftLineHidden=_leftLineHidden;
@property(nonatomic) struct CGRect leftLineRect; // @synthesize leftLineRect=_leftLineRect;
@property(retain, nonatomic) UIColor *leftLineColor; // @synthesize leftLineColor=_leftLineColor;
@property(retain, nonatomic) UIColor *bottomLineColor; // @synthesize bottomLineColor=_bottomLineColor;
@property(nonatomic) struct CGRect bottomLineRect; // @synthesize bottomLineRect=_bottomLineRect;
@property(nonatomic) _Bool bottomLineHidden; // @synthesize bottomLineHidden=_bottomLineHidden;
@property(nonatomic) struct CGRect subTitleRect; // @synthesize subTitleRect=_subTitleRect;
@property(copy, nonatomic) NSAttributedString *subTitle; // @synthesize subTitle=_subTitle;
@property(nonatomic) struct CGRect titleRect; // @synthesize titleRect=_titleRect;
@property(copy, nonatomic) NSAttributedString *title; // @synthesize title=_title;
@property(nonatomic) _Bool rightIconEnabled; // @synthesize rightIconEnabled=_rightIconEnabled;
@property(nonatomic) struct CGRect rightIconRect; // @synthesize rightIconRect=_rightIconRect;
@property(retain, nonatomic) UIImage *rightIcon; // @synthesize rightIcon=_rightIcon;
@property(nonatomic) struct CGRect playIconRect; // @synthesize playIconRect=_playIconRect;
@property(retain, nonatomic) UIImage *playIcon; // @synthesize playIcon=_playIcon;
@property(retain, nonatomic) UIColor *bgColor; // @synthesize bgColor=_bgColor;
@property(nonatomic) struct CGSize viewSize; // @synthesize viewSize=_viewSize;
@property(retain, nonatomic) QNDeDaoLessonModel *lessonModel; // @synthesize lessonModel=_lessonModel;
- (void).cxx_destruct;
- (void)calculateWithCourseModel:(id)arg1 context:(id)arg2;

@end

