//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBundleBase.h"

@interface QNQuestionAnswerBundle : QNBundleBase
{
}

+ (id)userpageIconCommentDelete;
+ (id)tlIconText;
+ (id)shareIconUninterestedPress;
+ (id)shareIconUninterestedNormal;
+ (id)shareIconEditPress;
+ (id)shareIconEditNormal;
+ (id)qaIconMyanswer;
+ (id)qaIconInviteanswer;
+ (id)qaIconFollowAnswerSmall;
+ (id)qaIconFollowAnswer;
+ (id)qaIconAnswerZhanwei;
+ (id)qaIconAnswer;
+ (id)qaBtEditPress;
+ (id)qaBtEditNormal;
+ (id)qaBtAddedNormal;
+ (id)iconEditorDot;
+ (id)btnEditorSeparatorSelected;
+ (id)btnEditorSeparator;
+ (id)btnEditorListSelected;
+ (id)btnEditorList;
+ (id)btnEditorBoldSelected;
+ (id)btnEditorBold;
+ (id)arrowDown;
+ (id)pdfResources;
+ (id)sharedInstance;

@end

