//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNCommonListDataAdapter.h"

@interface QNRecommendListDataAdapter : QNCommonListDataAdapter
{
}

- (void)tryToAddTopicNewsWithTopicItem:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)configTableViewCellLayoutContext:(id)arg1 forData:(id)arg2 indexPath:(id)arg3;
- (Class)classForListItem:(id)arg1 context:(id)arg2;
- (void)configureCellFactory;

@end

