//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@interface QNRecommendUnlikeTipViewBase : QNThemableView
{
    CDUnknownBlockType _completionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void).cxx_destruct;
- (void)showUnlikeTipsInTableViewCell:(id)arg1 position:(struct CGPoint)arg2 kbListItem:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)showUnlikeTipsInTableViewCell:(id)arg1 position:(struct CGPoint)arg2 listItem:(id)arg3 completion:(CDUnknownBlockType)arg4;

@end

