//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class UIColor;

@interface QNRemindPoint : QNThemableView
{
    UIColor *_color;
}

@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)resetWithColor:(id)arg1;
- (void)resetWithDefaultColor;
- (id)initWithColor:(id)arg1;
- (void)themeChanged:(long long)arg1;

@end

