//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNRoseLiveRoomPreciousTalkViewModel.h"

@interface QNRoseLiveRoomPreciousHotViewModel : QNRoseLiveRoomPreciousTalkViewModel
{
}

- (_Bool)do_shouldHandleFakeMessageSendComplete:(id)arg1 comment:(id)arg2;
- (_Bool)do_shouldHandleFakeMessageStartSend:(id)arg1 comment:(id)arg2;
- (id)do_parseResponse:(id)arg1;
- (void)mergeFakeMessage;
- (void)loadData;

@end

