//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNRoseLiveRoomContentTextFragmentView.h"

@interface QNRoseLiveRoomPreciousTextFragmentView : QNRoseLiveRoomContentTextFragmentView
{
}

+ (struct UIEdgeInsets)contentInset:(id)arg1;
+ (double)fontSize:(id)arg1;
+ (double)lineHeight:(id)arg1;
+ (long long)p_maxNumberOfLines:(id)arg1;
- (void)layoutSubviewsImmediately;
- (void)clearHighlightBackground;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)themeChanged:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

