//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBundleBase.h"

@interface QNSettingsBundle : QNBundleBase
{
}

+ (id)settingWeixinfriendsunbound;
+ (id)settingWeixinfriendsbound;
+ (id)settingWeibounbound;
+ (id)settingWeibobound;
+ (id)settingSinaweiboiconunbound;
+ (id)settingSinaweiboiconbound;
+ (id)settingAccountheadiconback;
+ (id)settingAccountheadicon;
+ (id)settingQzoneunbound;
+ (id)settingQzonebound;
+ (id)settingGene;
+ (id)night;
+ (id)loginBtnWeixinNormal;
+ (id)loginBtnWeiboNormal;
+ (id)loginBtnQqNormal;
+ (id)loginAvatar;
+ (id)channellableIconAddNormal;
+ (id)pdfResources;
+ (id)sharedInstance;

@end

