//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableCollectionViewCell.h"

@class NSString, QNBaseLabel, UIImageView, UIView;

@interface QNSearchHotRankCell : QNThemableCollectionViewCell
{
    QNBaseLabel *_textLbl;
    QNBaseLabel *_hotLabel;
    UIView *_verticalLine;
    UIImageView *_bottomLine;
    NSString *_hotWordTag;
}

+ (id)identifier;
@property(copy, nonatomic) NSString *hotWordTag; // @synthesize hotWordTag=_hotWordTag;
@property(retain, nonatomic) UIImageView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIView *verticalLine; // @synthesize verticalLine=_verticalLine;
@property(retain, nonatomic) QNBaseLabel *hotLabel; // @synthesize hotLabel=_hotLabel;
@property(retain, nonatomic) QNBaseLabel *textLbl; // @synthesize textLbl=_textLbl;
- (void).cxx_destruct;
- (void)p_setHotLabelStyle;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)themeChanged:(long long)arg1;
- (void)layoutRankCellWithShowInfo:(id)arg1 type:(unsigned long long)arg2 indexPathRow:(long long)arg3 isLastRow:(_Bool)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

