//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UITextFieldDelegate.h"

@class NSString, QNCommentsViewModel, UITextField, UITextView, UIView;

@interface QNSendDanmakuPanel : NSObject <UITextFieldDelegate>
{
    _Bool _isAnimation;
    _Bool _loginSuccess;
    QNCommentsViewModel *_commentsViewModel;
    CDUnknownBlockType _danmuPanelEnd;
    CDUnknownBlockType _customSendBlock;
    UITextField *_danmakuTextField;
    UIView *_writeMaskView;
    UIView *_textFieldMaskView;
    UITextView *_overlengthView;
    double _keyboardHeight;
    unsigned long long _keyboardAnimationOptions;
    double _keyboardAnimationDuration;
    NSString *_placeholder;
}

@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(nonatomic) double keyboardAnimationDuration; // @synthesize keyboardAnimationDuration=_keyboardAnimationDuration;
@property(nonatomic) unsigned long long keyboardAnimationOptions; // @synthesize keyboardAnimationOptions=_keyboardAnimationOptions;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(nonatomic) _Bool loginSuccess; // @synthesize loginSuccess=_loginSuccess;
@property(nonatomic) _Bool isAnimation; // @synthesize isAnimation=_isAnimation;
@property(retain, nonatomic) UITextView *overlengthView; // @synthesize overlengthView=_overlengthView;
@property(retain, nonatomic) UIView *textFieldMaskView; // @synthesize textFieldMaskView=_textFieldMaskView;
@property(retain, nonatomic) UIView *writeMaskView; // @synthesize writeMaskView=_writeMaskView;
@property(retain, nonatomic) UITextField *danmakuTextField; // @synthesize danmakuTextField=_danmakuTextField;
@property(copy, nonatomic) CDUnknownBlockType customSendBlock; // @synthesize customSendBlock=_customSendBlock;
@property(copy, nonatomic) CDUnknownBlockType danmuPanelEnd; // @synthesize danmuPanelEnd=_danmuPanelEnd;
@property(nonatomic) __weak QNCommentsViewModel *commentsViewModel; // @synthesize commentsViewModel=_commentsViewModel;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldCharactersChange;
- (void)layoutTextViewWithKeyboard;
- (void)handleKeyboardWillHide:(id)arg1;
- (void)handleKeyboardWillShow:(id)arg1;
- (void)p_delayHideShowOverLengthTips;
- (void)p_showOverLengthTips;
- (struct CGRect)p_screenBounds;
- (void)sendDanmaku:(id)arg1;
- (void)closeWriteDanmakuWithAnimated:(_Bool)arg1;
- (void)p_tapWriteMaskView;
- (void)showSendPanel;
- (void)showSendPanelWithPlaceholder:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

