//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableCollectionViewCell.h"

@class QNBaseLabel, QNEnlargeHitTestButton;

@interface QNSearchBarCollectionHeaderCell : QNThemableCollectionViewCell
{
    QNBaseLabel *_textLabel;
    CDUnknownBlockType _cleanAllBlock;
    QNEnlargeHitTestButton *_cleanAllBtn;
}

+ (double)getDeleteAllSearchCellHeight;
+ (id)identifier;
@property(retain, nonatomic) QNEnlargeHitTestButton *cleanAllBtn; // @synthesize cleanAllBtn=_cleanAllBtn;
@property(copy, nonatomic) CDUnknownBlockType cleanAllBlock; // @synthesize cleanAllBlock=_cleanAllBlock;
@property(retain, nonatomic) QNBaseLabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)themeChanged:(long long)arg1;
- (void)layoutSubviews;
- (void)cleanupBtnAction:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

