//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAbstractModelBuilder.h"

@interface QNSportsCommunityParamBuilder : QNAbstractModelBuilder
{
}

+ (id)builderWithModelCopy:(id)arg1;
+ (id)builder;
+ (id)fromDictionary:(id)arg1;
- (id)setRetCode:(id)arg1;
- (id)retCode;
- (id)setTargetId:(long long)arg1;
- (long long)targetId;
- (id)setArticleType:(long long)arg1;
- (long long)articleType;
- (id)setSportsExt:(id)arg1;
- (id)sportsExt;
- (id)setNewsId:(id)arg1;
- (id)newsId;
- (id)setChannelId:(id)arg1;
- (id)channelId;
- (id)build;
- (id)do_createModelObject;
- (id)initWithModelCopy:(id)arg1;
- (id)init;
- (void)do_customMapping:(id)arg1;

@end

