//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class NSArray, NSMutableArray;

@interface QNSpecialActivitiesView : QNThemableView
{
    NSArray *_activityItems;
    NSMutableArray *_activityViews;
}

@property(retain, nonatomic) NSMutableArray *activityViews; // @synthesize activityViews=_activityViews;
@property(retain, nonatomic) NSArray *activityItems; // @synthesize activityItems=_activityItems;
- (void).cxx_destruct;
- (void)themeChanged:(long long)arg1;
- (void)_onButtonClicked:(id)arg1;
- (void)layoutActivitiesView:(id)arg1;

@end

