//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNTableViewCell.h"

#import "QNAdCellViewableImpressionProtocol.h"
#import "QNSSPAdCommentViewComponent.h"

@class CALayer, CNewsAdDetailBottomBar, CSimpleImageView, NSString, QNAdCommentCellHeader, QNAdCommentCellLayoutContext, QNAdItem, QNAvatarView, TADReportManager;

@interface QNSSPAdCommentCell : QNTableViewCell <QNSSPAdCommentViewComponent, QNAdCellViewableImpressionProtocol>
{
    QNAdItem *_adItem;
    TADReportManager *_adReportManager;
    CDUnknownBlockType _touchEventCallBackBlock;
    QNAvatarView *_avatarView;
    QNAdCommentCellHeader *_cellHeader;
    CSimpleImageView *_largeImageView;
    CNewsAdDetailBottomBar *_bottomBar;
    CALayer *_separatorLine;
    QNAdCommentCellLayoutContext *_layoutContext;
}

+ (double)heightForAdItem:(id)arg1;
@property(retain, nonatomic) QNAdCommentCellLayoutContext *layoutContext; // @synthesize layoutContext=_layoutContext;
@property(retain, nonatomic) CALayer *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(retain, nonatomic) CNewsAdDetailBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(retain, nonatomic) CSimpleImageView *largeImageView; // @synthesize largeImageView=_largeImageView;
@property(retain, nonatomic) QNAdCommentCellHeader *cellHeader; // @synthesize cellHeader=_cellHeader;
@property(retain, nonatomic) QNAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(copy, nonatomic) CDUnknownBlockType touchEventCallBackBlock; // @synthesize touchEventCallBackBlock=_touchEventCallBackBlock;
@property(nonatomic) __weak TADReportManager *adReportManager; // @synthesize adReportManager=_adReportManager;
@property(retain, nonatomic) QNAdItem *adItem; // @synthesize adItem=_adItem;
- (void).cxx_destruct;
- (void)adCellDidAppear;
- (void)layoutSubviews;
- (void)layoutWithAdItem:(id)arg1 layoutContext:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (double)bottomViewHeight:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

