//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNNetworkJSONDictionaryApi.h"

@interface QNSubscribeFunsApi : QNNetworkJSONDictionaryApi
{
}

- (id)p_jsonParser;
- (id)initWithPageIndex:(unsigned long long)arg1 lastSubTime:(unsigned long long)arg2 andGuestUin:(id)arg3 andOmId:(id)arg4;
- (id)initWithPageIndex:(unsigned long long)arg1 lastSubTime:(unsigned long long)arg2 andOmId:(id)arg3;
- (id)initWithPageIndex:(unsigned long long)arg1 lastSubTime:(unsigned long long)arg2 andGuestUin:(id)arg3;

@end

