//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNRootViewController.h"

#import "QNCommonListControllerDelegate.h"
#import "QNCommonListControllerProtocol.h"
#import "QNSubscirbeContentControllerProtocol.h"
#import "QNWebviewCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CSubscribeListItemNode, NSArray, NSIndexPath, NSMutableArray, NSMutableSet, NSString, QN5TabBar, QNBaseLabel, QNLayoutTableView, QNSubscribeCategoryNode, QNTopicItem, UIView;

@interface QNSubscribeCategoryController : QNRootViewController <UITableViewDelegate, UITableViewDataSource, QNWebviewCellDelegate, QNCommonListControllerProtocol, QNCommonListControllerDelegate, QNSubscirbeContentControllerProtocol>
{
    _Bool _isFromDiscovery;
    _Bool _isLoadingMore;
    _Bool _isReachEnd;
    _Bool _isfollowAnimation;
    QNLayoutTableView *_tableView;
    QNSubscribeCategoryNode *_categoryNode;
    NSArray *_listItems;
    NSMutableSet *_tpIdSet;
    NSMutableSet *_catIdSet;
    long long _refreshNo;
    QNBaseLabel *_headLabel;
    UIView *_headView;
    NSIndexPath *_lastSelectedIndexPath;
    UIView *_bottomLine;
    CSubscribeListItemNode *_node;
    QNTopicItem *_topicItem;
    NSMutableArray *_didExposureArray;
    NSMutableArray *_followAnimationList;
    QN5TabBar *_tabBar;
}

@property(nonatomic) _Bool isfollowAnimation; // @synthesize isfollowAnimation=_isfollowAnimation;
@property(retain, nonatomic) QN5TabBar *tabBar; // @synthesize tabBar=_tabBar;
@property(retain, nonatomic) NSMutableArray *followAnimationList; // @synthesize followAnimationList=_followAnimationList;
@property(retain, nonatomic) NSMutableArray *didExposureArray; // @synthesize didExposureArray=_didExposureArray;
@property(retain, nonatomic) QNTopicItem *topicItem; // @synthesize topicItem=_topicItem;
@property(retain, nonatomic) CSubscribeListItemNode *node; // @synthesize node=_node;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) NSIndexPath *lastSelectedIndexPath; // @synthesize lastSelectedIndexPath=_lastSelectedIndexPath;
@property(retain, nonatomic) UIView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) QNBaseLabel *headLabel; // @synthesize headLabel=_headLabel;
@property(nonatomic) _Bool isReachEnd; // @synthesize isReachEnd=_isReachEnd;
@property(nonatomic) long long refreshNo; // @synthesize refreshNo=_refreshNo;
@property(nonatomic) _Bool isLoadingMore; // @synthesize isLoadingMore=_isLoadingMore;
@property(retain, nonatomic) NSMutableSet *catIdSet; // @synthesize catIdSet=_catIdSet;
@property(retain, nonatomic) NSMutableSet *tpIdSet; // @synthesize tpIdSet=_tpIdSet;
@property(copy, nonatomic) NSArray *listItems; // @synthesize listItems=_listItems;
@property(retain, nonatomic) QNSubscribeCategoryNode *categoryNode; // @synthesize categoryNode=_categoryNode;
@property(nonatomic) _Bool isFromDiscovery; // @synthesize isFromDiscovery=_isFromDiscovery;
@property(retain, nonatomic) QNLayoutTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)themeChanged:(long long)arg1;
- (void)scroll2Top;
- (id)getContentScrollView;
- (void)configureCellRankIcon:(id)arg1 atIndexPath:(id)arg2;
- (id)buildListItemsFromArray:(id)arg1;
- (void)doneLoadingTableViewData:(_Bool)arg1;
- (void)handlePushRequestOpen:(_Bool)arg1 type:(long long)arg2;
- (double)pushAlertViewBottomSpan;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)cleanListItemsUIDataCache;
- (void)scrollViewDidScroll:(id)arg1;
- (void)loadMore;
- (void)updateCategoryNode:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (id)initWithCategoryNode:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

