//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class QNBaseLabel, UIView;

@interface QNSubscribeFixPosHeaderView : QNThemableView
{
    QNBaseLabel *_titleLbl;
    UIView *_seperatorLine;
}

@property(retain, nonatomic) UIView *seperatorLine; // @synthesize seperatorLine=_seperatorLine;
@property(retain, nonatomic) QNBaseLabel *titleLbl; // @synthesize titleLbl=_titleLbl;
- (void).cxx_destruct;
- (void)layoutWithTitle:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

