//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNBaseModelObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSArray;

@interface QNSyncTopicResponse : QNBaseModelObject <NSCopying, NSCoding>
{
    NSArray *_cancelKeyList;
    NSArray *_subKeyList;
    NSArray *_subFailList;
    NSArray *_subList;
    long long _version;
}

+ (id)build:(CDUnknownBlockType)arg1;
+ (_Bool)isImmutable;
@property(nonatomic) long long version; // @synthesize version=_version;
@property(copy, nonatomic) NSArray *subList; // @synthesize subList=_subList;
@property(copy, nonatomic) NSArray *subFailList; // @synthesize subFailList=_subFailList;
@property(copy, nonatomic) NSArray *subKeyList; // @synthesize subKeyList=_subKeyList;
@property(copy, nonatomic) NSArray *cancelKeyList; // @synthesize cancelKeyList=_cancelKeyList;
- (void).cxx_destruct;
- (id)copyInstance;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

