//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface QNTADWXCardInfoModel : NSObject
{
    NSArray *_cardList;
    NSString *_errMsg;
}

@property(copy, nonatomic) NSString *errMsg; // @synthesize errMsg=_errMsg;
@property(copy, nonatomic) NSArray *cardList; // @synthesize cardList=_cardList;
- (void).cxx_destruct;

@end

