//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

#import "QNPageViewContentViewProtocol.h"

@class NSString, QNAttributedLabel, QNBaseLabel, QNReportParam, QNTopicItem, UIImageView, UIView;

@interface QNTopicImageView : QNThemableView <QNPageViewContentViewProtocol>
{
    unsigned long long _contentIndex;
    UIImageView *_bgImageView;
    UIView *_coverView;
    QNAttributedLabel *_nameLabel;
    UIImageView *_flagView;
    QNBaseLabel *_infoLabel;
    QNTopicItem *_topicItem;
    QNReportParam *_reportParam;
}

@property(retain, nonatomic) QNReportParam *reportParam; // @synthesize reportParam=_reportParam;
@property(retain, nonatomic) QNTopicItem *topicItem; // @synthesize topicItem=_topicItem;
@property(retain, nonatomic) QNBaseLabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) UIImageView *flagView; // @synthesize flagView=_flagView;
@property(retain, nonatomic) QNAttributedLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIView *coverView; // @synthesize coverView=_coverView;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(nonatomic) unsigned long long contentIndex; // @synthesize contentIndex=_contentIndex;
- (void).cxx_destruct;
- (id)creatListItemWithTopicItem:(id)arg1;
- (void)p_layoutTopicTitle;
- (void)reloadWithTopicItem:(id)arg1 reportParam:(id)arg2;
- (void)layoutSubviews;
- (void)themeChanged:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1 topicItem:(id)arg2 reportParam:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

