//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class QNEnlargeHitTestButton, UILabel, UIView;

@interface QNTopicSelectSectionHeaderView : QNThemableView
{
    CDUnknownBlockType _deleteButtonClickedBlock;
    UILabel *_titleLabel;
    QNEnlargeHitTestButton *_deleteButton;
    UIView *_topLine;
}

@property(retain, nonatomic) UIView *topLine; // @synthesize topLine=_topLine;
@property(retain, nonatomic) QNEnlargeHitTestButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType deleteButtonClickedBlock; // @synthesize deleteButtonClickedBlock=_deleteButtonClickedBlock;
- (void).cxx_destruct;
- (void)deleteButtonClicked:(id)arg1;
- (void)reloadWithTitle:(id)arg1 deleteEnabled:(_Bool)arg2 topLineHiden:(_Bool)arg3;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

