//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, UIView;

@interface QNTVPlayerBeforehandManager : NSObject
{
    long long _newsRefreshCount;
    double _times;
    UIView *_videoChannelTipsImageView;
    NSMutableArray *_list;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(retain, nonatomic) UIView *videoChannelTipsImageView; // @synthesize videoChannelTipsImageView=_videoChannelTipsImageView;
@property(nonatomic) double times; // @synthesize times=_times;
@property(nonatomic) long long newsRefreshCount; // @synthesize newsRefreshCount=_newsRefreshCount;
- (void).cxx_destruct;
- (void)clearAllGuidanceNewsList;
- (void)saveOver8SecondTimesVideoWithItem:(id)arg1;
- (_Bool)shouldShowGuidanceNewsRefresh;
- (void)saveShowGuidanceData:(id)arg1;
- (_Bool)shouldShowGuidanceView;
- (_Bool)hasOverVideoMaxNusmbers;
- (void)dealloc;
- (id)init;

@end

