//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNTableViewCell.h"

#import "QNUserCenterBannerItemCellDelegate.h"
#import "QNUserCenterCellProtocol.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSString, QNCollectionView, QNMineSection, QNMutiPagesIndicatorView;

@interface QNUserCenterBannerCell : QNTableViewCell <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, QNUserCenterBannerItemCellDelegate, QNUserCenterCellProtocol>
{
    id <QNUserCenterCellDelegate> _interactorDelegate;
    QNCollectionView *_bannerView;
    QNMutiPagesIndicatorView *_pageControl;
    QNMineSection *_section;
}

+ (double)heightForRowAtIndexPath:(id)arg1 InSection:(id)arg2;
@property(nonatomic) __weak QNMineSection *section; // @synthesize section=_section;
@property(nonatomic) __weak QNMutiPagesIndicatorView *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) __weak QNCollectionView *bannerView; // @synthesize bannerView=_bannerView;
@property(nonatomic) __weak id <QNUserCenterCellDelegate> interactorDelegate; // @synthesize interactorDelegate=_interactorDelegate;
- (void).cxx_destruct;
- (void)layoutCellAtIndexPath:(id)arg1 InSection:(id)arg2;
- (void)bannerItemCell:(id)arg1 webviewDidLoadSuccess:(id)arg2 contentHeight:(double)arg3 withEntity:(id)arg4;
- (void)scrollViewDidScroll:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)layoutSubviews;
- (void)setupPageControlTheme;
- (void)setupPageControl;
- (void)setupBannerView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

