//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNNetworkJSONDictionaryApi.h"

@interface QNVideoRecommendListApi : QNNetworkJSONDictionaryApi
{
}

+ (id)p_parseResponseInfo:(id)arg1 channelId:(id)arg2;
- (id)initWithVid:(id)arg1 listItem:(id)arg2 reportParam:(id)arg3 channelId:(id)arg4;

@end

