//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "QNHotestCommentBarDegate.h"
#import "QNImmerseCellProtocol.h"
#import "QNVideoDetaillmmerseBarHandle.h"
#import "QNVideoDetaillmmerseFirstHandle.h"

@class NSString, QNHotestCommentBar, QNImmBottomView, QNListNewsItem, QNVideoCellMiddleImmerContent, QNVideoDetailItem;

@interface QNVideoDetailImmerseTableViewCell : UITableViewCell <QNVideoDetaillmmerseBarHandle, QNVideoDetaillmmerseFirstHandle, QNHotestCommentBarDegate, QNImmerseCellProtocol>
{
    _Bool _isDoingAnimation;
    int _cellState;
    QNVideoDetailItem *_detailItem;
    CDUnknownBlockType _playVideoBlock;
    CDUnknownBlockType _posterViewClickBlock;
    id <QNVideoDetaillmmerseCellHandle> _cellHandleDegate;
    QNHotestCommentBar *_topBar;
    QNVideoCellMiddleImmerContent *_middleContentView;
    QNImmBottomView *_bottomView;
}

+ (float)getHeightWithDetailitem:(id)arg1 type:(long long)arg2;
@property(nonatomic) int cellState; // @synthesize cellState=_cellState;
@property(retain, nonatomic) QNImmBottomView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) _Bool isDoingAnimation; // @synthesize isDoingAnimation=_isDoingAnimation;
@property(retain, nonatomic) QNVideoCellMiddleImmerContent *middleContentView; // @synthesize middleContentView=_middleContentView;
@property(retain, nonatomic) QNHotestCommentBar *topBar; // @synthesize topBar=_topBar;
@property(nonatomic) __weak id <QNVideoDetaillmmerseCellHandle> cellHandleDegate; // @synthesize cellHandleDegate=_cellHandleDegate;
@property(copy, nonatomic) CDUnknownBlockType posterViewClickBlock; // @synthesize posterViewClickBlock=_posterViewClickBlock;
@property(copy, nonatomic) CDUnknownBlockType playVideoBlock; // @synthesize playVideoBlock=_playVideoBlock;
@property(retain, nonatomic) QNVideoDetailItem *detailItem; // @synthesize detailItem=_detailItem;
- (void).cxx_destruct;
- (void)switchToCellState:(int)arg1;
- (void)darkWithSubViewAlpha:(double)arg1 judgmentDoAnimation:(_Bool)arg2;
- (double)videoTopInView:(id)arg1;
- (struct CGRect)videoDisplayRect;
- (id)getViewAbovePosterView;
- (id)getPoseterImage;
- (id)getPosterView;
- (_Bool)isPosterViewOnMine;
- (void)resetPosterView;
- (_Bool)isPlayOnMine;
@property(readonly, nonatomic) _Bool isPlaying;
@property(readonly, nonatomic) QNListNewsItem *listItem;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)didClickCommentFirstButton;
- (void)commentBarDidClickDeclareButton:(struct CGRect)arg1;
- (void)didClickLikeButton:(id)arg1;
- (void)didClickSharedButton:(id)arg1;
- (void)didClickCommentButton:(id)arg1;
- (void)p_updateVideoBottomView;
- (id)getTopTitle;
- (void)p_updateVideoTitleLabel;
- (void)updateCellWithVideoDetailitem:(id)arg1 type:(long long)arg2;
- (void)p_commentVideo;
- (void)p_clickOM:(id)arg1;
- (void)p_clickTag:(id)arg1;
- (void)handleClickType:(long long)arg1 userinfo:(id)arg2;
- (void)didClickCommentWithBar:(id)arg1;
- (void)p_setBottomView;
- (void)p_setupMiddleContent;
- (void)p_setupTopBar;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

