//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAutoCodingCopyingObject.h"

@class NSURL, UIImage;

@interface QNVideoRecorderResult : QNAutoCodingCopyingObject
{
    _Bool _isFail;
    float _progress;
    NSURL *_videoURL;
    double _duration;
    CDUnknownBlockType _progressBlock;
    CDUnknownBlockType _failBlock;
    long long _fakeCommentStatus;
    UIImage *_videoThumbnail;
}

@property(retain, nonatomic) UIImage *videoThumbnail; // @synthesize videoThumbnail=_videoThumbnail;
@property(nonatomic) long long fakeCommentStatus; // @synthesize fakeCommentStatus=_fakeCommentStatus;
@property(nonatomic) _Bool isFail; // @synthesize isFail=_isFail;
@property(nonatomic) float progress; // @synthesize progress=_progress;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(readonly, nonatomic) double duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
- (void).cxx_destruct;
- (void)forceLoadThumbnail;
- (id)initWithVideoURL:(id)arg1 duration:(double)arg2;

@end

