//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, UILabel, UILongPressGestureRecognizer;

@interface QNVideoRecordingButtonView : UIView
{
    _Bool _enabled;
    long long _state;
    CDUnknownBlockType _stateChangedBlock;
    double _maximumDuration;
    double _currentDuration;
    double _animationProgress;
    UILabel *_titleLabel;
    UIView *_animationView;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(retain, nonatomic) UIView *animationView; // @synthesize animationView=_animationView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) double animationProgress; // @synthesize animationProgress=_animationProgress;
@property(nonatomic) double currentDuration; // @synthesize currentDuration=_currentDuration;
@property(nonatomic) double maximumDuration; // @synthesize maximumDuration=_maximumDuration;
@property(copy, nonatomic) CDUnknownBlockType stateChangedBlock; // @synthesize stateChangedBlock=_stateChangedBlock;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)p_handleTimerCount;
- (void)p_stopTimer;
- (void)p_startTimer;
- (void)p_handleLongPressGesture:(id)arg1;
- (void)p_buildGesture;
- (void)p_setAnimationViewBackgroundColorWithAlpha:(double)arg1;
- (id)p_getTitleLabel:(id)arg1;
- (void)p_buildSubviews;
- (void)showDisableRecordingTitle;
- (void)showTitleLabel:(_Bool)arg1;
- (void)disable;
- (void)reset;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

