//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class QNEnlargeHitTestButton;

@interface QNVideoAlbumGuideCell : UITableViewCell
{
    QNEnlargeHitTestButton *_openBtn;
    CDUnknownBlockType _openBtnBlock;
}

+ (double)viewHeight;
@property(copy, nonatomic) CDUnknownBlockType openBtnBlock; // @synthesize openBtnBlock=_openBtnBlock;
@property(retain, nonatomic) QNEnlargeHitTestButton *openBtn; // @synthesize openBtn=_openBtn;
- (void).cxx_destruct;
- (void)p_openBtnClicked;
- (void)p_layoutSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

