//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class QNBaseLabel, QNVideoAlbumPlayingView, UIButton, UIImageView;

@interface QNVideoVerticalAlbumCell : UITableViewCell
{
    UIImageView *_coverImageView;
    QNBaseLabel *_titleLabel;
    QNBaseLabel *_timeLabel;
    UIButton *_viewerButton;
    QNVideoAlbumPlayingView *_playingView;
}

+ (double)viewHeight;
+ (double)titleLabelWidth;
@property(retain, nonatomic) QNVideoAlbumPlayingView *playingView; // @synthesize playingView=_playingView;
@property(retain, nonatomic) UIButton *viewerButton; // @synthesize viewerButton=_viewerButton;
@property(retain, nonatomic) QNBaseLabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) QNBaseLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
- (void).cxx_destruct;
- (void)updateWithPlaying:(_Bool)arg1;
- (void)layoutWithDetailItem:(id)arg1;
- (void)p_layoutViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

