//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KBTableViewCell.h"

@class QNEnlargeHitTestButton;

@interface QNVideoAlbumExpandCell : KBTableViewCell
{
    CDUnknownBlockType _btnClickBlock;
    QNEnlargeHitTestButton *_expandBtn;
}

+ (double)heightForData:(id)arg1 width:(double)arg2 context:(id)arg3;
@property(retain, nonatomic) QNEnlargeHitTestButton *expandBtn; // @synthesize expandBtn=_expandBtn;
@property(copy, nonatomic) CDUnknownBlockType btnClickBlock; // @synthesize btnClickBlock=_btnClickBlock;
- (void).cxx_destruct;
- (void)layoutWithData:(id)arg1 context:(id)arg2;
- (void)p_openBtnClicked;
- (void)p_decorateViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

