//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QQVUpload;

@interface QNVideoKitUploader : NSObject
{
    QQVUpload *_uploadMgr;
}

+ (id)sharedInstance;
@property(retain, nonatomic) QQVUpload *uploadMgr; // @synthesize uploadMgr=_uploadMgr;
- (void).cxx_destruct;
- (id)p_buildVuserInfoWithLoginInfo;
- (id)vidForKey:(id)arg1;
- (_Bool)isUploading;
- (void)stopUploadWithFilePath:(id)arg1;
- (void)stopAllUploadTasks;
- (void)uploadVideoWithFilePath:(id)arg1 videoType:(unsigned long long)arg2 videoTitle:(id)arg3 completionBlock:(CDUnknownBlockType)arg4 progressBlock:(CDUnknownBlockType)arg5;
- (id)init;

@end

