//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class QNAttributedLabel, UIImageView;

@interface QNVideoChannelGuidanceView : QNThemableView
{
    QNAttributedLabel *_attributedLabel;
    UIImageView *_imageView;
}

@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) QNAttributedLabel *attributedLabel; // @synthesize attributedLabel=_attributedLabel;
- (void).cxx_destruct;
- (id)titleAttributedString:(id)arg1 textColor:(id)arg2;
- (void)layoutSubviews;
- (void)p_initAttributedLabelWithType:(long long)arg1;
- (id)initWithType:(long long)arg1;

@end

