//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAbstractModelBuilder.h"

@interface QNVideoDetailPageResponseModuleBuilder : QNAbstractModelBuilder
{
}

+ (id)builderWithModelCopy:(id)arg1;
+ (id)builder;
+ (id)fromDictionary:(id)arg1;
- (id)setModuleType:(unsigned long long)arg1;
- (unsigned long long)moduleType;
- (id)setKk_tagVideoArr:(id)arg1;
- (id)kk_tagVideoArr;
- (id)setKk_recVideoArr:(id)arg1;
- (id)kk_recVideoArr;
- (id)setKk_videoInfo:(id)arg1;
- (id)kk_videoInfo;
- (id)setNewsList:(id)arg1;
- (id)newsList;
- (id)setSpecialVideoList:(id)arg1;
- (id)specialVideoList;
- (id)setAuthorInfo:(id)arg1;
- (id)authorInfo;
- (id)setIdStr:(id)arg1;
- (id)idStr;
- (id)build;
- (id)do_createModelObject;
- (id)initWithModelCopy:(id)arg1;
- (id)init;
- (id)initWithDictionaryStub:(id)arg1;
- (void)do_customMapping:(id)arg1;

@end

