//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

@class CAGradientLayer, QNCommonGIFImageView, QNListNewsItem, QNVideoCellTopBar, QNVideoInfoView, UIButton, UIImageView, UILabel, UIView;

@interface QNVideoCellMiddleContent : QNThemableView
{
    QNListNewsItem *_listItem;
    QNCommonGIFImageView *_coverImgView;
    UIView *_playBtn;
    CDUnknownBlockType _clickBlock;
    UIImageView *_vr360ImageView;
    QNVideoCellTopBar *_topBar;
    UIView *_playCountBGView;
    UILabel *_playCountLabel;
    UIButton *_bgBtn;
    UIView *_maskImageView;
    QNVideoInfoView *_messageView;
    CAGradientLayer *_topGradient;
}

+ (double)topBarHeightWithItem:(id)arg1;
+ (double)defaultHeightWithItem:(id)arg1;
+ (double)defaultHeight;
@property(retain, nonatomic) CAGradientLayer *topGradient; // @synthesize topGradient=_topGradient;
@property(retain, nonatomic) QNVideoInfoView *messageView; // @synthesize messageView=_messageView;
@property(retain, nonatomic) UIView *maskImageView; // @synthesize maskImageView=_maskImageView;
@property(retain, nonatomic) UIButton *bgBtn; // @synthesize bgBtn=_bgBtn;
@property(retain, nonatomic) UILabel *playCountLabel; // @synthesize playCountLabel=_playCountLabel;
@property(retain, nonatomic) UIView *playCountBGView; // @synthesize playCountBGView=_playCountBGView;
@property(retain, nonatomic) QNVideoCellTopBar *topBar; // @synthesize topBar=_topBar;
@property(retain, nonatomic) UIImageView *vr360ImageView; // @synthesize vr360ImageView=_vr360ImageView;
@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
@property(retain, nonatomic) UIView *playBtn; // @synthesize playBtn=_playBtn;
@property(retain, nonatomic) QNCommonGIFImageView *coverImgView; // @synthesize coverImgView=_coverImgView;
@property(retain, nonatomic) QNListNewsItem *listItem; // @synthesize listItem=_listItem;
- (void).cxx_destruct;
- (void)playBtnClicked;
- (void)_updatePlayCountView;
- (void)_updateCoverViewWithChannelId:(id)arg1;
- (void)updatePlayCount;
- (void)_updateVRImageView;
- (void)updateViewsWithChannelId:(id)arg1;
- (void)_setupPlayBtn;
- (void)p_handleTap;
- (void)_setupTopBar;
- (_Bool)needRmdReason;
- (void)_setupPlayCountView;
- (void)_setupCoverView;
- (void)_setupBGBtn;
- (void)setFrame:(struct CGRect)arg1;
- (void)_setMessageView;
- (void)_setVRImageView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

