//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNNativeWidgetView.h"

@class QNNativeVoteWidgetView, UIImageView, UITapGestureRecognizer, UIView;

@interface QNVoteWidgetWrapper : QNNativeWidgetView
{
    _Bool _needShowFailAlert;
    QNNativeVoteWidgetView *_contentView;
    UIView *_tipContainer;
    UIImageView *_tipImage;
    UITapGestureRecognizer *_reloadTap;
    long long _loadState;
}

+ (struct CGSize)sizeForViewWithData:(id)arg1 width:(double)arg2 isNoPicMode:(_Bool)arg3;
@property(nonatomic) _Bool needShowFailAlert; // @synthesize needShowFailAlert=_needShowFailAlert;
@property(nonatomic) long long loadState; // @synthesize loadState=_loadState;
@property(retain, nonatomic) UITapGestureRecognizer *reloadTap; // @synthesize reloadTap=_reloadTap;
@property(retain, nonatomic) UIImageView *tipImage; // @synthesize tipImage=_tipImage;
@property(retain, nonatomic) UIView *tipContainer; // @synthesize tipContainer=_tipContainer;
@property(retain, nonatomic) QNNativeVoteWidgetView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)themeChanged:(long long)arg1;
- (void)_resetColor;
@property(readonly, nonatomic) _Bool isVoteLoaded;
- (void)updateVoteInfo;
- (void)p_handleTapToLoad:(id)arg1;
- (id)voteNode;
- (void)layoutViewWithData:(id)arg1;
- (id)initWidget;
- (long long)widgetViewType;

@end

