//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNAbstractModelBuilder.h"

@interface QNWalletServiceItemBuilder : QNAbstractModelBuilder
{
}

+ (id)builderWithModelCopy:(id)arg1;
+ (id)builder;
+ (id)fromDictionary:(id)arg1;
- (id)setLinkUrlString:(id)arg1;
- (id)linkUrlString;
- (id)setIsNative:(id)arg1;
- (id)isNative;
- (id)setNightImage:(id)arg1;
- (id)nightImage;
- (id)setDayImage:(id)arg1;
- (id)dayImage;
- (id)setName:(id)arg1;
- (id)name;
- (id)setServiceId:(id)arg1;
- (id)serviceId;
- (id)build;
- (id)do_createModelObject;
- (id)initWithModelCopy:(id)arg1;
- (id)init;
- (id)initWithDictionaryStub:(id)arg1;
- (void)do_customMapping:(id)arg1;

@end

