//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QNListMultiImagesUnitModel.h"

@class NSArray, NSString, QNImageProcessConfig, QNListNewsItem, UIColor, UIImage;

@interface QNWeiboCellMultiImagesUnitModel : NSObject <QNListMultiImagesUnitModel>
{
    struct CGSize _imageSize;
    NSArray *_imageOrImageURLs;
    NSArray *_imageOrImageItems;
    QNListNewsItem *_listItem;
    _Bool _autoPlayGIF;
    _Bool _enableTapGesture;
    UIColor *_bgColor;
    UIImage *_defaultImage;
    QNImageProcessConfig *_imageProcessConfig;
    long long _imageContentMode;
    struct CGRect _rect;
}

@property(readonly, nonatomic) long long imageContentMode; // @synthesize imageContentMode=_imageContentMode;
@property(readonly, nonatomic) _Bool enableTapGesture; // @synthesize enableTapGesture=_enableTapGesture;
@property(readonly, nonatomic) _Bool autoPlayGIF; // @synthesize autoPlayGIF=_autoPlayGIF;
@property(readonly, nonatomic) QNImageProcessConfig *imageProcessConfig; // @synthesize imageProcessConfig=_imageProcessConfig;
@property(readonly, nonatomic) UIImage *defaultImage; // @synthesize defaultImage=_defaultImage;
@property(readonly, nonatomic) UIColor *bgColor; // @synthesize bgColor=_bgColor;
@property(readonly, nonatomic) struct CGRect rect; // @synthesize rect=_rect;
- (void).cxx_destruct;
- (CDStruct_55d1109d)layoutTraitsForContext:(id)arg1;
- (id)gifStaticUrlAtIndex:(unsigned long long)arg1;
- (_Bool)imageIsGIFAtIndex:(unsigned long long)arg1;
- (id)imageAtIndex:(unsigned long long)arg1;
- (id)imageItemAtIndex:(unsigned long long)arg1;
- (id)imageURLAtIndex:(unsigned long long)arg1;
- (unsigned long long)countOfImages;
- (struct CGRect)imageFrameAtIndex:(unsigned long long)arg1;
- (unsigned long long)p_imageCountPerRow;
- (void)calculateWithData:(id)arg1 referRect:(struct CGRect)arg2 context:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

