//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

#import "QNDetailContentElementProtocol.h"
#import "QNListUnitProtocol.h"

@class NSString, QNAttributedLabel, QNDetailContentContainer, QNWeiboLocationViewModel;

@interface QNWeiboLocationView : QNThemableView <QNListUnitProtocol, QNDetailContentElementProtocol>
{
    QNDetailContentContainer *_contentContainer;
    QNAttributedLabel *_locationLabel;
    QNWeiboLocationViewModel *_viewModel;
}

@property(retain, nonatomic) QNWeiboLocationViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) QNAttributedLabel *locationLabel; // @synthesize locationLabel=_locationLabel;
@property(nonatomic) __weak QNDetailContentContainer *contentContainer; // @synthesize contentContainer=_contentContainer;
- (void).cxx_destruct;
- (double)heightOfElementView;
- (void)p_viewLocation;
- (void)p_handleTapGesture:(id)arg1;
- (void)layoutWithViewModel:(id)arg1 context:(id)arg2;
- (void)layoutSubviews;
- (void)themeChanged:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

