//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNCommentBaseCell.h"

@class CALayer, QNCommentCellContentUnitView, QNCommentCellLocationUnitView, QNCommentCellPictureUnitView, QNWidgetCommentCellBottomUnitView, QNWidgetCommentCellHeaderUnitView;

@interface QNWidgetCommentCell : QNCommentBaseCell
{
    QNWidgetCommentCellHeaderUnitView *_headerUnitView;
    QNCommentCellContentUnitView *_contentUnitView;
    QNCommentCellPictureUnitView *_picUnitView;
    QNCommentCellLocationUnitView *_locationUnitView;
    QNWidgetCommentCellBottomUnitView *_bottomUnitView;
    CALayer *_separatorLine;
}

@property(retain, nonatomic) CALayer *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(retain, nonatomic) QNWidgetCommentCellBottomUnitView *bottomUnitView; // @synthesize bottomUnitView=_bottomUnitView;
@property(retain, nonatomic) QNCommentCellLocationUnitView *locationUnitView; // @synthesize locationUnitView=_locationUnitView;
@property(retain, nonatomic) QNCommentCellPictureUnitView *picUnitView; // @synthesize picUnitView=_picUnitView;
@property(retain, nonatomic) QNCommentCellContentUnitView *contentUnitView; // @synthesize contentUnitView=_contentUnitView;
@property(retain, nonatomic) QNWidgetCommentCellHeaderUnitView *headerUnitView; // @synthesize headerUnitView=_headerUnitView;
- (void).cxx_destruct;
- (void)prepareForEnqueue;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)layoutWithViewModel:(id)arg1 context:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

