//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface QNWikiItemWord : NSObject
{
    NSString *_link;
    NSString *_word;
}

@property(copy, nonatomic) NSString *word; // @synthesize word=_word;
@property(copy, nonatomic) NSString *link; // @synthesize link=_link;
- (void).cxx_destruct;

@end

