//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QQLeakChecker : NSObject
{
}

+ (id)getInstance;
- (double)getOccupyMemory;
- (unsigned long long)getRecordStackNumber;
- (unsigned long long)getRecordObjNumber;
- (void)setNeedSystemStack:(_Bool)arg1;
- (void)setMaxStackDepth:(unsigned long long)arg1;
- (void)setPID:(id)arg1;
- (void)setAppversion:(id)arg1;
- (void)setUin:(id)arg1;
- (void)stopStackLogging;
- (void)startStackLogging;
- (void)executeLeakCheck:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

