//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSModel.h"

@class QSMatchDetailGuessProfitRankEntranceItem, QSMatchDetailGuessRecordItem;

@interface QSAfterMatchDetailGuessEntranceInfo : QSModel
{
    QSMatchDetailGuessProfitRankEntranceItem *_rank;
    QSMatchDetailGuessRecordItem *_records;
}

@property(retain, nonatomic) QSMatchDetailGuessRecordItem *records; // @synthesize records=_records;
@property(retain, nonatomic) QSMatchDetailGuessProfitRankEntranceItem *rank; // @synthesize rank=_rank;
- (void).cxx_destruct;

@end

