//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QSStatedDataDelegate.h"

@class NSString, QSMatchLivePropsKCoinExchangeData;

@interface QSBuyDiamondAndKbData : NSObject <QSStatedDataDelegate>
{
    NSString *_title;
    NSString *_subtitleSuffix;
    CDUnknownBlockType _finishBlock;
    QSMatchLivePropsKCoinExchangeData *_coinExchangeData;
}

@property(retain, nonatomic) QSMatchLivePropsKCoinExchangeData *coinExchangeData; // @synthesize coinExchangeData=_coinExchangeData;
@property(copy, nonatomic) CDUnknownBlockType finishBlock; // @synthesize finishBlock=_finishBlock;
@property(copy, nonatomic) NSString *subtitleSuffix; // @synthesize subtitleSuffix=_subtitleSuffix;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)data:(id)arg1 didFinishLoadWithError:(id)arg2;
- (void)dataWillStartLoad:(id)arg1;
- (void)exchangeKbWithDiamond:(long long)arg1 delay:(double)arg2;
- (void)buyDiamondWithDiamondNeeded:(long long)arg1;
- (void)buyKCoinWithKCoinNeeded:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

