//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSComTopicDetailContentCell.h"

@class QSRichTextLabel, UIButton;

@interface QSComTopicDetailTextContentCell : QSComTopicDetailContentCell
{
    QSRichTextLabel *_contentLabel;
    UIButton *_expandButton;
}

+ (double)cellHeightWithContentItem:(id)arg1 isReply:(_Bool)arg2;
@property(retain, nonatomic) UIButton *expandButton; // @synthesize expandButton=_expandButton;
@property(retain, nonatomic) QSRichTextLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
- (void).cxx_destruct;
- (void)update;
- (void)expandAction:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

