//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSModel.h"

@class QSComPublishTopicConfigContentItem, QSComPublishVideoConfigContentItem;

@interface QSComPublishConfigContentInfo : QSModel
{
    QSComPublishTopicConfigContentItem *_topic;
    QSComPublishVideoConfigContentItem *_video;
}

@property(retain, nonatomic) QSComPublishVideoConfigContentItem *video; // @synthesize video=_video;
@property(retain, nonatomic) QSComPublishTopicConfigContentItem *topic; // @synthesize topic=_topic;
- (void).cxx_destruct;

@end

