//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class QSComTopicDetailParentReplyView, QSComTopicDetailReplyItem;

@interface QSComTopicDetailParentReplyCell : UITableViewCell
{
    QSComTopicDetailReplyItem *_replyItem;
    QSComTopicDetailParentReplyView *_parentReplyView;
}

+ (double)cellHeightWithReplyItem:(id)arg1;
@property(retain, nonatomic) QSComTopicDetailParentReplyView *parentReplyView; // @synthesize parentReplyView=_parentReplyView;
@property(retain, nonatomic) QSComTopicDetailReplyItem *replyItem; // @synthesize replyItem=_replyItem;
- (void).cxx_destruct;
- (void)update;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

