//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSSportsMatchScheduleAttrView.h"

@class UILabel, UIScrollView;

@interface QSESportsScheduleMatchInfoView : QSSportsMatchScheduleAttrView
{
    UIScrollView *_contentScrollView;
    UILabel *_label;
}

+ (double)fixedHeight;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
- (void).cxx_destruct;
- (void)refreshWithScheduleItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

