//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QSHTTPRequestManagement : NSObject
{
}

+ (void)uploadImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)startDataRequestWithURLComponents:(id)arg1 parserBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;

@end

