//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class FLAnimatedImageView, NSString;

@interface QSImageDetailPageView : UIScrollView <UIScrollViewDelegate>
{
    FLAnimatedImageView *_imageView;
    CDUnknownBlockType _imageViewDidScrollBlock;
}

@property(copy, nonatomic) CDUnknownBlockType imageViewDidScrollBlock; // @synthesize imageViewDidScrollBlock=_imageViewDidScrollBlock;
@property(retain, nonatomic) FLAnimatedImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)restoreCenterPoint:(struct CGPoint)arg1 scale:(double)arg2;
- (struct CGPoint)minimumContentOffset;
- (struct CGPoint)maximumContentOffset;
- (double)scaleToRestoreAfterRotation;
- (struct CGPoint)pointToCenterAfterRotation;
- (void)setMaxMinZoomScalesForCurrentBounds;
- (struct CGRect)zoomRectForScale:(float)arg1 withCenter:(struct CGPoint)arg2;
- (void)handleDoubleTap:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)restoreCurPage;
- (void)setContentSize:(struct CGSize)arg1;
- (void)displayImage:(id)arg1;
- (void)displayGifImage:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

