//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSModel.h"

@class NSArray;

@interface QSMatchDetailStartListTableModel : QSModel
{
    NSArray *_head;
    NSArray *_row;
    NSArray *_width;
}

@property(retain, nonatomic) NSArray *width; // @synthesize width=_width;
@property(retain, nonatomic) NSArray *row; // @synthesize row=_row;
@property(retain, nonatomic) NSArray *head; // @synthesize head=_head;
- (void).cxx_destruct;

@end

