//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "QSMatchLivePropsMessageDisplayViewDataSource.h"

@class NSMutableArray, NSOperationQueue, NSString, QSMatchLivePropsMessageDisplayView;

@interface QSMatchLivePropsMessageDataSource : NSObject <QSMatchLivePropsMessageDisplayViewDataSource>
{
    QSMatchLivePropsMessageDisplayView *_displayView;
    id <QSMatchLivePropsMessageViewDelegate> _messageViewDelegate;
    NSMutableArray *_showingPropsMessageItems;
    NSMutableArray *_receivedPendingPropsMessages;
    NSOperationQueue *_gifDownloadQueue;
}

+ (int)propsMaxShowNum;
+ (_Bool)acceptMessageItem:(id)arg1;
@property(retain, nonatomic) NSOperationQueue *gifDownloadQueue; // @synthesize gifDownloadQueue=_gifDownloadQueue;
@property(retain, nonatomic) NSMutableArray *receivedPendingPropsMessages; // @synthesize receivedPendingPropsMessages=_receivedPendingPropsMessages;
@property(retain, nonatomic) NSMutableArray *showingPropsMessageItems; // @synthesize showingPropsMessageItems=_showingPropsMessageItems;
@property(nonatomic) __weak id <QSMatchLivePropsMessageViewDelegate> messageViewDelegate; // @synthesize messageViewDelegate=_messageViewDelegate;
@property(nonatomic) __weak QSMatchLivePropsMessageDisplayView *displayView; // @synthesize displayView=_displayView;
- (void).cxx_destruct;
- (double)displayView:(id)arg1 heightForRowAtIndex:(long long)arg2;
- (id)displayView:(id)arg1 viewForRowAtIndex:(long long)arg2;
- (long long)numberOfRowsInDisplayView:(id)arg1;
- (void)displayViewReplaceRowAtIndex:(unsigned long long)arg1;
- (void)displayViewDeleteRowsAtIndexes:(id)arg1 insertRowsAtIndexes:(id)arg2;
- (void)removeMessageItemAtIndex:(long long)arg1;
- (void)clearRecivedPendingMessageItem;
- (void)forceClearAllExceptSentAndLotteryMessageItem;
- (void)removeSentMessageItem;
- (void)removeMessageItem:(id)arg1;
- (void)addReceivedMessageItems:(id)arg1;
- (void)addSentMessageItem:(id)arg1;
- (void)addLotteryMessageItem:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

