//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIWebViewDelegate.h"

@class NSMutableArray, NSString, NSTimer, QSMatchLiveCartoonPropsMessageItem, QSMatchLivePropsBuyItem, QSMatchLivePropsListItem, UIWebView;

@interface QSMatchLivePropsCartoonView : UIView <UIWebViewDelegate>
{
    _Bool _animationIsReady;
    UIWebView *_webView;
    NSMutableArray *_receivedPendingPropsMessages;
    QSMatchLiveCartoonPropsMessageItem *_showingReceivedPropsMessageItem;
    QSMatchLivePropsListItem *_pendingPropsItem;
    QSMatchLivePropsBuyItem *_pendingBuyItem;
    QSMatchLivePropsListItem *_showingPropsItem;
    QSMatchLivePropsBuyItem *_showingBuyItem;
    NSString *_curMethodName;
    NSString *_h5data;
    NSTimer *_monitorTimer;
}

@property(retain, nonatomic) NSTimer *monitorTimer; // @synthesize monitorTimer=_monitorTimer;
@property(copy, nonatomic) NSString *h5data; // @synthesize h5data=_h5data;
@property(nonatomic) _Bool animationIsReady; // @synthesize animationIsReady=_animationIsReady;
@property(copy, nonatomic) NSString *curMethodName; // @synthesize curMethodName=_curMethodName;
@property(retain, nonatomic) QSMatchLivePropsBuyItem *showingBuyItem; // @synthesize showingBuyItem=_showingBuyItem;
@property(retain, nonatomic) QSMatchLivePropsListItem *showingPropsItem; // @synthesize showingPropsItem=_showingPropsItem;
@property(retain, nonatomic) QSMatchLivePropsBuyItem *pendingBuyItem; // @synthesize pendingBuyItem=_pendingBuyItem;
@property(retain, nonatomic) QSMatchLivePropsListItem *pendingPropsItem; // @synthesize pendingPropsItem=_pendingPropsItem;
@property(retain, nonatomic) QSMatchLiveCartoonPropsMessageItem *showingReceivedPropsMessageItem; // @synthesize showingReceivedPropsMessageItem=_showingReceivedPropsMessageItem;
@property(retain, nonatomic) NSMutableArray *receivedPendingPropsMessages; // @synthesize receivedPendingPropsMessages=_receivedPendingPropsMessages;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (id)allParamentsInfoWithRequest:(id)arg1;
- (void)doAnimationScript;
- (void)webViewDidFinishLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)monitorTimerFired:(id)arg1;
- (_Bool)isShowingReceivedProps;
- (_Bool)isShowingSentProps;
- (_Bool)isCurrentShowingProps;
- (void)reloadData;
- (void)showSentPendingProps;
- (void)showReceivedPendingMessageItem;
- (void)hideAndRemoveWebView;
- (void)showNextPropsCartoon;
- (void)forceClearReceivedMessage;
- (void)clearRecivedPendingMessageItem;
- (void)messageItemsBeenReceived:(id)arg1;
- (void)cancelPreload;
- (void)buyItemLoaded:(id)arg1;
- (void)preLoadPropsItem:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

