//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSModel.h"

@class NSDictionary, NSString;

@interface QSMyCommunityAttendOrFansItem : QSModel
{
    NSString *_uid;
    NSString *_name;
    NSString *_avatar;
    long long _vipType;
    NSDictionary *_jumpData;
    long long _followed;
}

+ (void)unAttendCommunityUserWithUid:(id)arg1 currentStatus:(long long)arg2;
+ (void)attendCommunityUserWithUid:(id)arg1 currentStatus:(long long)arg2;
+ (void)requestChangeCommunityUserAttendStatusWithUid:(id)arg1 currentStatus:(long long)arg2;
+ (id)propertyNameFromParsedKey:(id)arg1;
@property(nonatomic) long long followed; // @synthesize followed=_followed;
@property(retain, nonatomic) NSDictionary *jumpData; // @synthesize jumpData=_jumpData;
@property(nonatomic) long long vipType; // @synthesize vipType=_vipType;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (void)requestChangeCommunityUserAttendStatus;

@end

