//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QSEntranceSportsTabInfo, QSNBAHeaderEntranceView;

@protocol QSNBAHeaderEntranceViewDelegate <NSObject>
- (void)vipButtonDidTapInNBAHeaderEntranceView:(QSNBAHeaderEntranceView *)arg1 entranceTabInfo:(QSEntranceSportsTabInfo *)arg2;
- (void)communityButtonDidTapInNBAHeaderEntranceView:(QSNBAHeaderEntranceView *)arg1 entranceTabInfo:(QSEntranceSportsTabInfo *)arg2;
- (void)dataButtonDidTapInNBAHeaderEntranceView:(QSNBAHeaderEntranceView *)arg1;
- (void)matchScheduleButtonDidTapInNBAHeaderEntranceView:(QSNBAHeaderEntranceView *)arg1;
@end

