//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

@interface QSPlayerRanklistInfo : QSModel
{
    NSString *_serial;
    NSString *_name;
    NSString *_playerId;
    NSString *_icon;
    NSString *_value;
    NSString *_teamName;
    NSString *_teamLogo;
    NSString *_detailUrl;
    NSString *_position;
    NSString *_pointPG;
    NSString *_reboundsPG;
    NSString *_assistsPG;
}

@property(copy, nonatomic) NSString *assistsPG; // @synthesize assistsPG=_assistsPG;
@property(copy, nonatomic) NSString *reboundsPG; // @synthesize reboundsPG=_reboundsPG;
@property(copy, nonatomic) NSString *pointPG; // @synthesize pointPG=_pointPG;
@property(copy, nonatomic) NSString *position; // @synthesize position=_position;
@property(copy, nonatomic) NSString *detailUrl; // @synthesize detailUrl=_detailUrl;
@property(copy, nonatomic) NSString *teamLogo; // @synthesize teamLogo=_teamLogo;
@property(copy, nonatomic) NSString *teamName; // @synthesize teamName=_teamName;
@property(copy, nonatomic) NSString *value; // @synthesize value=_value;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *playerId; // @synthesize playerId=_playerId;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *serial; // @synthesize serial=_serial;
- (void).cxx_destruct;

@end

