//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSModel.h"

@class NSString;

@interface QSPropsRanklistJumpItem : QSModel
{
    NSString *_jumpIcon;
    NSString *_jumpTitle;
    NSString *_jumpContent1;
    NSString *_jumpContent2;
    NSString *_jumpLinkForWeb;
    NSString *_jumpLinkForApp;
}

@property(copy, nonatomic) NSString *jumpLinkForApp; // @synthesize jumpLinkForApp=_jumpLinkForApp;
@property(copy, nonatomic) NSString *jumpLinkForWeb; // @synthesize jumpLinkForWeb=_jumpLinkForWeb;
@property(copy, nonatomic) NSString *jumpContent2; // @synthesize jumpContent2=_jumpContent2;
@property(copy, nonatomic) NSString *jumpContent1; // @synthesize jumpContent1=_jumpContent1;
@property(copy, nonatomic) NSString *jumpTitle; // @synthesize jumpTitle=_jumpTitle;
@property(copy, nonatomic) NSString *jumpIcon; // @synthesize jumpIcon=_jumpIcon;
- (void).cxx_destruct;

@end

