//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNRootViewControllerDelegate.h"

@class QSPresentedNavigationController;

@protocol QSPresentedNavigationControllerDelegate <QNRootViewControllerDelegate>
- (void)navigationWantsToBeClosed:(QSPresentedNavigationController *)arg1;
@end

