//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSPropsRanklistKickOffData.h"

@class NSString, QSPropsRanklistDetailRankListRankItem;

@interface QSPropsRanklistNormalKickOffData : QSPropsRanklistKickOffData
{
    NSString *_mid;
    NSString *_targetCode;
    long long _rankType;
    QSPropsRanklistDetailRankListRankItem *_kickedOffRankItem;
    NSString *_toPoints;
    NSString *_userId;
    NSString *_leftTeam;
    NSString *_rightTeam;
    NSString *_matchTitle;
}

@property(copy, nonatomic) NSString *matchTitle; // @synthesize matchTitle=_matchTitle;
@property(copy, nonatomic) NSString *rightTeam; // @synthesize rightTeam=_rightTeam;
@property(copy, nonatomic) NSString *leftTeam; // @synthesize leftTeam=_leftTeam;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *toPoints; // @synthesize toPoints=_toPoints;
@property(retain, nonatomic) QSPropsRanklistDetailRankListRankItem *kickedOffRankItem; // @synthesize kickedOffRankItem=_kickedOffRankItem;
@property(nonatomic) long long rankType; // @synthesize rankType=_rankType;
@property(copy, nonatomic) NSString *targetCode; // @synthesize targetCode=_targetCode;
@property(copy, nonatomic) NSString *mid; // @synthesize mid=_mid;
- (void).cxx_destruct;
- (id)buyNum;
- (id)propsid;
- (long long)costKB;
- (id)kickOffRequestData;

@end

