//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSStatedData.h"

@class NSArray, NSString;

@interface QSRanklistData : QSStatedData
{
    NSString *_columnId;
    NSString *_tabType;
    NSArray *_ranklistArray;
}

@property(retain, nonatomic) NSArray *ranklistArray; // @synthesize ranklistArray=_ranklistArray;
@property(copy, nonatomic) NSString *tabType; // @synthesize tabType=_tabType;
@property(copy, nonatomic) NSString *columnId; // @synthesize columnId=_columnId;
- (void).cxx_destruct;
- (id)filteredDataWithOriginalData:(id)arg1;
- (void)resetWithResponseModel:(id)arg1;
- (id)httpURLComponents;
- (id)identifier;

@end

