//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSRichTextPartInfo.h"

@class UIImage;

@interface QSRichTextPartImageInfo : QSRichTextPartInfo
{
    _Bool _selfDefinedAscent;
    UIImage *_image;
    double _leftBlank;
    double _rightBlank;
    double _ascent;
    double _descent;
    double _defaultImageWidth;
    double _offsetY;
}

@property(nonatomic) double offsetY; // @synthesize offsetY=_offsetY;
@property(nonatomic) _Bool selfDefinedAscent; // @synthesize selfDefinedAscent=_selfDefinedAscent;
@property(nonatomic) double defaultImageWidth; // @synthesize defaultImageWidth=_defaultImageWidth;
@property(nonatomic) double descent; // @synthesize descent=_descent;
@property(nonatomic) double ascent; // @synthesize ascent=_ascent;
@property(nonatomic) double rightBlank; // @synthesize rightBlank=_rightBlank;
@property(nonatomic) double leftBlank; // @synthesize leftBlank=_leftBlank;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (id)initWithImage:(id)arg1;

@end

