//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNSportsBundle.h"

@interface QSStaicImage : QNSportsBundle
{
}

+ (id)qsDefaultTeamImage;
+ (id)getSportsImageResourceWithName:(id)arg1;
+ (id)getSportsImageWithName:(id)arg1 resizedImage:(struct CGSize)arg2;
+ (id)getSportsOriginalSizeImageWithName:(id)arg1;
+ (id)getSportsImageWithName:(id)arg1;

@end

