//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QSBaseDataDelegate.h"

@class NSError, QSStatedData;

@protocol QSStatedDataDelegate <QSBaseDataDelegate>

@optional
- (void)data:(QSStatedData *)arg1 didFinishFinallyWithError:(NSError *)arg2;
- (void)data:(QSStatedData *)arg1 didUpdateWithError:(NSError *)arg2;
@end

