//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel;

@interface QSTopicReplyHeadView : UIView
{
    CDUnknownBlockType _chooseBtnDidTapBlock;
    UILabel *_replyLabel;
    UIButton *_replyListOptionChooseBtn;
    UIView *_touchView;
}

@property(retain, nonatomic) UIView *touchView; // @synthesize touchView=_touchView;
@property(retain, nonatomic) UIButton *replyListOptionChooseBtn; // @synthesize replyListOptionChooseBtn=_replyListOptionChooseBtn;
@property(retain, nonatomic) UILabel *replyLabel; // @synthesize replyLabel=_replyLabel;
@property(copy, nonatomic) CDUnknownBlockType chooseBtnDidTapBlock; // @synthesize chooseBtnDidTapBlock=_chooseBtnDidTapBlock;
- (void).cxx_destruct;
- (void)touchViewDidTap:(id)arg1;
- (void)chooseBtnDidTap:(id)arg1;
- (void)setReplyCount:(long long)arg1 option:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

