//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableTableViewCell.h"

#import "KBTableViewCellProtocol.h"

@class KBListItem, NSArray, NSString;

@interface QSVerticalScheduleCell : QNThemableTableViewCell <KBTableViewCellProtocol>
{
    long long _scheduleType;
    id <QSVerticalScheduleCellDelegate> _delegate;
    KBListItem *_kbItem;
    NSArray *_models;
}

+ (struct UIEdgeInsets)cellInsets;
+ (double)heightWithModels:(id)arg1;
+ (double)heightForData:(id)arg1 width:(double)arg2 context:(id)arg3;
@property(retain, nonatomic) NSArray *models; // @synthesize models=_models;
@property(retain, nonatomic) KBListItem *kbItem; // @synthesize kbItem=_kbItem;
@property(nonatomic) __weak id <QSVerticalScheduleCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long scheduleType; // @synthesize scheduleType=_scheduleType;
- (void).cxx_destruct;
- (void)allScheduleButtonDidTap:(id)arg1;
- (void)scheduleViewDidTap:(id)arg1;
- (void)updateWithModels:(id)arg1;
- (void)layoutWithData:(id)arg1 context:(id)arg2;
- (void)themeChanged:(long long)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

