//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QNThemableView.h"

#import "QNPageViewContentViewProtocol.h"

@class NSString, QSMatchItem, UIImageView, UILabel;

@interface QSWorldCupScheduleCell : QNThemableView <QNPageViewContentViewProtocol>
{
    unsigned long long contentIndex;
    NSString *_matchDescEx;
    UILabel *_matchTypeLabel;
    UIImageView *_liveTypeIconView;
    UILabel *_dateLabel;
    UIImageView *_matchStateBackgroundView;
    UILabel *_matchStateLabel;
    UILabel *_titleLabel;
    UILabel *_matchScoreLabel;
    QSMatchItem *_matchItem;
}

@property(retain, nonatomic) QSMatchItem *matchItem; // @synthesize matchItem=_matchItem;
@property(retain, nonatomic) UILabel *matchScoreLabel; // @synthesize matchScoreLabel=_matchScoreLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *matchStateLabel; // @synthesize matchStateLabel=_matchStateLabel;
@property(retain, nonatomic) UIImageView *matchStateBackgroundView; // @synthesize matchStateBackgroundView=_matchStateBackgroundView;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) UIImageView *liveTypeIconView; // @synthesize liveTypeIconView=_liveTypeIconView;
@property(retain, nonatomic) UILabel *matchTypeLabel; // @synthesize matchTypeLabel=_matchTypeLabel;
@property(copy, nonatomic) NSString *matchDescEx; // @synthesize matchDescEx=_matchDescEx;
@property(nonatomic) unsigned long long contentIndex; // @synthesize contentIndex;
- (void).cxx_destruct;
- (void)refreshUIWithMatchItem:(id)arg1;
- (void)updateWithMatchItem:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)themeChanged:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

