//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MVClipVideoView.h"

@class UIImageView, UILabel;

@interface QZEVLimitVideoView : MVClipVideoView
{
    UILabel *_wholeDurationLabel;
    UIImageView *_wholeDurationIcon;
}

@property(nonatomic) __weak UIImageView *wholeDurationIcon; // @synthesize wholeDurationIcon=_wholeDurationIcon;
@property(nonatomic) __weak UILabel *wholeDurationLabel; // @synthesize wholeDurationLabel=_wholeDurationLabel;
- (void).cxx_destruct;
- (void)setMaximumEditableDuration:(long long)arg1;
- (id)tipStringForMaximumDuration;
- (void)updateUIByDuration;
- (void)initUIWithClipModel:(id)arg1;

@end

