//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QZTouchuanPacket.h"

@class NSString;

@interface QZUploadPortait : QZTouchuanPacket
{
    long long _portaitType;
    long long _subid;
    NSString *uinId;
}

@property(retain, nonatomic) NSString *uinId; // @synthesize uinId;
@property(nonatomic) long long subid; // @synthesize subid=_subid;
@property(nonatomic) long long portaitType; // @synthesize portaitType=_portaitType;
- (void).cxx_destruct;
- (id)packetRespWithRspData:(id)arg1;
- (id)transData;
- (id)appidName;
- (id)generateDescription;
- (id)init;

@end

