//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_source>;

@interface RNTimer : NSObject
{
    CDUnknownBlockType _block;
    NSObject<OS_dispatch_source> *_source;
}

+ (id)repeatingTimerWithTimeInterval:(double)arg1 block:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *source; // @synthesize source=_source;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (void)fire;
- (void)dealloc;
- (void)invalidate;

@end

