//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSString;

@interface stAdminBlockUserReq : JceObjectV2
{
    int jcev2_p_1_r_op;
    int jcev2_p_2_o_type;
    NSString *jcev2_p_0_r_person_id;
}

+ (id)jceType;
+ (void)initialize;
@property(nonatomic, getter=jce_type, setter=setJce_type:) int jcev2_p_2_o_type; // @synthesize jcev2_p_2_o_type;
@property(nonatomic, getter=jce_op, setter=setJce_op:) int jcev2_p_1_r_op; // @synthesize jcev2_p_1_r_op;
@property(retain, nonatomic, getter=jce_person_id, setter=setJce_person_id:) NSString *jcev2_p_0_r_person_id; // @synthesize jcev2_p_0_r_person_id;
- (void).cxx_destruct;
- (id)init;

@end

