//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSArray, stMetaPerson;

@interface stGetCyclyingItemRsp : JceObjectV2
{
    NSArray *jcev2_p_0_o_cyclyingfeeds__b0x9i_VOstMetaFeed;
    NSArray *jcev2_p_1_o_cyclyingtopics__b0x9i_VOstMetaTopicAndFeed;
    stMetaPerson *jcev2_p_2_o_lastSharePerson;
    stMetaPerson *jcev2_p_3_o_loginPerson;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_loginPerson, setter=setJce_loginPerson:) stMetaPerson *jcev2_p_3_o_loginPerson; // @synthesize jcev2_p_3_o_loginPerson;
@property(retain, nonatomic, getter=jce_lastSharePerson, setter=setJce_lastSharePerson:) stMetaPerson *jcev2_p_2_o_lastSharePerson; // @synthesize jcev2_p_2_o_lastSharePerson;
@property(retain, nonatomic, getter=jce_cyclyingtopics, setter=setJce_cyclyingtopics:) NSArray *jcev2_p_1_o_cyclyingtopics__b0x9i_VOstMetaTopicAndFeed; // @synthesize jcev2_p_1_o_cyclyingtopics__b0x9i_VOstMetaTopicAndFeed;
@property(retain, nonatomic, getter=jce_cyclyingfeeds, setter=setJce_cyclyingfeeds:) NSArray *jcev2_p_0_o_cyclyingfeeds__b0x9i_VOstMetaFeed; // @synthesize jcev2_p_0_o_cyclyingfeeds__b0x9i_VOstMetaFeed;
- (void).cxx_destruct;
- (id)init;

@end

