//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class stMetaPerson;

@interface stLoginExtra : JceObjectV2
{
    stMetaPerson *jcev2_p_0_o_personInfo;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_personInfo, setter=setJce_personInfo:) stMetaPerson *jcev2_p_0_o_personInfo; // @synthesize jcev2_p_0_o_personInfo;
- (void).cxx_destruct;
- (id)init;

@end

