//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSArray, NSDictionary, NSString;

@interface stMetaInteraction : JceObjectV2
{
    int jcev2_p_1_o_type;
    int jcev2_p_4_o_score;
    NSDictionary *jcev2_p_0_o_mpEx__b0x9i_M09ONSStringONSString;
    NSString *jcev2_p_2_o_person_id;
    NSString *jcev2_p_3_o_feed_id;
    NSArray *jcev2_p_5_o_buttons__b0x9i_VOstActiveButton;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_buttons, setter=setJce_buttons:) NSArray *jcev2_p_5_o_buttons__b0x9i_VOstActiveButton; // @synthesize jcev2_p_5_o_buttons__b0x9i_VOstActiveButton;
@property(nonatomic, getter=jce_score, setter=setJce_score:) int jcev2_p_4_o_score; // @synthesize jcev2_p_4_o_score;
@property(retain, nonatomic, getter=jce_feed_id, setter=setJce_feed_id:) NSString *jcev2_p_3_o_feed_id; // @synthesize jcev2_p_3_o_feed_id;
@property(retain, nonatomic, getter=jce_person_id, setter=setJce_person_id:) NSString *jcev2_p_2_o_person_id; // @synthesize jcev2_p_2_o_person_id;
@property(nonatomic, getter=jce_type, setter=setJce_type:) int jcev2_p_1_o_type; // @synthesize jcev2_p_1_o_type;
@property(retain, nonatomic, getter=jce_mpEx, setter=setJce_mpEx:) NSDictionary *jcev2_p_0_o_mpEx__b0x9i_M09ONSStringONSString; // @synthesize jcev2_p_0_o_mpEx__b0x9i_M09ONSStringONSString;
- (void).cxx_destruct;
- (id)init;

@end

