//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSDictionary, NSString;

@interface stMetaOrnament : JceObjectV2
{
    NSDictionary *jcev2_p_0_o_mpEx__b0x9i_M09ONSStringONSString;
    NSString *jcev2_p_1_o_filter_id;
    NSString *jcev2_p_2_o_filter_name;
    NSString *jcev2_p_3_o_pendant_id;
    NSString *jcev2_p_4_o_pendant_cate;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_pendant_cate, setter=setJce_pendant_cate:) NSString *jcev2_p_4_o_pendant_cate; // @synthesize jcev2_p_4_o_pendant_cate;
@property(retain, nonatomic, getter=jce_pendant_id, setter=setJce_pendant_id:) NSString *jcev2_p_3_o_pendant_id; // @synthesize jcev2_p_3_o_pendant_id;
@property(retain, nonatomic, getter=jce_filter_name, setter=setJce_filter_name:) NSString *jcev2_p_2_o_filter_name; // @synthesize jcev2_p_2_o_filter_name;
@property(retain, nonatomic, getter=jce_filter_id, setter=setJce_filter_id:) NSString *jcev2_p_1_o_filter_id; // @synthesize jcev2_p_1_o_filter_id;
@property(retain, nonatomic, getter=jce_mpEx, setter=setJce_mpEx:) NSDictionary *jcev2_p_0_o_mpEx__b0x9i_M09ONSStringONSString; // @synthesize jcev2_p_0_o_mpEx__b0x9i_M09ONSStringONSString;
- (void).cxx_destruct;
- (id)init;

@end

