//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSArray, NSDictionary, NSString, stMetaPerson;

@interface stMetaComment : JceObjectV2
{
    int jcev2_p_6_o_createtime;
    int jcev2_p_7_o_mask;
    int jcev2_p_8_o_robotMode;
    int jcev2_p_10_o_essOpUin;
    unsigned int jcev2_p_11_o_dingNum;
    int jcev2_p_12_o_isDing;
    unsigned int jcev2_p_14_o_replyNum;
    NSString *jcev2_p_0_o_id;
    NSString *jcev2_p_1_o_wording;
    NSString *jcev2_p_2_o_poster_id;
    stMetaPerson *jcev2_p_3_o_poster;
    NSString *jcev2_p_4_o_receiver_id;
    stMetaPerson *jcev2_p_5_o_receiver;
    NSString *jcev2_p_9_o_beReplyCommendId;
    NSArray *jcev2_p_13_o_replyList__b0x9i_VOstMetaReply;
    NSString *jcev2_p_15_o_feedOwnerId;
    NSDictionary *jcev2_p_16_o_reserve__b0x9i_M09ONSNumberONSString;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_reserve, setter=setJce_reserve:) NSDictionary *jcev2_p_16_o_reserve__b0x9i_M09ONSNumberONSString; // @synthesize jcev2_p_16_o_reserve__b0x9i_M09ONSNumberONSString;
@property(retain, nonatomic, getter=jce_feedOwnerId, setter=setJce_feedOwnerId:) NSString *jcev2_p_15_o_feedOwnerId; // @synthesize jcev2_p_15_o_feedOwnerId;
@property(nonatomic, getter=jce_replyNum, setter=setJce_replyNum:) unsigned int jcev2_p_14_o_replyNum; // @synthesize jcev2_p_14_o_replyNum;
@property(retain, nonatomic, getter=jce_replyList, setter=setJce_replyList:) NSArray *jcev2_p_13_o_replyList__b0x9i_VOstMetaReply; // @synthesize jcev2_p_13_o_replyList__b0x9i_VOstMetaReply;
@property(nonatomic, getter=jce_isDing, setter=setJce_isDing:) int jcev2_p_12_o_isDing; // @synthesize jcev2_p_12_o_isDing;
@property(nonatomic, getter=jce_dingNum, setter=setJce_dingNum:) unsigned int jcev2_p_11_o_dingNum; // @synthesize jcev2_p_11_o_dingNum;
@property(nonatomic, getter=jce_essOpUin, setter=setJce_essOpUin:) int jcev2_p_10_o_essOpUin; // @synthesize jcev2_p_10_o_essOpUin;
@property(retain, nonatomic, getter=jce_beReplyCommendId, setter=setJce_beReplyCommendId:) NSString *jcev2_p_9_o_beReplyCommendId; // @synthesize jcev2_p_9_o_beReplyCommendId;
@property(nonatomic, getter=jce_robotMode, setter=setJce_robotMode:) int jcev2_p_8_o_robotMode; // @synthesize jcev2_p_8_o_robotMode;
@property(nonatomic, getter=jce_mask, setter=setJce_mask:) int jcev2_p_7_o_mask; // @synthesize jcev2_p_7_o_mask;
@property(nonatomic, getter=jce_createtime, setter=setJce_createtime:) int jcev2_p_6_o_createtime; // @synthesize jcev2_p_6_o_createtime;
@property(retain, nonatomic, getter=jce_receiver, setter=setJce_receiver:) stMetaPerson *jcev2_p_5_o_receiver; // @synthesize jcev2_p_5_o_receiver;
@property(retain, nonatomic, getter=jce_receiver_id, setter=setJce_receiver_id:) NSString *jcev2_p_4_o_receiver_id; // @synthesize jcev2_p_4_o_receiver_id;
@property(retain, nonatomic, getter=jce_poster, setter=setJce_poster:) stMetaPerson *jcev2_p_3_o_poster; // @synthesize jcev2_p_3_o_poster;
@property(retain, nonatomic, getter=jce_poster_id, setter=setJce_poster_id:) NSString *jcev2_p_2_o_poster_id; // @synthesize jcev2_p_2_o_poster_id;
@property(retain, nonatomic, getter=jce_wording, setter=setJce_wording:) NSString *jcev2_p_1_o_wording; // @synthesize jcev2_p_1_o_wording;
@property(retain, nonatomic, getter=jce_id, setter=setJce_id:) NSString *jcev2_p_0_o_id; // @synthesize jcev2_p_0_o_id;
- (void).cxx_destruct;
- (id)init;

@end

