//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSString, stMetaPerson;

@interface stMetaReply : JceObjectV2
{
    int jcev2_p_4_o_createtime;
    int jcev2_p_5_o_mask;
    NSString *jcev2_p_0_o_id;
    NSString *jcev2_p_1_o_wording;
    stMetaPerson *jcev2_p_2_o_poster;
    stMetaPerson *jcev2_p_3_o_receiver;
    long long jcev2_p_6_o_robotMode;
    NSString *jcev2_p_7_o_beReplyReplyId;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_beReplyReplyId, setter=setJce_beReplyReplyId:) NSString *jcev2_p_7_o_beReplyReplyId; // @synthesize jcev2_p_7_o_beReplyReplyId;
@property(nonatomic, getter=jce_robotMode, setter=setJce_robotMode:) long long jcev2_p_6_o_robotMode; // @synthesize jcev2_p_6_o_robotMode;
@property(nonatomic, getter=jce_mask, setter=setJce_mask:) int jcev2_p_5_o_mask; // @synthesize jcev2_p_5_o_mask;
@property(nonatomic, getter=jce_createtime, setter=setJce_createtime:) int jcev2_p_4_o_createtime; // @synthesize jcev2_p_4_o_createtime;
@property(retain, nonatomic, getter=jce_receiver, setter=setJce_receiver:) stMetaPerson *jcev2_p_3_o_receiver; // @synthesize jcev2_p_3_o_receiver;
@property(retain, nonatomic, getter=jce_poster, setter=setJce_poster:) stMetaPerson *jcev2_p_2_o_poster; // @synthesize jcev2_p_2_o_poster;
@property(retain, nonatomic, getter=jce_wording, setter=setJce_wording:) NSString *jcev2_p_1_o_wording; // @synthesize jcev2_p_1_o_wording;
@property(retain, nonatomic, getter=jce_id, setter=setJce_id:) NSString *jcev2_p_0_o_id; // @synthesize jcev2_p_0_o_id;
- (void).cxx_destruct;
- (id)init;

@end

