//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSDictionary;

@interface stPersonRevPushRec : JceObjectV2
{
    NSDictionary *jcev2_p_0_o_mapRevTimeStamp__b0x9i_M09ONSNumberONSNumber;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_mapRevTimeStamp, setter=setJce_mapRevTimeStamp:) NSDictionary *jcev2_p_0_o_mapRevTimeStamp__b0x9i_M09ONSNumberONSNumber; // @synthesize jcev2_p_0_o_mapRevTimeStamp__b0x9i_M09ONSNumberONSNumber;
- (void).cxx_destruct;
- (id)init;

@end

