//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class stMetaComment;

@interface stPostFeedCommentRsp : JceObjectV2
{
    stMetaComment *jcev2_p_0_r_comment;
    long long jcev2_p_1_o_prompt;
}

+ (id)jceType;
+ (void)initialize;
@property(nonatomic, getter=jce_prompt, setter=setJce_prompt:) long long jcev2_p_1_o_prompt; // @synthesize jcev2_p_1_o_prompt;
@property(retain, nonatomic, getter=jce_comment, setter=setJce_comment:) stMetaComment *jcev2_p_0_r_comment; // @synthesize jcev2_p_0_r_comment;
- (void).cxx_destruct;
- (id)init;

@end

