//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@interface stUserBlackListOperationRsp : JceObjectV2
{
    int jcev2_p_0_r_ret;
}

+ (id)jceType;
+ (void)initialize;
@property(nonatomic, getter=jce_ret, setter=setJce_ret:) int jcev2_p_0_r_ret; // @synthesize jcev2_p_0_r_ret;
- (id)init;

@end

