//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSArray, stShareInfo;

@interface stWSNetFashionRankRsp : JceObjectV2
{
    NSArray *jcev2_p_0_o_feedlist__b0x9i_VOstWSNetFashionFeedRankItem;
    NSArray *jcev2_p_1_o_darenlist__b0x9i_VOstWSNetFashionDarenRankItem;
    stShareInfo *jcev2_p_2_o_shareInfo;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_shareInfo, setter=setJce_shareInfo:) stShareInfo *jcev2_p_2_o_shareInfo; // @synthesize jcev2_p_2_o_shareInfo;
@property(retain, nonatomic, getter=jce_darenlist, setter=setJce_darenlist:) NSArray *jcev2_p_1_o_darenlist__b0x9i_VOstWSNetFashionDarenRankItem; // @synthesize jcev2_p_1_o_darenlist__b0x9i_VOstWSNetFashionDarenRankItem;
@property(retain, nonatomic, getter=jce_feedlist, setter=setJce_feedlist:) NSArray *jcev2_p_0_o_feedlist__b0x9i_VOstWSNetFashionFeedRankItem; // @synthesize jcev2_p_0_o_feedlist__b0x9i_VOstWSNetFashionFeedRankItem;
- (void).cxx_destruct;
- (id)init;

@end

