//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class NSString, stMetaBubble, stMetaMusicBubble, stMetaPendantBubble;

@interface stWSGetBubbleListRsp : JceObjectV2
{
    NSString *jcev2_p_0_o_attach_info;
    stMetaBubble *jcev2_p_1_o_topicBubble;
    stMetaMusicBubble *jcev2_p_2_o_musicBubble;
    stMetaPendantBubble *jcev2_p_3_o_pendantBubble;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_pendantBubble, setter=setJce_pendantBubble:) stMetaPendantBubble *jcev2_p_3_o_pendantBubble; // @synthesize jcev2_p_3_o_pendantBubble;
@property(retain, nonatomic, getter=jce_musicBubble, setter=setJce_musicBubble:) stMetaMusicBubble *jcev2_p_2_o_musicBubble; // @synthesize jcev2_p_2_o_musicBubble;
@property(retain, nonatomic, getter=jce_topicBubble, setter=setJce_topicBubble:) stMetaBubble *jcev2_p_1_o_topicBubble; // @synthesize jcev2_p_1_o_topicBubble;
@property(retain, nonatomic, getter=jce_attach_info, setter=setJce_attach_info:) NSString *jcev2_p_0_o_attach_info; // @synthesize jcev2_p_0_o_attach_info;
- (void).cxx_destruct;
- (id)init;

@end

