//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TADMobileAdConfig : NSObject
{
}

+ (id)appParams;
+ (void)setLogPrinterEnable:(_Bool)arg1;
+ (id)sdkVersion;
+ (void)configureWithChidiPadPaltform:(id)arg1;
+ (void)configureWithChid:(id)arg1;

@end

