//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSTimer;

@interface TADQNDP3Reporter : NSObject
{
    NSMutableArray *_reportItems;
    NSMutableArray *_adCostArray;
    NSTimer *_reportTimer;
    NSMutableDictionary *_landingDurationDict;
    NSMutableDictionary *_channelPVDict;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *channelPVDict; // @synthesize channelPVDict=_channelPVDict;
@property(retain, nonatomic) NSMutableDictionary *landingDurationDict; // @synthesize landingDurationDict=_landingDurationDict;
@property(nonatomic) __weak NSTimer *reportTimer; // @synthesize reportTimer=_reportTimer;
@property(retain, nonatomic) NSMutableArray *adCostArray; // @synthesize adCostArray=_adCostArray;
@property(retain, nonatomic) NSMutableArray *reportItems; // @synthesize reportItems=_reportItems;
- (void).cxx_destruct;
- (void)logChannelPVForReportItem:(id)arg1;
- (void)appWillResignActive:(id)arg1;
- (void)logLandingDurationItem:(id)arg1 adItem:(id)arg2;
- (void)p_send:(id)arg1;
- (void)startReport;
- (void)logAdCostWithNetStatus:(id)arg1 source:(id)arg2 timeStr:(id)arg3;
- (void)logAdCostWithNetStatus:(id)arg1 source:(id)arg2 time:(long long)arg3;
- (void)reportItem:(id)arg1 withAdItem:(id)arg2 state:(int)arg3;
- (void)reportQNDP3Item:(id)arg1 state:(int)arg2;
- (void)reportItem:(id)arg1 state:(int)arg2;
- (void)addReportItem:(id)arg1;
- (void)dealloc;
- (id)init;

@end

