//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TADSSPBaseResponse.h"

@interface TADSSPStreamResponse : TADSSPBaseResponse
{
}

+ (id)p_sortedAdListWithStreamAdList:(id)arg1 bannerAdList:(id)arg2;
+ (id)hotSpotAdListFromResponseStr:(id)arg1 channel:(id)arg2 reportItem:(id)arg3;
+ (id)p_streamAdListFromResponseStr:(id)arg1 channel:(id)arg2 withCurAdList:(id)arg3 reportItem:(id)arg4;
+ (id)parseStreamAdFromResponseStr:(id)arg1 channel:(id)arg2 withCurAdList:(id)arg3 reportItem:(id)arg4;

@end

