//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TADCellViewComponentProtocol.h"
#import "TADVideoFinishCoverDelegate.h"
#import "TADVideoViewProtocol.h"

@class CSelectButton, CSimpleImageView, NSString, QNAdItem, TADVideoFinishCoverView, UIButton;

@interface TADVideoView : UIView <TADVideoFinishCoverDelegate, TADVideoViewProtocol, TADCellViewComponentProtocol>
{
    _Bool _isNoPicMode;
    QNAdItem *_adItem;
    id <TADVideoViewPresenterProtocol> _videoViewPresenter;
    id <TADVideoPlayerProtocol> _videoPlayer;
    id <TADVideoViewDelegate> _delegate;
    unsigned long long _controlViewStyle;
    UIButton *_playerContentView;
    CSelectButton *_playButton;
    CSimpleImageView *_videoBgImageView;
    TADVideoFinishCoverView *_finishCoverView;
    struct CGRect _videoViewRect;
}

+ (double)heightForAdItem:(id)arg1;
@property(retain, nonatomic) TADVideoFinishCoverView *finishCoverView; // @synthesize finishCoverView=_finishCoverView;
@property(nonatomic) _Bool isNoPicMode; // @synthesize isNoPicMode=_isNoPicMode;
@property(retain, nonatomic) CSimpleImageView *videoBgImageView; // @synthesize videoBgImageView=_videoBgImageView;
@property(retain, nonatomic) CSelectButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) UIButton *playerContentView; // @synthesize playerContentView=_playerContentView;
@property(nonatomic) struct CGRect videoViewRect; // @synthesize videoViewRect=_videoViewRect;
@property(nonatomic) unsigned long long controlViewStyle; // @synthesize controlViewStyle=_controlViewStyle;
@property(nonatomic) __weak id <TADVideoViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <TADVideoPlayerProtocol> videoPlayer; // @synthesize videoPlayer=_videoPlayer;
@property(retain, nonatomic) id <TADVideoViewPresenterProtocol> videoViewPresenter; // @synthesize videoViewPresenter=_videoViewPresenter;
@property(retain, nonatomic) QNAdItem *adItem; // @synthesize adItem=_adItem;
- (void).cxx_destruct;
- (void)removeAd;
- (void)hideFinishCoverView;
- (void)showFinishCoverView;
- (void)hideDefaultControl;
- (void)showDefaultControl;
- (void)videoFinishCoverReplayBtnClicked;
- (void)videoFinishCoverDetailBtnClicked;
- (void)playButtonDown:(id)arg1;
- (void)fullPlayerClickBtnClicked;
- (void)onGotoLandingView;
- (void)onShow;
- (void)onHide;
- (void)onFinish;
- (void)onStop;
- (void)onResume;
- (void)onPaused;
- (void)onPlay;
- (void)onMute:(_Bool)arg1;
- (void)p_reloadVideoImageView:(id)arg1;
- (void)layoutWithAdItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 presenter:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

