//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TADAutoCodingCopyingObject.h"

@class NSNumber, NSString;

@interface TSADP3Item : TADAutoCodingCopyingObject
{
    NSNumber *_errorcode;
    NSString *_soid;
    NSString *_oid;
    NSString *_uoid;
    NSString *_cid;
    NSNumber *_isfirst;
    NSNumber *_iscpm;
    NSNumber *_displayid;
    NSNumber *_duration;
    NSString *_channel;
    NSString *_requestid;
    NSString *_networktype;
    NSNumber *_lpLoadDuration;
    NSNumber *_lpStayDuration;
    NSNumber *_skiptime;
    NSNumber *_clicktime;
    NSNumber *_clickx;
    NSNumber *_clicky;
    NSNumber *_loadduration;
    NSNumber *_stayduration;
    NSNumber *_losscode;
    NSNumber *_calltype;
    NSNumber *_callfrom;
    NSString *_callid;
    NSNumber *_playround;
    NSString *_thirdpartyurl;
    NSNumber *_errortype;
    NSNumber *_apptype;
}

@property(retain, nonatomic) NSNumber *apptype; // @synthesize apptype=_apptype;
@property(retain, nonatomic) NSNumber *errortype; // @synthesize errortype=_errortype;
@property(copy, nonatomic) NSString *thirdpartyurl; // @synthesize thirdpartyurl=_thirdpartyurl;
@property(retain, nonatomic) NSNumber *playround; // @synthesize playround=_playround;
@property(copy, nonatomic) NSString *callid; // @synthesize callid=_callid;
@property(retain, nonatomic) NSNumber *callfrom; // @synthesize callfrom=_callfrom;
@property(retain, nonatomic) NSNumber *calltype; // @synthesize calltype=_calltype;
@property(retain, nonatomic) NSNumber *losscode; // @synthesize losscode=_losscode;
@property(retain, nonatomic) NSNumber *stayduration; // @synthesize stayduration=_stayduration;
@property(retain, nonatomic) NSNumber *loadduration; // @synthesize loadduration=_loadduration;
@property(retain, nonatomic) NSNumber *clicky; // @synthesize clicky=_clicky;
@property(retain, nonatomic) NSNumber *clickx; // @synthesize clickx=_clickx;
@property(retain, nonatomic) NSNumber *clicktime; // @synthesize clicktime=_clicktime;
@property(retain, nonatomic) NSNumber *skiptime; // @synthesize skiptime=_skiptime;
@property(retain, nonatomic) NSNumber *lpStayDuration; // @synthesize lpStayDuration=_lpStayDuration;
@property(retain, nonatomic) NSNumber *lpLoadDuration; // @synthesize lpLoadDuration=_lpLoadDuration;
@property(copy, nonatomic) NSString *networktype; // @synthesize networktype=_networktype;
@property(copy, nonatomic) NSString *requestid; // @synthesize requestid=_requestid;
@property(copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(retain, nonatomic) NSNumber *duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSNumber *displayid; // @synthesize displayid=_displayid;
@property(retain, nonatomic) NSNumber *iscpm; // @synthesize iscpm=_iscpm;
@property(retain, nonatomic) NSNumber *isfirst; // @synthesize isfirst=_isfirst;
@property(copy, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(copy, nonatomic) NSString *uoid; // @synthesize uoid=_uoid;
@property(copy, nonatomic) NSString *oid; // @synthesize oid=_oid;
@property(copy, nonatomic) NSString *soid; // @synthesize soid=_soid;
@property(retain, nonatomic) NSNumber *errorcode; // @synthesize errorcode=_errorcode;
- (void).cxx_destruct;
- (void)configDP3ItemWithItemInfo:(id)arg1;
- (id)convertItemToDictionary;

@end

