//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@class TTstVersions;

@interface TTstPTCenterCombinReq : JceObjectV2
{
    TTstVersions *jcev2_p_0_r_versions;
}

+ (id)jceType;
+ (void)initialize;
@property(retain, nonatomic, getter=jce_versions, setter=setJce_versions:) TTstVersions *jcev2_p_0_r_versions; // @synthesize jcev2_p_0_r_versions;
- (void).cxx_destruct;
- (id)init;

@end

