//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ODKV.h"

@interface TVKMTA : ODKV
{
}

+ (void)trackCustomKeyValueEvent:(id)arg1 props:(id)arg2;
+ (void)startWithAppkey:(id)arg1;
+ (void)resetMTA;
+ (void)enableMTA:(_Bool)arg1;
+ (_Bool)supportMTA;

@end

