//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVKPlayerConfig : NSObject
{
}

+ (int)videoDecodeMode;
+ (void)setParamForPlayer:(id)arg1 paramID:(long long)arg2 dataType1:(unsigned long long)arg3 dataType2:(unsigned long long)arg4 key1:(id)arg5 key2:(id)arg6;
+ (void)setParamForPlayer:(id)arg1 paramID:(long long)arg2 dataType:(unsigned long long)arg3 key:(id)arg4;
+ (void)setConfigForPlayer:(id)arg1 param:(id)arg2;

@end

