//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVKPlayerStrategtyUtil : NSObject
{
}

+ (long long)convertPlayerDefinitionWithFileInfo:(id)arg1;
+ (_Bool)needResourceLoaderForMP4;
+ (_Bool)needResourceloader:(_Bool)arg1;
+ (_Bool)urlsContainDomain:(id)arg1;
+ (id)strategyWhenSelfPlayerDisableWithMediaType:(int)arg1 videoUrls:(id)arg2;
+ (id)strategryWhenSelfPlayerEnableWithIsHevc:(_Bool)arg1 mediaType:(int)arg2 videoUrls:(id)arg3;
+ (_Bool)maybeUseClipWithResourceLoaderForMP4;
+ (id)playerStrategyWithMediaPlayInfo:(id)arg1;

@end

