//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVKQNBAVPlayerStateManagerBase.h"

@interface TVKQNBAVPlayerStateManager : TVKQNBAVPlayerStateManagerBase
{
    unsigned long long _avPlayerState;
}

@property(nonatomic) unsigned long long avPlayerState; // @synthesize avPlayerState=_avPlayerState;
- (unsigned long long)state;
@property(readonly, nonatomic) _Bool needPlay; // @dynamic needPlay;
- (_Bool)playFinished;
- (_Bool)playerItemTimeBasePause;
- (_Bool)playerItemTimeBasePlay;
- (_Bool)stop;
- (_Bool)pause;
- (_Bool)play;
- (_Bool)loadVideo;

@end

