//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TVKVideoView;

@protocol TVKVideoViewDelegate <NSObject>

@optional
- (void)videoView:(TVKVideoView *)arg1 newFrame:(struct CGRect)arg2;
@end

