//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface TVKWaterMarkModel : NSObject
{
    NSString *_actionUrl;
    NSArray *_waterInfos;
}

@property(retain, nonatomic) NSArray *waterInfos; // @synthesize waterInfos=_waterInfos;
@property(copy, nonatomic) NSString *actionUrl; // @synthesize actionUrl=_actionUrl;
- (void).cxx_destruct;

@end

