//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (MVSDK)
+ (id)colorWithHex:(long long)arg1 alpha:(float)arg2;
+ (id)colorWithHex:(long long)arg1;
+ (id)MVProcessLine;
+ (id)mv_themeDarkBlueColor;
+ (id)mv_themeGreenColor;
+ (id)mv_themeRedColor;
+ (id)mv_themeMainColor;
+ (id)mv_colorWithHexString:(id)arg1;
+ (double)mv_colorComponentFrom:(id)arg1 start:(unsigned long long)arg2 length:(unsigned long long)arg3;
@end

