//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (TSAHardware)
- (id)tsa_platformString;
- (unsigned long long)tsa_platformType;
- (unsigned long long)tsa_maxSocketBufferSize;
- (unsigned long long)getSysInfo:(unsigned int)arg1;
- (id)tsa_hwmodel;
- (id)tsa_platform;
- (id)getSysInfoByName:(char *)arg1;
@end

