//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (QSComTopicDetailViewController)
- (id)imageOriginRect:(struct CGRect)arg1 scaled:(double)arg2 rotated:(double)arg3;
- (id)imageWithMaxWidthHeigh:(unsigned long long)arg1;
- (id)imageWithNewWidth:(double)arg1;
@end

