//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (Theme)
- (void)do_updateTheme;
- (void)p_setImageLoadItem:(id)arg1;
- (void)p_setImageURL:(id)arg1;
@property(copy, nonatomic, setter=qn_setAlphaPicker:) CDUnknownBlockType qn_alphaPicker;
@property(copy, nonatomic, setter=qn_setImageLoadItemPicker:) CDUnknownBlockType qn_imageLoadItemPicker;
@property(copy, nonatomic, setter=qn_setImageURLPicker:) CDUnknownBlockType qn_imageURLPicker;
@property(copy, nonatomic, setter=qn_setImagePicker:) CDUnknownBlockType qn_imagePicker;
- (void)qn_setThemeExtraBlock:(CDUnknownBlockType)arg1;
- (id)pickers;
@end

