//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JceObjectV2.h"

@interface VideoOrientation : JceObjectV2
{
    long long jcev2_p_0_o_times;
    long long jcev2_p_1_o_orientation;
}

+ (id)jceType;
+ (void)initialize;
@property(nonatomic, getter=jce_orientation, setter=setJce_orientation:) long long jcev2_p_1_o_orientation; // @synthesize jcev2_p_1_o_orientation;
@property(nonatomic, getter=jce_times, setter=setJce_times:) long long jcev2_p_0_o_times; // @synthesize jcev2_p_0_o_times;
- (id)init;

@end

