# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

targetArray = [
    "TestRX",
    "RxDataSourcesDemo",
];

targetArray.each do |t|
  target t do
    
    pod 'RxSwift','~>5.0'
    pod 'RxCocoa','~>5.0'
    pod 'RxDataSources', '~> 4.0'

    pod 'Moya/RxSwift'
    pod 'HandyJSON'
    
    pod 'NSObject+Rx'  # 提供 rx_disposeBag
    pod 'Then'          # 快速初始化的语法糖
    pod 'Reusable'     # 帮助我们优雅的使用自定义cell和view,不再出现Optional
    
    pod 'MJRefresh'
    pod 'Kingfisher'
    pod 'SnapKit'
    
    pod 'SwiftyJSON'
    pod 'ObjectMapper'
    
  end
end
  
# CocoPods 下开启 RxSwift 调试 RxSwift.Resources.total
#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name == 'RxSwift'
#            target.build_configurations.each do |config|
#                if config.name == 'Debug'
#                    config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
#                end
#            end
#        end
#    end
#end
